=== amamatou/GestionScolarite-XML/Validation_xml/Modules.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
elementFormDefault="qualified">

<xs:element name="Modules">
   <xs:complexType>
     <xs:sequence>
      <xs:element name="Module" maxOccurs="12" minOccurs="6">
       <xs:complexType>
        <xs:sequence>
          <xs:element name="CodeModule" type="xs:string"/>
          <xs:element name="ModuleName" type="xs:string"/>
          <xs:element name="ElementName" type="xs:string" maxOccurs="3" minOccurs="1"/>
          <xs:element name="Dept_Attachement" type="xs:string"/>
          <xs:element name="Coordinator" type="xs:string"/>
        </xs:sequence>
       </xs:complexType>
    </xs:element>
   </xs:sequence>
  </xs:complexType> 
  </xs:element>

  </xs:schema>

=== amamatou/GestionScolarite-XML/Fichiers_xml/Modules_AP1.xml
<?xml version="1.0"?>
<Modules xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C://xampp/htdocs/GestionScolarite-XML/Validation_xml/Modules.xsd">
  <Module>
    <CodeModule>AP11</CodeModule>
    <ModuleName>MATHS1</ModuleName>
    <ElementName>ANALYSE1</ElementName>
    <ElementName>ALGEBRE1</ElementName>
    <Dept_Attachement>SIC</Dept_Attachement>
    <Coordinator>SAMADI</Coordinator>
  </Module>
  <Module>
    <CodeModule>AP12</CodeModule>
    <ModuleName>PHYSIQUE1</ModuleName>
    <ElementName>Electrocinetique</ElementName>
    <ElementName>Instumentation1</ElementName>
    <Dept_Attachement>GEI</Dept_Attachement>
    <Coordinator>BRITEL</Coordinator>
  </Module>
  <Module>
    <CodeModule>AP13</CodeModule>
    <ModuleName>MECANIQUE</ModuleName>
    <ElementName>Mecanique de point</ElementName>
    <ElementName>mecanique2</ElementName>
    <Dept_Attachement>GEI</Dept_Attachement>
    <Coordinator>BOUAJAJ</Coordinator>
  </Module>
  <Module>
    <CodeModule>AP14</CodeModule>
    <ModuleName>CHIMIE</ModuleName>
    <ElementName>Atomistique</ElementName>
    <ElementName>Chimie Organique</ElementName>
    <Dept_Attachement>SIC</Dept_Attachement>
    <Coordinator>TOUHAMI</Coordinator>
  </Module>
  <Module>
    <CodeModule>AP15</CodeModule>
    <ModuleName>LC1</ModuleName>
    <ElementName>Francais1</ElementName>
    <ElementName>Activites d'ouverture</ElementName>
    <Dept_Attachement>SIC</Dept_Attachement>
    <Coordinator>HARIS</Coordinator>
  </Module>
  <Module>
    <CodeModule>AP16</CodeModule>
    <ModuleName>MATHS2</ModuleName>
    <ElementName>Algebre2</ElementName>
    <ElementName>Analyse2</ElementName>
    <Dept_Attachement>SIC</Dept_Attachement>
    <Coordinator>EZZINE</Coordinator>
  </Module>
  <Module>
    <CodeModule>AP17</CodeModule>
    <ModuleName>PYSIQUE2</ModuleName>
    <ElementName>Electrostatique</ElementName>
    <ElementName>Magnetostatique</ElementName>
    <Dept_Attachement>SIC</Dept_Attachement>
    <Coordinator>LAHJOMRI</Coordinator>
  </Module>
  <Module>
    <CodeModule>AP18</CodeModule>
    <ModuleName>PYSIQUE3</ModuleName>
    <ElementName>Optique geometrique</ElementName>
    <ElementName>Optique Physique</ElementName>
    <Dept_Attachement>SIC</Dept_Attachement>
    <Coordinator>FILALI</Coordinator>
  </Module>
  <Module>
    <CodeModule>AP19</CodeModule>
    <ModuleName>INFO1</ModuleName>
    <ElementName>Calcul Formel</ElementName>
    <ElementName>algebre de boule</ElementName>
    <Dept_Attachement>SIC</Dept_Attachement>
    <Coordinator>BELMOKADEM</Coordinator>
  </Module>
</Modules>

=== amamatou/GestionScolarite-XML/Fichiers_xml/Modules_GIL3.xml
<?xml version="1.0"?>
<Modules xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C://xampp/htdocs/GestionScolarite-XML/Validation_xml/Modules.xsd">
  <Module>
    <CodeModule>GIL51</CodeModule>
    <ModuleName> Logistique</ModuleName>
    <ElementName>logistique maritine</ElementName>
    <ElementName>E-logistique</ElementName>
    <Dept_Attachement>SIC</Dept_Attachement>
    <Coordinator>kamachi</Coordinator>
  </Module>
  <Module>
    <CodeModule>GIL52</CodeModule>
    <ModuleName>Secutite et energie</ModuleName>
    <ElementName>Securite Ergonomie</ElementName>
    <ElementName>Economie d'energie</ElementName>
    <Dept_Attachement>GEI</Dept_Attachement>
    <Coordinator>sedqui</Coordinator>
  </Module>
  <Module>
    <CodeModule>GIL53</CodeModule>
    <ModuleName>Qualite et environnement</ModuleName>
    <ElementName>management de l'innovation</ElementName>
    <ElementName>Management de qualite</ElementName>
    <Dept_Attachement>GEI</Dept_Attachement>
    <Coordinator>rahali</Coordinator>
  </Module>
  <Module>
    <CodeModule>GIL54</CodeModule>
    <ModuleName>Controle et supervision</ModuleName>
    <ElementName>supervision</ElementName>
    <ElementName>gestion industrielle</ElementName>
    <Dept_Attachement>SIC</Dept_Attachement>
    <Coordinator>sarsri</Coordinator>
  </Module>
  <Module>
    <CodeModule>GIL55</CodeModule>
    <ModuleName>Management de l'entreprise</ModuleName>
    <ElementName>seminaires</ElementName>
    <ElementName>projet libre</ElementName>
    <Dept_Attachement>SIC</Dept_Attachement>
    <Coordinator>sedqui</Coordinator>
  </Module>
  <Module>
    <CodeModule>GIL56</CodeModule>
    <ModuleName>Supply CHAIN</ModuleName>
    <ElementName>ordonnancement</ElementName>
    <ElementName>ordonnancement</ElementName>
    <Dept_Attachement>SIC</Dept_Attachement>
    <Coordinator>SARSRI</Coordinator>
  </Module>
</Modules>

=== amamatou/GestionScolarite-XML/Fichiers_xml/Modules_G3EI1.xml
<?xml version="1.0"?>
<Modules xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C://xampp/htdocs/GestionScolarite-XML/Validation_xml/Modules.xsd">
  <Module>
    <CodeModule>G3EI11</CodeModule>
    <ModuleName>STATISTIQUES</ModuleName>
    <ElementName>Statistiques Appliquees</ElementName>
    <ElementName>Traitement du signal</ElementName>
    <Dept_Attachement>SIC</Dept_Attachement>
    <Coordinator>Chraibi</Coordinator>
  </Module>
  <Module>
    <CodeModule>G3EI12</CodeModule>
    <ModuleName>ELECTRONIQUE</ModuleName>
    <ElementName>Electronique Analogique</ElementName>
    <ElementName>Electronique Numerique</ElementName>
    <Dept_Attachement>GEI</Dept_Attachement>
    <Coordinator>FILALI</Coordinator>
  </Module>
  <Module>
    <CodeModule>G3EI13</CodeModule>
    <ModuleName>MATERIAUX</ModuleName>
    <ElementName>Sciences des materiaux</ElementName>
    <ElementName>Dessin Industriel</ElementName>
    <Dept_Attachement>GEI</Dept_Attachement>
    <Coordinator>BOUAJAJ</Coordinator>
  </Module>
  <Module>
    <CodeModule>G3EI14</CodeModule>
    <ModuleName>INFORMATIQUE</ModuleName>
    <ElementName>bases des donnees</ElementName>
    <ElementName>Technologie web</ElementName>
    <Dept_Attachement>SIC</Dept_Attachement>
    <Coordinator>Derhi</Coordinator>
  </Module>
  <Module>
    <CodeModule>G3EI15</CodeModule>
    <ModuleName>AUTOMATIQUE1</ModuleName>
    <ElementName>electrotechnique</ElementName>
    <ElementName>Automatique lineaire</ElementName>
    <Dept_Attachement>SIC</Dept_Attachement>
    <Coordinator>moussa</Coordinator>
  </Module>
  <Module>
    <CodeModule>G3EI16</CodeModule>
    <ModuleName>MANAGEMENT</ModuleName>
    <ElementName>comptabilite</ElementName>
    <ElementName>Economie</ElementName>
    <Dept_Attachement>SIC</Dept_Attachement>
    <Coordinator>rahali</Coordinator>
  </Module>
  <Module>
    <CodeModule>G3EI17</CodeModule>
    <ModuleName>Thermodynamique industrielle</ModuleName>
    <ElementName>Mecanique des fluides</ElementName>
    <ElementName>Thermodynamique</ElementName>
    <Dept_Attachement>SIC</Dept_Attachement>
    <Coordinator>al alalli</Coordinator>
  </Module>
  <Module>
    <CodeModule>G3EI18</CodeModule>
    <ModuleName>MACHINES INDUSTRIELLES</ModuleName>
    <ElementName>machines thermiques 1</ElementName>
    <ElementName>Machines Electrique</ElementName>
    <Dept_Attachement>SIC</Dept_Attachement>
    <Coordinator>El fadar</Coordinator>
  </Module>
  <Module>
    <CodeModule>G3EI19</CodeModule>
    <ModuleName>SIMULATION</ModuleName>
    <ElementName>Electrotechnique 2</ElementName>
    <ElementName>Td electronique</ElementName>
    <Dept_Attachement>SIC</Dept_Attachement>
    <Coordinator>Moussa</Coordinator>
  </Module>
</Modules>

=== amamatou/GestionScolarite-XML/Fichiers_xml/Modules_G3EI2.xml
<?xml version="1.0"?>
<Modules xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C://xampp/htdocs/GestionScolarite-XML/Validation_xml/Modules.xsd">
  <Module>
    <CodeModule>G3EI31</CodeModule>
    <ModuleName>Automatisme</ModuleName>
    <ElementName>Automatismes industriels</ElementName>
    <ElementName>Supervision</ElementName>
    <Dept_Attachement>SIC</Dept_Attachement>
    <Coordinator>Chater</Coordinator>
  </Module>
  <Module>
    <CodeModule>G3EI32</CodeModule>
    <ModuleName>Technologie</ModuleName>
    <ElementName>RDM</ElementName>
    <ElementName>conception</ElementName>
    <Dept_Attachement>GEI</Dept_Attachement>
    <Coordinator>FILALI</Coordinator>
  </Module>
  <Module>
    <CodeModule>G3EI33</CodeModule>
    <ModuleName>Solaire Thermique</ModuleName>
    <ElementName>Solaire thermique</ElementName>
    <ElementName>Geothermie</ElementName>
    <Dept_Attachement>GEI</Dept_Attachement>
    <Coordinator>EL FADAR</Coordinator>
  </Module>
  <Module>
    <CodeModule>G3EI34</CodeModule>
    <ModuleName>Energie Eolienne</ModuleName>
    <ElementName>Aerodynamique</ElementName>
    <ElementName>Etude economique</ElementName>
    <Dept_Attachement>SIC</Dept_Attachement>
    <Coordinator>motaki</Coordinator>
  </Module>
  <Module>
    <CodeModule>G3EI35</CodeModule>
    <ModuleName>Legislation </ModuleName>
    <ElementName>Techniques EIE</ElementName>
    <ElementName>projet etude</ElementName>
    <Dept_Attachement>SIC</Dept_Attachement>
    <Coordinator>KAMACH</Coordinator>
  </Module>
  <Module>
    <CodeModule>G3EI36</CodeModule>
    <ModuleName>Communication2</ModuleName>
    <ElementName>Allemand</ElementName>
    <ElementName>Anglais</ElementName>
    <Dept_Attachement>SIC</Dept_Attachement>
    <Coordinator>Haris</Coordinator>
  </Module>
  <Module>
    <CodeModule>G3EI37</CodeModule>
    <ModuleName>Technologies</ModuleName>
    <ElementName>Technologie gaziere</ElementName>
    <ElementName>Machines Thermiques</ElementName>
    <Dept_Attachement>SIC</Dept_Attachement>
    <Coordinator>SARSRI</Coordinator>
  </Module>
  <Module>
    <CodeModule>G3EI38</CodeModule>
    <ModuleName>Management</ModuleName>
    <ElementName>Projet ISO</ElementName>
    <ElementName>SME</ElementName>
    <Dept_Attachement>SIC</Dept_Attachement>
    <Coordinator>Khouya</Coordinator>
  </Module>
  <Module>
    <CodeModule>G3EI39</CodeModule>
    <ModuleName>Maintenace et qualite</ModuleName>
    <ElementName>outils qualite</ElementName>
    <ElementName>Maintenance surete</ElementName>
    <Dept_Attachement>SIC</Dept_Attachement>
    <Coordinator>El kalkha</Coordinator>
  </Module>
</Modules>

=== amamatou/GestionScolarite-XML/Fichiers_xml/Modules_GIL2.xml
<?xml version="1.0"?>
<Modules xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C://xampp/htdocs/GestionScolarite-XML/Validation_xml/Modules.xsd">
  <Module>
    <CodeModule>GIL31</CodeModule>
    <ModuleName>Automatisme</ModuleName>
    <ElementName>Automatismes industriels</ElementName>
    <ElementName>Maintenance</ElementName>
    <Dept_Attachement>SIC</Dept_Attachement>
    <Coordinator>EZZINE</Coordinator>
  </Module>
  <Module>
    <CodeModule>GIL32</CodeModule>
    <ModuleName>Commande industriel</ModuleName>
    <ElementName>Commande numerique </ElementName>
    <ElementName>Reseaux locaux</ElementName>
    <Dept_Attachement>GEI</Dept_Attachement>
    <Coordinator>FILALI</Coordinator>
  </Module>
  <Module>
    <CodeModule>GIL33</CodeModule>
    <ModuleName>Outils d'aide </ModuleName>
    <ElementName>Theorie de graphe</ElementName>
    <ElementName>Decision Multicritere</ElementName>
    <Dept_Attachement>GEI</Dept_Attachement>
    <Coordinator>Samadi</Coordinator>
  </Module>
  <Module>
    <CodeModule>GIL34</CodeModule>
    <ModuleName>Fabrication mecanique</ModuleName>
    <ElementName>Procedes de fabrication</ElementName>
    <ElementName>CFAO</ElementName>
    <Dept_Attachement>SIC</Dept_Attachement>
    <Coordinator>motaki</Coordinator>
  </Module>
  <Module>
    <CodeModule>GIL35</CodeModule>
    <ModuleName>Conception Mecanique</ModuleName>
    <ElementName>Conception systeme</ElementName>
    <ElementName>Anaylse de valeur</ElementName>
    <Dept_Attachement>SIC</Dept_Attachement>
    <Coordinator>KAMACH</Coordinator>
  </Module>
  <Module>
    <CodeModule>GIL36</CodeModule>
    <ModuleName>Communication2</ModuleName>
    <ElementName>comptabilite2</ElementName>
    <ElementName>Management de projet</ElementName>
    <Dept_Attachement>SIC</Dept_Attachement>
    <Coordinator>SARSRI</Coordinator>
  </Module>
  <Module>
    <CodeModule>GIL37</CodeModule>
    <ModuleName>Modelisation</ModuleName>
    <ElementName>implantation</ElementName>
    <ElementName>Stimulation</ElementName>
    <Dept_Attachement>SIC</Dept_Attachement>
    <Coordinator>SARSRI</Coordinator>
  </Module>
  <Module>
    <CodeModule>GIL38</CodeModule>
    <ModuleName>Gestion de production</ModuleName>
    <ElementName>GP</ElementName>
    <ElementName>GP avancee</ElementName>
    <Dept_Attachement>SIC</Dept_Attachement>
    <Coordinator>BOUMAN</Coordinator>
  </Module>
  <Module>
    <CodeModule>GIL39</CodeModule>
    <ModuleName>Maintenace et qualite</ModuleName>
    <ElementName>outils qualite</ElementName>
    <ElementName>Anaylse de valeur2</ElementName>
    <Dept_Attachement>SIC</Dept_Attachement>
    <Coordinator>Sedqui</Coordinator>
  </Module>
</Modules>

=== amamatou/GestionScolarite-XML/Fichiers_xml/Modules_G3EI3.xml
<?xml version="1.0"?>
<Modules xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C://xampp/htdocs/GestionScolarite-XML/Validation_xml/Modules.xsd">
  <Module>
    <CodeModule>G3EI51</CodeModule>
    <ModuleName>Valorisation des dechets</ModuleName>
    <ElementName>Biogaz</ElementName>
    <ElementName>Biomasse</ElementName>
    <Dept_Attachement>SIC</Dept_Attachement>
    <Coordinator>Fadar</Coordinator>
  </Module>
  <Module>
    <CodeModule>G3EI52</CodeModule>
    <ModuleName>Responsabilite societale</ModuleName>
    <ElementName>outils RSE</ElementName>
    <ElementName>ISO: 26000</ElementName>
    <Dept_Attachement>GEI</Dept_Attachement>
    <Coordinator>azzabach</Coordinator>
  </Module>
  <Module>
    <CodeModule>G3EI53</CodeModule>
    <ModuleName>Efficacite energetique</ModuleName>
    <ElementName>RTBM</ElementName>
    <ElementName>outils efficacite</ElementName>
    <Dept_Attachement>GEI</Dept_Attachement>
    <Coordinator>khouya</Coordinator>
  </Module>
  <Module>
    <CodeModule>G3EI54</CodeModule>
    <ModuleName>optimisation systemes</ModuleName>
    <ElementName>systemes geographique</ElementName>
    <ElementName>optimisation systeme</ElementName>
    <Dept_Attachement>SIC</Dept_Attachement>
    <Coordinator>chraibi</Coordinator>
  </Module>
  <Module>
    <CodeModule>G3EI55</CodeModule>
    <ModuleName>chauffage et climatisation</ModuleName>
    <ElementName>climatisation d'air</ElementName>
    <ElementName>Poids industriels</ElementName>
    <Dept_Attachement>SIC</Dept_Attachement>
    <Coordinator>kalkha</Coordinator>
  </Module>
  <Module>
    <CodeModule>G3EI56</CodeModule>
    <ModuleName>management de l'entreprise</ModuleName>
    <ElementName>creation entreprise</ElementName>
    <ElementName>seminaires</ElementName>
    <Dept_Attachement>SIC</Dept_Attachement>
    <Coordinator>chraibi</Coordinator>
  </Module>
</Modules>

=== amamatou/GestionScolarite-XML/Fichiers_xml/Modules_AP2.xml
<?xml version="1.0"?>
<Modules xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C://xampp/htdocs/GestionScolarite-XML/Validation_xml/Modules.xsd">
  <Module>
    <CodeModule>AP31</CodeModule>
    <ModuleName>MATHS3</ModuleName>
    <ElementName>ANALYSE3</ElementName>
    <ElementName>ALGEBRE3</ElementName>
    <Dept_Attachement>SIC</Dept_Attachement>
    <Coordinator>EZZINE</Coordinator>
  </Module>
  <Module>
    <CodeModule>AP32</CodeModule>
    <ModuleName>PHYSIQUE4</ModuleName>
    <ElementName>Electromagnetisme</ElementName>
    <ElementName>Electo</ElementName>
    <Dept_Attachement>GEI</Dept_Attachement>
    <Coordinator>chahboun</Coordinator>
  </Module>
  <Module>
    <CodeModule>AP33</CodeModule>
    <ModuleName>MECANIQUE2</ModuleName>
    <ElementName>Mecanique industrielle</ElementName>
    <ElementName>mecanique_ind</ElementName>
    <Dept_Attachement>GEI</Dept_Attachement>
    <Coordinator>SARSRI</Coordinator>
  </Module>
  <Module>
    <CodeModule>AP34</CodeModule>
    <ModuleName>CHIMIE</ModuleName>
    <ElementName>Atomistique</ElementName>
    <ElementName>Chimie Organique</ElementName>
    <Dept_Attachement>SIC</Dept_Attachement>
    <Coordinator>TOUHAMI</Coordinator>
  </Module>
  <Module>
    <CodeModule>AP35</CodeModule>
    <ModuleName>LC3</ModuleName>
    <ElementName>Francais1</ElementName>
    <ElementName>Activites d'ouverture</ElementName>
    <Dept_Attachement>SIC</Dept_Attachement>
    <Coordinator>HARIS</Coordinator>
  </Module>
  <Module>
    <CodeModule>AP36</CodeModule>
    <ModuleName>MATHS4</ModuleName>
    <ElementName>Algebre4</ElementName>
    <ElementName>Analyse4</ElementName>
    <Dept_Attachement>SIC</Dept_Attachement>
    <Coordinator>AMAL</Coordinator>
  </Module>
  <Module>
    <CodeModule>AP37</CodeModule>
    <ModuleName>PYSIQUE5</ModuleName>
    <ElementName>Electronique</ElementName>
    <ElementName>instrumentation2</ElementName>
    <Dept_Attachement>SIC</Dept_Attachement>
    <Coordinator>Britel</Coordinator>
  </Module>
  <Module>
    <CodeModule>AP38</CodeModule>
    <ModuleName>PYSIQUE5</ModuleName>
    <ElementName>Thermodynamique</ElementName>
    <ElementName>instrumentation3</ElementName>
    <Dept_Attachement>SIC</Dept_Attachement>
    <Coordinator>FILALI</Coordinator>
  </Module>
  <Module>
    <CodeModule>AP39</CodeModule>
    <ModuleName>INFO1</ModuleName>
    <ElementName>Programmation C</ElementName>
    <ElementName>Algorithme</ElementName>
    <Dept_Attachement>SIC</Dept_Attachement>
    <Coordinator>ALAMI</Coordinator>
  </Module>
</Modules>

=== amamatou/GestionScolarite-XML/Fichiers_xml/Modules_GINF1.xml
<?xml version="1.0"?>
<Modules xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C://xampp/htdocs/GestionScolarite-XML/Validation_xml/Modules.xsd">
  <Module>
    <CodeModule>GINF11</CodeModule>
    <ModuleName>Maths pour l'ingenieur</ModuleName>
    <ElementName>Analyse numerique</ElementName>
    <ElementName>Statistiques</ElementName>
    <Dept_Attachement>MI</Dept_Attachement>
    <Coordinator>Maouene</Coordinator>
  </Module>
  <Module>
    <CodeModule>GINF12</CodeModule>
    <ModuleName>Signal</ModuleName>
    <ElementName>Traitement de signal</ElementName>
    <ElementName>Probabilites</ElementName>
    <Dept_Attachement>SIC</Dept_Attachement>
    <Coordinator>Filali</Coordinator>
  </Module>
  <Module>
    <CodeModule>GINF13</CodeModule>
    <ModuleName>Electronique 1</ModuleName>
    <ElementName>Electronique analogique</ElementName>
    <ElementName>Electronique  numerique</ElementName>
    <Dept_Attachement>SIC</Dept_Attachement>
    <Coordinator>El Oualkadi</Coordinator>
  </Module>
  <Module>
    <CodeModule>GINF14</CodeModule>
    <ModuleName>Programmation</ModuleName>
    <ElementName>Structure de donnees C</ElementName>
    <ElementName>Programmation web PHP</ElementName>
    <Dept_Attachement>MI</Dept_Attachement>
    <Coordinator>Amechnoue</Coordinator>
  </Module>
  <Module>
    <CodeModule>GINF15</CodeModule>
    <ModuleName>Bases de donnees &amp; Reseaux</ModuleName>
    <ElementName>BD relationnelles</ElementName>
    <ElementName>Concepts fondamentaux des reseaux</ElementName>
    <Dept_Attachement>MI</Dept_Attachement>
    <Coordinator>Tanana</Coordinator>
  </Module>
  <Module>
    <CodeModule>GINF16</CodeModule>
    <ModuleName>Langues et communication 1</ModuleName>
    <ElementName>Methodologie de PP</ElementName>
    <ElementName>Anglais&amp;Espagnol 1</ElementName>
    <Dept_Attachement>SIC</Dept_Attachement>
    <Coordinator>Haris</Coordinator>
  </Module>
  <Module>
    <CodeModule>GINF21</CodeModule>
    <ModuleName>Developpement informatique II</ModuleName>
    <ElementName>C++</ElementName>
    <ElementName>PHP5</ElementName>
    <Dept_Attachement>SIC</Dept_Attachement>
    <Coordinator>El Haddad</Coordinator>
  </Module>
  <Module>
    <CodeModule>GINF22</CodeModule>
    <ModuleName>Bases de donnees: Developpement et Manipulation</ModuleName>
    <ElementName>Methodes de Modelisation de BD</ElementName>
    <ElementName>PLSQL</ElementName>
    <Dept_Attachement>SIC</Dept_Attachement>
    <Coordinator>Fissoune</Coordinator>
  </Module>
  <Module>
    <CodeModule>GINF23</CodeModule>
    <ModuleName>Theorie des Graphes et Recherche operationnelle</ModuleName>
    <ElementName>Recherche operationnelle</ElementName>
    <ElementName>Theorie des Graphes</ElementName>
    <Dept_Attachement>SIC</Dept_Attachement>
    <Coordinator>Samadi</Coordinator>
  </Module>
  <Module>
    <CodeModule>GINF24</CodeModule>
    <ModuleName>Reseaux 1</ModuleName>
    <ElementName>Protocoles et adressage des reseaux</ElementName>
    <ElementName>Technologie des Reseaux</ElementName>
    <Dept_Attachement>MI</Dept_Attachement>
    <Coordinator>Tanana</Coordinator>
  </Module>
  <Module>
    <CodeModule>GINF25</CodeModule>
    <ModuleName>Architectures &amp; Linux</ModuleName>
    <ElementName>Micro-architectures des processeurs</ElementName>
    <ElementName>Syst&#xE8;me d'exploitation Linux</ElementName>
    <Dept_Attachement>SIC</Dept_Attachement>
    <Coordinator>Belmokadem</Coordinator>
  </Module>
  <Module>
    <CodeModule>GINF26</CodeModule>
    <ModuleName>Management de l'entreprise 1</ModuleName>
    <ElementName>Gestion des entreprises 1</ElementName>
    <ElementName>Economie&amp;Comptabilite 1</ElementName>
    <Dept_Attachement>SIC</Dept_Attachement>
    <Coordinator>El Haddad</Coordinator>
  </Module>
</Modules>
