=== amamatou/GestionScolarite-XML/Validation_xml/Modules.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
elementFormDefault="qualified">

<xs:element name="Modules">
   <xs:complexType>
     <xs:sequence>
      <xs:element name="Module" maxOccurs="12" minOccurs="6">
       <xs:complexType>
        <xs:sequence>
          <xs:element name="CodeModule" type="xs:string"/>
          <xs:element name="ModuleName" type="xs:string"/>
          <xs:element name="ElementName" type="xs:string" maxOccurs="3" minOccurs="1"/>
          <xs:element name="Dept_Attachement" type="xs:string"/>
          <xs:element name="Coordinator" type="xs:string"/>
        </xs:sequence>
       </xs:complexType>
    </xs:element>
   </xs:sequence>
  </xs:complexType> 
  </xs:element>

  </xs:schema>

=== amamatou/GestionScolarite-XML/Fichiers_xml/Modules_GINF2.xml
<?xml version="1.0"?>
<Modules xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C://xampp/htdocs/GestionScolarite-XML/Validation_xml/Modules.xsd">
  <Module>
    <CodeModule>GINF31</CodeModule>
    <ModuleName>Programmation orientee objet &amp; XML</ModuleName>
    <ElementName>POO Java</ElementName>
    <ElementName>XML&amp;Applications</ElementName>
    <Dept_Attachement>SIC</Dept_Attachement>
    <Coordinator>El Haddad</Coordinator>
  </Module>
  <Module>
    <CodeModule>GINF32</CodeModule>
    <ModuleName>Qualite &amp; approche processus</ModuleName>
    <ElementName>Cycle de vie logiciel et methodes agiles</ElementName>
    <ElementName>Maitrise et optimisation des processus</ElementName>
    <Dept_Attachement>SIC</Dept_Attachement>
    <Coordinator>Rahali El Azzouzi</Coordinator>
  </Module>
  <Module>
    <CodeModule>GINF33</CodeModule>
    <ModuleName>Modelisation orientee objet et IHM</ModuleName>
    <ElementName>MOO UML</ElementName>
    <ElementName>IHM</ElementName>
    <Dept_Attachement>MI</Dept_Attachement>
    <Coordinator>El Alami Hassoun</Coordinator>
  </Module>
  <Module>
    <CodeModule>GINF34</CodeModule>
    <ModuleName>Bases de donnees avancees I</ModuleName>
    <ElementName>Optimisation et qualite de BD</ElementName>
    <ElementName>Administration et securite des BD</ElementName>
    <Dept_Attachement>SIC</Dept_Attachement>
    <Coordinator>Badir</Coordinator>
  </Module>
  <Module>
    <CodeModule>GINF35</CodeModule>
    <ModuleName>Administration et programmation syst&#xE8;me</ModuleName>
    <ElementName>Administration systemes</ElementName>
    <ElementName>Programmation systemes</ElementName>
    <Dept_Attachement>MI</Dept_Attachement>
    <Coordinator>Amechnoue</Coordinator>
  </Module>
  <Module>
    <CodeModule>GINF36</CodeModule>
    <ModuleName>Langues et communication 2</ModuleName>
    <ElementName>Techniques de communication</ElementName>
    <ElementName>Anglais2&amp;Espagnol2</ElementName>
    <Dept_Attachement>SIC</Dept_Attachement>
    <Coordinator>Haris</Coordinator>
  </Module>
  <Module>
    <CodeModule>GINF41</CodeModule>
    <ModuleName>Technologies distribuees</ModuleName>
    <ElementName>J2EE</ElementName>
    <ElementName>C#</ElementName>
    <Dept_Attachement>SIC</Dept_Attachement>
    <Coordinator>El Haddad</Coordinator>
  </Module>
  <Module>
    <CodeModule>GINF42</CodeModule>
    <ModuleName>Bases de donnees avancees I &amp; Cloud</ModuleName>
    <ElementName>Gestion des donnees complexes</ElementName>
    <ElementName>Gestion des donnees distribuees</ElementName>
    <Dept_Attachement>SIC</Dept_Attachement>
    <Coordinator>Badir</Coordinator>
  </Module>
  <Module>
    <CodeModule>GINF43</CodeModule>
    <ModuleName>Traitement de l'image</ModuleName>
    <ElementName>Traitement de l'image</ElementName>
    <ElementName>Vision numerique</ElementName>
    <Dept_Attachement>SIC</Dept_Attachement>
    <Coordinator>Ezzine</Coordinator>
  </Module>
  <Module>
    <CodeModule>GINF44</CodeModule>
    <ModuleName>Programmation declarative et TAV</ModuleName>
    <ElementName>Programmation declarative</ElementName>
    <ElementName>TAV</ElementName>
    <Dept_Attachement>MI</Dept_Attachement>
    <Coordinator>El Alami Hassoun</Coordinator>
  </Module>
  <Module>
    <CodeModule>GINF45</CodeModule>
    <ModuleName>Securite &amp; cryptographie</ModuleName>
    <ElementName>Securite des systemes</ElementName>
    <ElementName>Cryptographie</ElementName>
    <Dept_Attachement>MI</Dept_Attachement>
    <Coordinator>Lazaar</Coordinator>
  </Module>
  <Module>
    <CodeModule>GINF46</CodeModule>
    <ModuleName>Management de l'entreprise 2</ModuleName>
    <ElementName>Mangement de Projet</ElementName>
    <ElementName>Economie&amp;Comptabilite 2</ElementName>
    <Dept_Attachement>SIC</Dept_Attachement>
    <Coordinator>El Haddad</Coordinator>
  </Module>
</Modules>

=== amamatou/GestionScolarite-XML/Fichiers_xml/Modules_GSTR2.xml
<?xml version="1.0"?>
<Modules xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C://xampp/htdocs/GestionScolarite-XML/Validation_xml/Modules.xsd">
  <Module>
    <CodeModule>GSTR31</CodeModule>
    <ModuleName>Telecom 3</ModuleName>
    <ElementName>Traitement numerique du signal</ElementName>
    <ElementName>Communications Numeriques</ElementName>
    <Dept_Attachement>SIC</Dept_Attachement>
    <Coordinator>Moussaoui</Coordinator>
  </Module>
  <Module>
    <CodeModule>GSTR32</CodeModule>
    <ModuleName>Reseaux 2</ModuleName>
    <ElementName>Protocoles et concepts de routage</ElementName>
    <ElementName>Technologies WAN</ElementName>
    <Dept_Attachement>MI</Dept_Attachement>
    <Coordinator>Tanana</Coordinator>
  </Module>
  <Module>
    <CodeModule>GSTR33</CodeModule>
    <ModuleName>Telecom 4</ModuleName>
    <ElementName>Guides d'Ondes</ElementName>
    <ElementName>Propagation Radio</ElementName>
    <Dept_Attachement>SIC</Dept_Attachement>
    <Coordinator>Laaziz</Coordinator>
  </Module>
  <Module>
    <CodeModule>GSTR34</CodeModule>
    <ModuleName>Telecom 5</ModuleName>
    <ElementName>Antennes</ElementName>
    <ElementName>Dispositifs Micro-ondes</ElementName>
    <Dept_Attachement>SIC</Dept_Attachement>
    <Coordinator>El Oualkadi</Coordinator>
  </Module>
  <Module>
    <CodeModule>GSTR35</CodeModule>
    <ModuleName>Info 2</ModuleName>
    <ElementName>Architectures mobiles</ElementName>
    <ElementName>Programmation VHDL</ElementName>
    <Dept_Attachement>SIC</Dept_Attachement>
    <Coordinator>Belmokadem</Coordinator>
  </Module>
  <Module>
    <CodeModule>GSTR36</CodeModule>
    <ModuleName>Langues et communication 2</ModuleName>
    <ElementName>Techniques de communication</ElementName>
    <ElementName>Anglais2&amp;Espagnol2</ElementName>
    <Dept_Attachement>SIC</Dept_Attachement>
    <Coordinator>Haris</Coordinator>
  </Module>
  <Module>
    <CodeModule>GSTR41</CodeModule>
    <ModuleName>Telecom 6</ModuleName>
    <ElementName>FibresOptiques</ElementName>
    <ElementName>Liaisons Optiques</ElementName>
    <Dept_Attachement>SIC</Dept_Attachement>
    <Coordinator>Laaziz</Coordinator>
  </Module>
  <Module>
    <CodeModule>GSTR42</CodeModule>
    <ModuleName>Traitement de l'image et de la parole</ModuleName>
    <ElementName>Traitement de l'image</ElementName>
    <ElementName>Traitement et codage de la parole</ElementName>
    <Dept_Attachement>SIC</Dept_Attachement>
    <Coordinator>Filali Meknassi</Coordinator>
  </Module>
  <Module>
    <CodeModule>GSTR43</CodeModule>
    <ModuleName>Reseaux 3</ModuleName>
    <ElementName>Reseaux de transport</ElementName>
    <ElementName>Voix sur IP, PABX</ElementName>
    <Dept_Attachement>MI</Dept_Attachement>
    <Coordinator>Ben Achhab</Coordinator>
  </Module>
  <Module>
    <CodeModule>GSTR44</CodeModule>
    <ModuleName>Reseaux 4</ModuleName>
    <ElementName>Administration reseaux</ElementName>
    <ElementName>Programmation reseaux</ElementName>
    <Dept_Attachement>MI</Dept_Attachement>
    <Coordinator>Tanana</Coordinator>
  </Module>
  <Module>
    <CodeModule>GSTR45</CodeModule>
    <ModuleName>Reseaux mobiles 1</ModuleName>
    <ElementName>Reseaux mobiles 1</ElementName>
    <ElementName>Reseaux WPAN, WLAN</ElementName>
    <Dept_Attachement>SIC</Dept_Attachement>
    <Coordinator>Moussaoui</Coordinator>
  </Module>
  <Module>
    <CodeModule>GSTR46</CodeModule>
    <ModuleName>Management de l'entreprise 2</ModuleName>
    <ElementName>Mangement de Projet</ElementName>
    <ElementName>Economie&amp;Comptabilite 2</ElementName>
    <Dept_Attachement>SIC</Dept_Attachement>
    <Coordinator>El Oualkadi</Coordinator>
  </Module>
</Modules>

=== amamatou/GestionScolarite-XML/Fichiers_xml/Modules_GSTR3.xml
<?xml version="1.0"?>
<Modules xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C://xampp/htdocs/GestionScolarite-XML/Validation_xml/Modules.xsd">
  <Module>
    <CodeModule>GSTR51</CodeModule>
    <ModuleName>Reseaux mobiles 2</ModuleName>
    <ElementName>Signalisation 2G/3G</ElementName>
    <ElementName>Reseaux mobiles nouvelle generation</ElementName>
    <Dept_Attachement>SIC</Dept_Attachement>
    <Coordinator>Moussaoui</Coordinator>
  </Module>
  <Module>
    <CodeModule>GSTR52</CodeModule>
    <ModuleName>Securite et Interconnexion des Reseaux</ModuleName>
    <ElementName>Securite des Reseaux</ElementName>
    <ElementName>Cryptographie</ElementName>
    <Dept_Attachement>MI</Dept_Attachement>
    <Coordinator>Lazaar</Coordinator>
  </Module>
  <Module>
    <CodeModule>GSTR53</CodeModule>
    <ModuleName>Telecom 7</ModuleName>
    <ElementName>Telecom Satellitaires</ElementName>
    <ElementName>Reseaux de capteurs sans fils</ElementName>
    <Dept_Attachement>SIC</Dept_Attachement>
    <Coordinator>Chahboun A.</Coordinator>
  </Module>
  <Module>
    <CodeModule>GSTR54</CodeModule>
    <ModuleName>Info 3</ModuleName>
    <ElementName>Fouille de donnees</ElementName>
    <ElementName>Developpement mobile</ElementName>
    <Dept_Attachement>GEI</Dept_Attachement>
    <Coordinator>Lyhyaoui</Coordinator>
  </Module>
  <Module>
    <CodeModule>GSTR55</CodeModule>
    <ModuleName>Telecom 8</ModuleName>
    <ElementName>Projets Telecom</ElementName>
    <ElementName>TP Telecom 3</ElementName>
    <Dept_Attachement>SIC</Dept_Attachement>
    <Coordinator>El Oualkadi</Coordinator>
  </Module>
  <Module>
    <CodeModule>GSTR56</CodeModule>
    <ModuleName>Management de l'entreprise 3</ModuleName>
    <ElementName>Entreprenariat&amp;GRH</ElementName>
    <ElementName>Simulation d'entretien d'embauche et ethique de l'ingenieur</ElementName>
    <Dept_Attachement>SIC</Dept_Attachement>
    <Coordinator>El Oualkadi</Coordinator>
  </Module>
</Modules>

=== amamatou/GestionScolarite-XML/Fichiers_xml/Modules_GSEA3.xml
<?xml version="1.0"?>
<Modules xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C://xampp/htdocs/GestionScolarite-XML/Validation_xml/Modules.xsd">
  <Module>
    <CodeModule>GSEA51</CodeModule>
    <ModuleName>Systemes enbarques</ModuleName>
    <ElementName>Systemes embarques</ElementName>
    <ElementName>Tp sys embarques</ElementName>
    <Dept_Attachement>GEI</Dept_Attachement>
    <Coordinator>El Mourabit</Coordinator>
  </Module>
  <Module>
    <CodeModule>GSEA52</CodeModule>
    <ModuleName>Systemes Temps reel</ModuleName>
    <ElementName>Systemes Temps reel</ElementName>
    <ElementName>Tp sys Temps  reel</ElementName>
    <Dept_Attachement>GEI</Dept_Attachement>
    <Coordinator>Moussa</Coordinator>
  </Module>
  <Module>
    <CodeModule>GSEA53</CodeModule>
    <ModuleName>Verification et developpement mobile</ModuleName>
    <ElementName>DeveloppemtnMobile</ElementName>
    <ElementName>Verification de syst&#xE8;me Temps reel</ElementName>
    <Dept_Attachement>SIC</Dept_Attachement>
    <Coordinator>Belmokadem</Coordinator>
  </Module>
  <Module>
    <CodeModule>GSEA54</CodeModule>
    <ModuleName>Association conv/Machine et modelisation</ModuleName>
    <ElementName>Association conv/Machine</ElementName>
    <ElementName>QSE</ElementName>
    <Dept_Attachement>GEI</Dept_Attachement>
    <Coordinator>El Menzhi</Coordinator>
  </Module>
  <Module>
    <CodeModule>GSEA55</CodeModule>
    <ModuleName>Diagnostic des SA et modelisation</ModuleName>
    <ElementName>Diagnostic des SA</ElementName>
    <ElementName>SYSML-UML</ElementName>
    <Dept_Attachement>SIC</Dept_Attachement>
    <Coordinator>Fissoune</Coordinator>
  </Module>
  <Module>
    <CodeModule>GSEA56</CodeModule>
    <ModuleName>Management de l'entreprise 3</ModuleName>
    <ElementName>Entreprenariat&amp;GRH</ElementName>
    <ElementName>Simulation d'entretien d'embauche et ethique de l'ingenieur</ElementName>
    <Dept_Attachement>GEI</Dept_Attachement>
    <Coordinator>El Mourabit</Coordinator>
  </Module>
</Modules>

=== amamatou/GestionScolarite-XML/Fichiers_xml/Modules_GIL1.xml
<?xml version="1.0"?>
<Modules xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C://xampp/htdocs/GestionScolarite-XML/Validation_xml/Modules.xsd">
  <Module>
    <CodeModule>GIL11</CodeModule>
    <ModuleName>STATISTIQUES</ModuleName>
    <ElementName>Statistiques Appliquees</ElementName>
    <ElementName>Traitement du signal</ElementName>
    <Dept_Attachement>SIC</Dept_Attachement>
    <Coordinator>EZZINE</Coordinator>
  </Module>
  <Module>
    <CodeModule>GIL12</CodeModule>
    <ModuleName>ELECTRONIQUE</ModuleName>
    <ElementName>Electronique Analogique</ElementName>
    <ElementName>Electronique Numerique</ElementName>
    <Dept_Attachement>GEI</Dept_Attachement>
    <Coordinator>FILALI</Coordinator>
  </Module>
  <Module>
    <CodeModule>GIL13</CodeModule>
    <ModuleName>MATERIAUX</ModuleName>
    <ElementName>Sciences des materiaux</ElementName>
    <ElementName>Dessin Industriel</ElementName>
    <Dept_Attachement>GEI</Dept_Attachement>
    <Coordinator>BOUAJAJ</Coordinator>
  </Module>
  <Module>
    <CodeModule>GIL14</CodeModule>
    <ModuleName>INFORMATIQUE</ModuleName>
    <ElementName>bases des donnees</ElementName>
    <ElementName>Technologie web</ElementName>
    <Dept_Attachement>SIC</Dept_Attachement>
    <Coordinator>motaki</Coordinator>
  </Module>
  <Module>
    <CodeModule>GIL15</CodeModule>
    <ModuleName>AUTOMATIQUE1</ModuleName>
    <ElementName>electrotechnique</ElementName>
    <ElementName>Automatique lineaire</ElementName>
    <Dept_Attachement>SIC</Dept_Attachement>
    <Coordinator>moussa</Coordinator>
  </Module>
  <Module>
    <CodeModule>GIL16</CodeModule>
    <ModuleName>MANAGEMENT</ModuleName>
    <ElementName>comptabilite</ElementName>
    <ElementName>Economie</ElementName>
    <Dept_Attachement>SIC</Dept_Attachement>
    <Coordinator>SARSRI</Coordinator>
  </Module>
  <Module>
    <CodeModule>GIL17</CodeModule>
    <ModuleName>RESISTANCE DES MATERIAUX</ModuleName>
    <ElementName>RDM</ElementName>
    <ElementName>TP RDM</ElementName>
    <Dept_Attachement>SIC</Dept_Attachement>
    <Coordinator>SARSRI</Coordinator>
  </Module>
  <Module>
    <CodeModule>GIL18</CodeModule>
    <ModuleName>MACHINES INDUSTRIELLES</ModuleName>
    <ElementName>Machines thermiques</ElementName>
    <ElementName>Machines Electrique</ElementName>
    <Dept_Attachement>SIC</Dept_Attachement>
    <Coordinator>el Menzhi</Coordinator>
  </Module>
  <Module>
    <CodeModule>GIL19</CodeModule>
    <ModuleName>SIMULATION</ModuleName>
    <ElementName>Capteurs</ElementName>
    <ElementName>Td electronique</ElementName>
    <Dept_Attachement>SIC</Dept_Attachement>
    <Coordinator>Moussa</Coordinator>
  </Module>
</Modules>

=== amamatou/GestionScolarite-XML/Fichiers_xml/Modules_GINF3.xml
<?xml version="1.0"?>
<Modules xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C://xampp/htdocs/GestionScolarite-XML/Validation_xml/Modules.xsd">
  <Module>
    <CodeModule>GINF51</CodeModule>
    <ModuleName>Technologies Net et J2EE</ModuleName>
    <ElementName>Architectures J2EE</ElementName>
    <ElementName>Programmation mobile Net</ElementName>
    <Dept_Attachement>SIC</Dept_Attachement>
    <Coordinator>El Haddad</Coordinator>
  </Module>
  <Module>
    <CodeModule>GINF52</CodeModule>
    <ModuleName>Intelligence Artificielle Avancee</ModuleName>
    <ElementName>IA avancee et Web semantique</ElementName>
    <ElementName>Ingenierie de connaissances</ElementName>
    <Dept_Attachement>MI</Dept_Attachement>
    <Coordinator>El Alami Hassoun</Coordinator>
  </Module>
  <Module>
    <CodeModule>GINF53</CodeModule>
    <ModuleName>SI decisionnel et BI</ModuleName>
    <ElementName>Datawarehouse</ElementName>
    <ElementName>BigData </ElementName>
    <Dept_Attachement>SIC</Dept_Attachement>
    <Coordinator>Badir</Coordinator>
  </Module>
  <Module>
    <CodeModule>GINF54</CodeModule>
    <ModuleName>Mangement des systemes d'information</ModuleName>
    <ElementName>Gouvernance des SI</ElementName>
    <ElementName>ERP&amp;CRM</ElementName>
    <Dept_Attachement>SIC</Dept_Attachement>
    <Coordinator>Ezzine</Coordinator>
  </Module>
  <Module>
    <CodeModule>GINF55</CodeModule>
    <ModuleName>Web services et applications </ModuleName>
    <ElementName>Webservices</ElementName>
    <ElementName>E-commerce</ElementName>
    <Dept_Attachement>MI</Dept_Attachement>
    <Coordinator>BenAchhab</Coordinator>
  </Module>
  <Module>
    <CodeModule>GINF56</CodeModule>
    <ModuleName>Management de l'entreprise 3</ModuleName>
    <ElementName>Entreprenariat&amp;GRH</ElementName>
    <ElementName>Simulation d'entretien d'embauche et ethique de l'ingenieur</ElementName>
    <Dept_Attachement>SIC</Dept_Attachement>
    <Coordinator>El Haddad</Coordinator>
  </Module>
</Modules>

=== amamatou/GestionScolarite-XML/Fichiers_xml/Modules_GSTR1.xml
<?xml version="1.0"?>
<Modules xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C://xampp/htdocs/GestionScolarite-XML/Validation_xml/Modules.xsd">
  <Module>
    <CodeModule>GSTR11</CodeModule>
    <ModuleName>Maths pour l'ingenieur</ModuleName>
    <ElementName>Analyse numerique</ElementName>
    <ElementName>Statistiques</ElementName>
    <Dept_Attachement>MI</Dept_Attachement>
    <Coordinator>Maouene</Coordinator>
  </Module>
  <Module>
    <CodeModule>GSTR12</CodeModule>
    <ModuleName>Signal</ModuleName>
    <ElementName>Traitement de signal</ElementName>
    <ElementName>TP Signal</ElementName>
    <Dept_Attachement>GEI</Dept_Attachement>
    <Coordinator>Lyhyaoui</Coordinator>
  </Module>
  <Module>
    <CodeModule>GSTR13</CodeModule>
    <ModuleName>Electronique 1</ModuleName>
    <ElementName>Electronique analogique</ElementName>
    <ElementName>Electronique  numerique</ElementName>
    <Dept_Attachement>SIC</Dept_Attachement>
    <Coordinator>El Oualkadi</Coordinator>
  </Module>
  <Module>
    <CodeModule>GSTR14</CodeModule>
    <ModuleName>Telecom 1</ModuleName>
    <ElementName>Lignes de transimission</ElementName>
    <ElementName>Ondes electromagnetique dans la matiere</ElementName>
    <Dept_Attachement>SIC</Dept_Attachement>
    <Coordinator>chahboun N.</Coordinator>
  </Module>
  <Module>
    <CodeModule>GSTR15</CodeModule>
    <ModuleName>Automatique &amp; reseaux</ModuleName>
    <ElementName>Automatique lineaire</ElementName>
    <ElementName>Concepts fondamentaux des reseaux</ElementName>
    <Dept_Attachement>SIC</Dept_Attachement>
    <Coordinator>Filali Meknassi</Coordinator>
  </Module>
  <Module>
    <CodeModule>GSTR16</CodeModule>
    <ModuleName>Langues et communication 1</ModuleName>
    <ElementName>Methodologie de PP</ElementName>
    <ElementName>Anglais&amp;Espagnol 1</ElementName>
    <Dept_Attachement>SIC</Dept_Attachement>
    <Coordinator>Haris</Coordinator>
  </Module>
  <Module>
    <CodeModule>GSTR21</CodeModule>
    <ModuleName>Electronique 2</ModuleName>
    <ElementName>Micro-architectures des processeurs</ElementName>
    <ElementName>Syst&#xE8;me d'exploitation Linux</ElementName>
    <Dept_Attachement>SIC</Dept_Attachement>
    <Coordinator>Chahboun A.</Coordinator>
  </Module>
  <Module>
    <CodeModule>GSTR22</CodeModule>
    <ModuleName>Info 1</ModuleName>
    <ElementName>POO Java</ElementName>
    <ElementName>MOO UML</ElementName>
    <Dept_Attachement>SIC</Dept_Attachement>
    <Coordinator>Belmokadem</Coordinator>
  </Module>
  <Module>
    <CodeModule>GSTR23</CodeModule>
    <ModuleName>Theorie des Graphes et Applications</ModuleName>
    <ElementName>Recherche operationnelle</ElementName>
    <ElementName>Theorie des Graphes</ElementName>
    <Dept_Attachement>SIC</Dept_Attachement>
    <Coordinator>Samadi</Coordinator>
  </Module>
  <Module>
    <CodeModule>GSTR24</CodeModule>
    <ModuleName>Reseaux 1</ModuleName>
    <ElementName>Protocoles et adressage des reseaux</ElementName>
    <ElementName>Technologie des Reseaux</ElementName>
    <Dept_Attachement>MI</Dept_Attachement>
    <Coordinator>Tanana</Coordinator>
  </Module>
  <Module>
    <CodeModule>GSTR25</CodeModule>
    <ModuleName>Telecom 2</ModuleName>
    <ElementName>Communications analogiques</ElementName>
    <ElementName>Theorie de l'information et codage</ElementName>
    <Dept_Attachement>SIC</Dept_Attachement>
    <Coordinator>El Oualkadi</Coordinator>
  </Module>
  <Module>
    <CodeModule>GSTR26</CodeModule>
    <ModuleName>Management de l'entreprise 1</ModuleName>
    <ElementName>Gestion des entreprises 1</ElementName>
    <ElementName>Economie&amp;Comptabilite 1</ElementName>
    <Dept_Attachement>SIC</Dept_Attachement>
    <Coordinator>Haris</Coordinator>
  </Module>
</Modules>

=== amamatou/GestionScolarite-XML/Fichiers_xml/Modules_GSEA1.xml
<?xml version="1.0"?>
<Modules xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C://xampp/htdocs/GestionScolarite-XML/Validation_xml/Modules.xsd">
  <Module>
    <CodeModule>GSEA11</CodeModule>
    <ModuleName>Maths Appliquees</ModuleName>
    <ElementName>Analyse numerique</ElementName>
    <ElementName>Statistiques</ElementName>
    <Dept_Attachement>MI</Dept_Attachement>
    <Coordinator>Maouene</Coordinator>
  </Module>
  <Module>
    <CodeModule>GSEA12</CodeModule>
    <ModuleName>Traitement de signal</ModuleName>
    <ElementName>Traitement de signal</ElementName>
    <ElementName>Probabilites</ElementName>
    <Dept_Attachement>GEI</Dept_Attachement>
    <Coordinator>Lyhyaoui</Coordinator>
  </Module>
  <Module>
    <CodeModule>GSEA13</CodeModule>
    <ModuleName>Electronique 1</ModuleName>
    <ElementName>Electronique analogique</ElementName>
    <ElementName>Electronique  numerique</ElementName>
    <Dept_Attachement>SIC</Dept_Attachement>
    <Coordinator>El Oualkadi</Coordinator>
  </Module>
  <Module>
    <CodeModule>GSEA14</CodeModule>
    <ModuleName>Ondes et propagation</ModuleName>
    <ElementName>Lignes de transimission</ElementName>
    <ElementName>Ondes electromagnetique dans la matiere</ElementName>
    <Dept_Attachement>SIC</Dept_Attachement>
    <Coordinator>chahboun N.</Coordinator>
  </Module>
  <Module>
    <CodeModule>GSEA15</CodeModule>
    <ModuleName>Automatique I et electroch I</ModuleName>
    <ElementName>Electrotechnique</ElementName>
    <ElementName>Automatique Lineaire</ElementName>
    <Dept_Attachement>GEI</Dept_Attachement>
    <Coordinator>Moussa</Coordinator>
  </Module>
  <Module>
    <CodeModule>GSEA16</CodeModule>
    <ModuleName>Langues et communication 1</ModuleName>
    <ElementName>Methodologie de PP</ElementName>
    <ElementName>Anglais&amp;Espagnol 1</ElementName>
    <Dept_Attachement>SIC</Dept_Attachement>
    <Coordinator>Haris</Coordinator>
  </Module>
  <Module>
    <CodeModule>GSEA21</CodeModule>
    <ModuleName>Assembleur, Microprocesseur et Microcontroleur</ModuleName>
    <ElementName>Microcontroleurs</ElementName>
    <ElementName>Assembleur</ElementName>
    <Dept_Attachement>GEI</Dept_Attachement>
    <Coordinator>Cherkaoui</Coordinator>
  </Module>
  <Module>
    <CodeModule>GSEA22</CodeModule>
    <ModuleName>Electronique III </ModuleName>
    <ElementName>Automatisme</ElementName>
    <ElementName>Electronique analogique 2</ElementName>
    <Dept_Attachement>GEI</Dept_Attachement>
    <Coordinator>Cherkaoui</Coordinator>
  </Module>
  <Module>
    <CodeModule>GSEA23</CodeModule>
    <ModuleName>Electrotechnique II et installations electriques</ModuleName>
    <ElementName>Electrotechnique II</ElementName>
    <ElementName>Installations electriques</ElementName>
    <Dept_Attachement>GEI</Dept_Attachement>
    <Coordinator>Azyat</Coordinator>
  </Module>
  <Module>
    <CodeModule>GSEA24</CodeModule>
    <ModuleName>Instrumentation et automatique II</ModuleName>
    <ElementName> Automatique II</ElementName>
    <ElementName>Instrumentation </ElementName>
    <Dept_Attachement>GEI</Dept_Attachement>
    <Coordinator>Derrhi</Coordinator>
  </Module>
  <Module>
    <CodeModule>GSEA25</CodeModule>
    <ModuleName>Informatique</ModuleName>
    <ElementName>BD relationnelles</ElementName>
    <ElementName>PHP</ElementName>
    <Dept_Attachement>SIC</Dept_Attachement>
    <Coordinator>Fissoune</Coordinator>
  </Module>
  <Module>
    <CodeModule>GSEA26</CodeModule>
    <ModuleName>Management de l'entreprise 1</ModuleName>
    <ElementName>Gestion des entreprises 1</ElementName>
    <ElementName>Economie&amp;Comptabilite 1</ElementName>
    <Dept_Attachement>GEI</Dept_Attachement>
    <Coordinator>El Mourabit</Coordinator>
  </Module>
</Modules>
