=== amamatou/GestionScolarite-XML/Validation_xml/Notes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
elementFormDefault="qualified">

  <xs:element name="Notes">
   <xs:complexType>
     <xs:sequence>
      <xs:element name="Note">
       <xs:complexType>
        <xs:sequence>
          <xs:element name="CNE" type="xs:string"/>
          <xs:element name="FirstName" type="xs:string"/>
          <xs:element name="LastName" type="xs:string"/>
          <xs:element name="Matiere" maxOccurs="12" minOccurs="6">
            <xs:complexType>
              <xs:attribute name="codeMatiere" type="xs:string" use="required" />
              <xs:restriction base="xs:float">
                <xs:minInclusive value="0"/>
                <xs:maxInclusive value="20"/>
              </xs:restriction>
            </xs:complexType>  
          </xs:element>
        </xs:sequence>
        </xs:complexType>
    </xs:element>
   </xs:sequence>
  </xs:complexType> 
  </xs:element>
  </xs:schema>

=== amamatou/GestionScolarite-XML/Fichiers_xml/Notes_GSEA2_ApresRat.xml
<?xml version="1.0"?>
<Notes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C://xampp/htdocs/GestionScolarite-XML/Validation_xml/Notes.xsd">
  <Note>
    <CNE>18000021</CNE>
    <LastName>Gsea2_LN1</LastName>
    <FirstName>Gsea2_FN1</FirstName>
    <Matiere codeMatiere="GSEA31">16</Matiere>
    <Matiere codeMatiere="GSEA32">10</Matiere>
    <Matiere codeMatiere="GSEA33">12</Matiere>
    <Matiere codeMatiere="GSEA34">12</Matiere>
    <Matiere codeMatiere="GSEA35">15</Matiere>
    <Matiere codeMatiere="GSEA36">17</Matiere>
    <Matiere codeMatiere="GSEA41">11</Matiere>
    <Matiere codeMatiere="GSEA42">15</Matiere>
    <Matiere codeMatiere="GSEA43">16</Matiere>
    <Matiere codeMatiere="GSEA44">12</Matiere>
    <Matiere codeMatiere="GSEA45">12</Matiere>
    <Matiere codeMatiere="GSEA46">16</Matiere>
  </Note>
  <Note>
    <CNE>18000022</CNE>
    <LastName>Gsea2_LN2</LastName>
    <FirstName>Gsea2_FN2</FirstName>
    <Matiere codeMatiere="GSEA31">12</Matiere>
    <Matiere codeMatiere="GSEA32">20</Matiere>
    <Matiere codeMatiere="GSEA33">12</Matiere>
    <Matiere codeMatiere="GSEA34">16</Matiere>
    <Matiere codeMatiere="GSEA35">15</Matiere>
    <Matiere codeMatiere="GSEA36">19</Matiere>
    <Matiere codeMatiere="GSEA41">13</Matiere>
    <Matiere codeMatiere="GSEA42">12</Matiere>
    <Matiere codeMatiere="GSEA43">12</Matiere>
    <Matiere codeMatiere="GSEA44">12</Matiere>
    <Matiere codeMatiere="GSEA45">17</Matiere>
    <Matiere codeMatiere="GSEA46">12</Matiere>
  </Note>
  <Note>
    <CNE>18000023</CNE>
    <LastName>Gsea2_LN3</LastName>
    <FirstName>Gsea2_FN3</FirstName>
    <Matiere codeMatiere="GSEA31">12</Matiere>
    <Matiere codeMatiere="GSEA32">12</Matiere>
    <Matiere codeMatiere="GSEA33">20</Matiere>
    <Matiere codeMatiere="GSEA34">15</Matiere>
    <Matiere codeMatiere="GSEA35">19</Matiere>
    <Matiere codeMatiere="GSEA36">15</Matiere>
    <Matiere codeMatiere="GSEA41">12</Matiere>
    <Matiere codeMatiere="GSEA42">19</Matiere>
    <Matiere codeMatiere="GSEA43">12</Matiere>
    <Matiere codeMatiere="GSEA44">15</Matiere>
    <Matiere codeMatiere="GSEA45">20</Matiere>
    <Matiere codeMatiere="GSEA46">15</Matiere>
  </Note>
  <Note>
    <CNE>18000024</CNE>
    <LastName>Gsea2_LN4</LastName>
    <FirstName>Gsea2_FN4</FirstName>
    <Matiere codeMatiere="GSEA31">20</Matiere>
    <Matiere codeMatiere="GSEA32">9</Matiere>
    <Matiere codeMatiere="GSEA33">20</Matiere>
    <Matiere codeMatiere="GSEA34">12</Matiere>
    <Matiere codeMatiere="GSEA35">12</Matiere>
    <Matiere codeMatiere="GSEA36">13</Matiere>
    <Matiere codeMatiere="GSEA41">10</Matiere>
    <Matiere codeMatiere="GSEA42">11</Matiere>
    <Matiere codeMatiere="GSEA43">10</Matiere>
    <Matiere codeMatiere="GSEA44">12</Matiere>
    <Matiere codeMatiere="GSEA45">13</Matiere>
    <Matiere codeMatiere="GSEA46">12</Matiere>
  </Note>
  <Note>
    <CNE>18000025</CNE>
    <LastName>Gsea2_LN5</LastName>
    <FirstName>Gsea2_FN5</FirstName>
    <Matiere codeMatiere="GSEA31">14</Matiere>
    <Matiere codeMatiere="GSEA32">12</Matiere>
    <Matiere codeMatiere="GSEA33">12</Matiere>
    <Matiere codeMatiere="GSEA34">15</Matiere>
    <Matiere codeMatiere="GSEA35">12</Matiere>
    <Matiere codeMatiere="GSEA36">18</Matiere>
    <Matiere codeMatiere="GSEA41">8</Matiere>
    <Matiere codeMatiere="GSEA42">12</Matiere>
    <Matiere codeMatiere="GSEA43">18</Matiere>
    <Matiere codeMatiere="GSEA44">13</Matiere>
    <Matiere codeMatiere="GSEA45">12</Matiere>
    <Matiere codeMatiere="GSEA46">12</Matiere>
  </Note>
  <Note>
    <CNE>18000026</CNE>
    <LastName>Gsea2_LN6</LastName>
    <FirstName>Gsea2_FN6</FirstName>
    <Matiere codeMatiere="GSEA31">12</Matiere>
    <Matiere codeMatiere="GSEA32">12</Matiere>
    <Matiere codeMatiere="GSEA33">15</Matiere>
    <Matiere codeMatiere="GSEA34">14</Matiere>
    <Matiere codeMatiere="GSEA35">18</Matiere>
    <Matiere codeMatiere="GSEA36">12</Matiere>
    <Matiere codeMatiere="GSEA41">20</Matiere>
    <Matiere codeMatiere="GSEA42">13</Matiere>
    <Matiere codeMatiere="GSEA43">15</Matiere>
    <Matiere codeMatiere="GSEA44">14</Matiere>
    <Matiere codeMatiere="GSEA45">15</Matiere>
    <Matiere codeMatiere="GSEA46">19</Matiere>
  </Note>
  <Note>
    <CNE>18000027</CNE>
    <LastName>Gsea2_LN7</LastName>
    <FirstName>Gsea2_FN7</FirstName>
    <Matiere codeMatiere="GSEA31">20</Matiere>
    <Matiere codeMatiere="GSEA32">16</Matiere>
    <Matiere codeMatiere="GSEA33">15</Matiere>
    <Matiere codeMatiere="GSEA34">17</Matiere>
    <Matiere codeMatiere="GSEA35">19</Matiere>
    <Matiere codeMatiere="GSEA36">12</Matiere>
    <Matiere codeMatiere="GSEA41">12</Matiere>
    <Matiere codeMatiere="GSEA42">9</Matiere>
    <Matiere codeMatiere="GSEA43">13</Matiere>
    <Matiere codeMatiere="GSEA44">12</Matiere>
    <Matiere codeMatiere="GSEA45">16</Matiere>
    <Matiere codeMatiere="GSEA46">17</Matiere>
  </Note>
  <Note>
    <CNE>18000028</CNE>
    <LastName>Gsea2_LN8</LastName>
    <FirstName>Gsea2_FN8</FirstName>
    <Matiere codeMatiere="GSEA31">19</Matiere>
    <Matiere codeMatiere="GSEA32">17</Matiere>
    <Matiere codeMatiere="GSEA33">16</Matiere>
    <Matiere codeMatiere="GSEA34">20</Matiere>
    <Matiere codeMatiere="GSEA35">18</Matiere>
    <Matiere codeMatiere="GSEA36">16</Matiere>
    <Matiere codeMatiere="GSEA41">12</Matiere>
    <Matiere codeMatiere="GSEA42">17</Matiere>
    <Matiere codeMatiere="GSEA43">13</Matiere>
    <Matiere codeMatiere="GSEA44">20</Matiere>
    <Matiere codeMatiere="GSEA45">12</Matiere>
    <Matiere codeMatiere="GSEA46">12</Matiere>
  </Note>
  <Note>
    <CNE>18000029</CNE>
    <LastName>Gsea2_LN9</LastName>
    <FirstName>Gsea2_FN9</FirstName>
    <Matiere codeMatiere="GSEA31">12</Matiere>
    <Matiere codeMatiere="GSEA32">18</Matiere>
    <Matiere codeMatiere="GSEA33">17</Matiere>
    <Matiere codeMatiere="GSEA34">10</Matiere>
    <Matiere codeMatiere="GSEA35">18</Matiere>
    <Matiere codeMatiere="GSEA36">14</Matiere>
    <Matiere codeMatiere="GSEA41">10</Matiere>
    <Matiere codeMatiere="GSEA42">14</Matiere>
    <Matiere codeMatiere="GSEA43">18</Matiere>
    <Matiere codeMatiere="GSEA44">18</Matiere>
    <Matiere codeMatiere="GSEA45">16</Matiere>
    <Matiere codeMatiere="GSEA46">19</Matiere>
  </Note>
  <Note>
    <CNE>18000030</CNE>
    <LastName>Gsea2_LN10</LastName>
    <FirstName>Gsea2_FN10</FirstName>
    <Matiere codeMatiere="GSEA31">12</Matiere>
    <Matiere codeMatiere="GSEA32">15</Matiere>
    <Matiere codeMatiere="GSEA33">12</Matiere>
    <Matiere codeMatiere="GSEA34">17</Matiere>
    <Matiere codeMatiere="GSEA35">12</Matiere>
    <Matiere codeMatiere="GSEA36">12</Matiere>
    <Matiere codeMatiere="GSEA41">7</Matiere>
    <Matiere codeMatiere="GSEA42">12</Matiere>
    <Matiere codeMatiere="GSEA43">14</Matiere>
    <Matiere codeMatiere="GSEA44">14</Matiere>
    <Matiere codeMatiere="GSEA45">13</Matiere>
    <Matiere codeMatiere="GSEA46">12</Matiere>
  </Note>
</Notes>

=== amamatou/GestionScolarite-XML/Fichiers_xml/Notes_GINF2_Avant.xml
<?xml version="1.0"?>
<Notes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C://xampp/htdocs/GestionScolarite-XML/Validation_xml/Notes.xsd">
  <Note>
    <CNE>18000031</CNE>
    <LastName>Ginf2_LN1</LastName>
    <FirstName>Ginf2_FN1</FirstName>
    <Matiere codeMatiere="GINF31">15</Matiere>
    <Matiere codeMatiere="GINF32">20</Matiere>
    <Matiere codeMatiere="GINF33">11</Matiere>
    <Matiere codeMatiere="GINF34">5</Matiere>
    <Matiere codeMatiere="GINF35">14</Matiere>
    <Matiere codeMatiere="GINF36">17</Matiere>
    <Matiere codeMatiere="GINF41">7</Matiere>
    <Matiere codeMatiere="GINF42">16</Matiere>
    <Matiere codeMatiere="GINF43">18</Matiere>
    <Matiere codeMatiere="GINF44">12</Matiere>
    <Matiere codeMatiere="GINF45">10</Matiere>
    <Matiere codeMatiere="GINF46">14</Matiere>
  </Note>
  <Note>
    <CNE>18000031</CNE>
    <LastName>Ginf2_LN2</LastName>
    <FirstName>Ginf2_FN2</FirstName>
    <Matiere codeMatiere="GINF31">19</Matiere>
    <Matiere codeMatiere="GINF32">11</Matiere>
    <Matiere codeMatiere="GINF33">17</Matiere>
    <Matiere codeMatiere="GINF34">9</Matiere>
    <Matiere codeMatiere="GINF35">13</Matiere>
    <Matiere codeMatiere="GINF36">15</Matiere>
    <Matiere codeMatiere="GINF41">8</Matiere>
    <Matiere codeMatiere="GINF42">15</Matiere>
    <Matiere codeMatiere="GINF43">19</Matiere>
    <Matiere codeMatiere="GINF44">15</Matiere>
    <Matiere codeMatiere="GINF45">18</Matiere>
    <Matiere codeMatiere="GINF46">19</Matiere>
  </Note>
  <Note>
    <CNE>18000031</CNE>
    <LastName>Ginf2_LN3</LastName>
    <FirstName>Ginf2_FN3</FirstName>
    <Matiere codeMatiere="GINF31">8</Matiere>
    <Matiere codeMatiere="GINF32">18</Matiere>
    <Matiere codeMatiere="GINF33">8</Matiere>
    <Matiere codeMatiere="GINF34">7</Matiere>
    <Matiere codeMatiere="GINF35">18</Matiere>
    <Matiere codeMatiere="GINF36">18</Matiere>
    <Matiere codeMatiere="GINF41">10</Matiere>
    <Matiere codeMatiere="GINF42">9</Matiere>
    <Matiere codeMatiere="GINF43">13</Matiere>
    <Matiere codeMatiere="GINF44">11</Matiere>
    <Matiere codeMatiere="GINF45">18</Matiere>
    <Matiere codeMatiere="GINF46">12</Matiere>
  </Note>
  <Note>
    <CNE>18000031</CNE>
    <LastName>Ginf2_LN4</LastName>
    <FirstName>Ginf2_FN4</FirstName>
    <Matiere codeMatiere="GINF31">18</Matiere>
    <Matiere codeMatiere="GINF32">7</Matiere>
    <Matiere codeMatiere="GINF33">12</Matiere>
    <Matiere codeMatiere="GINF34">9</Matiere>
    <Matiere codeMatiere="GINF35">15</Matiere>
    <Matiere codeMatiere="GINF36">18</Matiere>
    <Matiere codeMatiere="GINF41">15</Matiere>
    <Matiere codeMatiere="GINF42">9</Matiere>
    <Matiere codeMatiere="GINF43">17</Matiere>
    <Matiere codeMatiere="GINF44">20</Matiere>
    <Matiere codeMatiere="GINF45">15</Matiere>
    <Matiere codeMatiere="GINF46">18</Matiere>
  </Note>
  <Note>
    <CNE>18000031</CNE>
    <LastName>Ginf2_LN5</LastName>
    <FirstName>Ginf2_FN5</FirstName>
    <Matiere codeMatiere="GINF31">19</Matiere>
    <Matiere codeMatiere="GINF32">14</Matiere>
    <Matiere codeMatiere="GINF33">9</Matiere>
    <Matiere codeMatiere="GINF34">16</Matiere>
    <Matiere codeMatiere="GINF35">11</Matiere>
    <Matiere codeMatiere="GINF36">14</Matiere>
    <Matiere codeMatiere="GINF41">14</Matiere>
    <Matiere codeMatiere="GINF42">19</Matiere>
    <Matiere codeMatiere="GINF43">13</Matiere>
    <Matiere codeMatiere="GINF44">15</Matiere>
    <Matiere codeMatiere="GINF45">18</Matiere>
    <Matiere codeMatiere="GINF46">18</Matiere>
  </Note>
  <Note>
    <CNE>18000031</CNE>
    <LastName>Ginf2_LN6</LastName>
    <FirstName>Ginf2_FN6</FirstName>
    <Matiere codeMatiere="GINF31">19</Matiere>
    <Matiere codeMatiere="GINF32">7</Matiere>
    <Matiere codeMatiere="GINF33">20</Matiere>
    <Matiere codeMatiere="GINF34">14</Matiere>
    <Matiere codeMatiere="GINF35">19</Matiere>
    <Matiere codeMatiere="GINF36">15</Matiere>
    <Matiere codeMatiere="GINF41">10</Matiere>
    <Matiere codeMatiere="GINF42">11</Matiere>
    <Matiere codeMatiere="GINF43">17</Matiere>
    <Matiere codeMatiere="GINF44">18</Matiere>
    <Matiere codeMatiere="GINF45">15</Matiere>
    <Matiere codeMatiere="GINF46">20</Matiere>
  </Note>
  <Note>
    <CNE>18000031</CNE>
    <LastName>Ginf2_LN7</LastName>
    <FirstName>Ginf2_FN7</FirstName>
    <Matiere codeMatiere="GINF31">6</Matiere>
    <Matiere codeMatiere="GINF32">10</Matiere>
    <Matiere codeMatiere="GINF33">14</Matiere>
    <Matiere codeMatiere="GINF34">7</Matiere>
    <Matiere codeMatiere="GINF35">16</Matiere>
    <Matiere codeMatiere="GINF36">18</Matiere>
    <Matiere codeMatiere="GINF41">16</Matiere>
    <Matiere codeMatiere="GINF42">12</Matiere>
    <Matiere codeMatiere="GINF43">20</Matiere>
    <Matiere codeMatiere="GINF44">11</Matiere>
    <Matiere codeMatiere="GINF45">15</Matiere>
    <Matiere codeMatiere="GINF46">12</Matiere>
  </Note>
  <Note>
    <CNE>18000031</CNE>
    <LastName>Ginf2_LN8</LastName>
    <FirstName>Ginf2_FN8</FirstName>
    <Matiere codeMatiere="GINF31">17</Matiere>
    <Matiere codeMatiere="GINF32">9</Matiere>
    <Matiere codeMatiere="GINF33">18</Matiere>
    <Matiere codeMatiere="GINF34">17</Matiere>
    <Matiere codeMatiere="GINF35">9</Matiere>
    <Matiere codeMatiere="GINF36">16</Matiere>
    <Matiere codeMatiere="GINF41">7</Matiere>
    <Matiere codeMatiere="GINF42">19</Matiere>
    <Matiere codeMatiere="GINF43">16</Matiere>
    <Matiere codeMatiere="GINF44">19</Matiere>
    <Matiere codeMatiere="GINF45">16</Matiere>
    <Matiere codeMatiere="GINF46">14</Matiere>
  </Note>
  <Note>
    <CNE>18000031</CNE>
    <LastName>Ginf2_LN9</LastName>
    <FirstName>Ginf2_FN9</FirstName>
    <Matiere codeMatiere="GINF31">9</Matiere>
    <Matiere codeMatiere="GINF32">17</Matiere>
    <Matiere codeMatiere="GINF33">12</Matiere>
    <Matiere codeMatiere="GINF34">16</Matiere>
    <Matiere codeMatiere="GINF35">15</Matiere>
    <Matiere codeMatiere="GINF36">18</Matiere>
    <Matiere codeMatiere="GINF41">14</Matiere>
    <Matiere codeMatiere="GINF42">6</Matiere>
    <Matiere codeMatiere="GINF43">15</Matiere>
    <Matiere codeMatiere="GINF44">18</Matiere>
    <Matiere codeMatiere="GINF45">9</Matiere>
    <Matiere codeMatiere="GINF46">10</Matiere>
  </Note>
  <Note>
    <CNE>18000031</CNE>
    <LastName>Ginf2_LN10</LastName>
    <FirstName>Ginf2_FN10</FirstName>
    <Matiere codeMatiere="GINF31">12</Matiere>
    <Matiere codeMatiere="GINF32">8</Matiere>
    <Matiere codeMatiere="GINF33">18</Matiere>
    <Matiere codeMatiere="GINF34">18</Matiere>
    <Matiere codeMatiere="GINF35">12</Matiere>
    <Matiere codeMatiere="GINF36">10</Matiere>
    <Matiere codeMatiere="GINF41">15</Matiere>
    <Matiere codeMatiere="GINF42">13</Matiere>
    <Matiere codeMatiere="GINF43">16</Matiere>
    <Matiere codeMatiere="GINF44">20</Matiere>
    <Matiere codeMatiere="GINF45">11</Matiere>
    <Matiere codeMatiere="GINF46">18</Matiere>
  </Note>
</Notes>

=== amamatou/GestionScolarite-XML/Fichiers_xml/Notes_GIL2_Avant.xml
<?xml version="1.0"?>
<Notes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C://xampp/htdocs/GestionScolarite-XML/Validation_xml/Notes.xsd">
  <Note>
    <CNE>18000011</CNE>
    <LastName>GIL2_LN1</LastName>
    <FirstName>GIL2_FN1</FirstName>
    <Matiere codeMatiere="GIL31">12</Matiere>
    <Matiere codeMatiere="GIL32">6.89</Matiere>
    <Matiere codeMatiere="GIL33">19</Matiere>
    <Matiere codeMatiere="GIL34">4.7</Matiere>
    <Matiere codeMatiere="GIL35">12</Matiere>
    <Matiere codeMatiere="GIL36">13</Matiere>
    <Matiere codeMatiere="GIL37">19.32</Matiere>
    <Matiere codeMatiere="GIL38">4.98</Matiere>
    <Matiere codeMatiere="GIL39">12.09</Matiere>
  </Note>
  <Note>
    <CNE>18000012</CNE>
    <LastName>GIL2_LN2</LastName>
    <FirstName>GIL2_FN2</FirstName>
    <Matiere codeMatiere="GIL31">6.8</Matiere>
    <Matiere codeMatiere="GIL32">10.8</Matiere>
    <Matiere codeMatiere="GIL33">17</Matiere>
    <Matiere codeMatiere="GIL34">12.6</Matiere>
    <Matiere codeMatiere="GIL35">15</Matiere>
    <Matiere codeMatiere="GIL36">14</Matiere>
    <Matiere codeMatiere="GIL37">19.65</Matiere>
    <Matiere codeMatiere="GIL38">12</Matiere>
    <Matiere codeMatiere="GIL39">12</Matiere>
  </Note>
  <Note>
    <CNE>18000013</CNE>
    <LastName>GIL2_LN3</LastName>
    <FirstName>GIL2_FN3</FirstName>
    <Matiere codeMatiere="GIL31">15</Matiere>
    <Matiere codeMatiere="GIL32">12</Matiere>
    <Matiere codeMatiere="GIL33">16</Matiere>
    <Matiere codeMatiere="GIL34">13.8</Matiere>
    <Matiere codeMatiere="GIL35">19</Matiere>
    <Matiere codeMatiere="GIL36">15</Matiere>
    <Matiere codeMatiere="GIL37">12</Matiere>
    <Matiere codeMatiere="GIL38">13</Matiere>
    <Matiere codeMatiere="GIL39">12</Matiere>
  </Note>
  <Note>
    <CNE>18000014</CNE>
    <LastName>GIL2_LN4</LastName>
    <FirstName>GIL2_FN4</FirstName>
    <Matiere codeMatiere="GIL31">11</Matiere>
    <Matiere codeMatiere="GIL32">17</Matiere>
    <Matiere codeMatiere="GIL33">15</Matiere>
    <Matiere codeMatiere="GIL34">15</Matiere>
    <Matiere codeMatiere="GIL35">4.5</Matiere>
    <Matiere codeMatiere="GIL36">6</Matiere>
    <Matiere codeMatiere="GIL37">14</Matiere>
    <Matiere codeMatiere="GIL38">10</Matiere>
    <Matiere codeMatiere="GIL39">14</Matiere>
  </Note>
  <Note>
    <CNE>18000015</CNE>
    <LastName>GIL2_LN5</LastName>
    <FirstName>GIL2_FN5</FirstName>
    <Matiere codeMatiere="GIL31">10</Matiere>
    <Matiere codeMatiere="GIL32">10</Matiere>
    <Matiere codeMatiere="GIL33">10</Matiere>
    <Matiere codeMatiere="GIL34">16.8</Matiere>
    <Matiere codeMatiere="GIL35">10.54</Matiere>
    <Matiere codeMatiere="GIL36">8.9</Matiere>
    <Matiere codeMatiere="GIL37">17</Matiere>
    <Matiere codeMatiere="GIL38">14</Matiere>
    <Matiere codeMatiere="GIL39">19</Matiere>
  </Note>
  <Note>
    <CNE>18000016</CNE>
    <LastName>GIL2_LN6</LastName>
    <FirstName>GIL2_FN6</FirstName>
    <Matiere codeMatiere="GIL31">19</Matiere>
    <Matiere codeMatiere="GIL32">19</Matiere>
    <Matiere codeMatiere="GIL33">14</Matiere>
    <Matiere codeMatiere="GIL34">12</Matiere>
    <Matiere codeMatiere="GIL35">13</Matiere>
    <Matiere codeMatiere="GIL36">12</Matiere>
    <Matiere codeMatiere="GIL37">19</Matiere>
    <Matiere codeMatiere="GIL38">15.7</Matiere>
    <Matiere codeMatiere="GIL39">13</Matiere>
  </Note>
  <Note>
    <CNE>18000017</CNE>
    <LastName>GIL2_LN7</LastName>
    <FirstName>GIL2_FN7</FirstName>
    <Matiere codeMatiere="GIL31">14</Matiere>
    <Matiere codeMatiere="GIL32">18</Matiere>
    <Matiere codeMatiere="GIL33">12</Matiere>
    <Matiere codeMatiere="GIL34">10.54</Matiere>
    <Matiere codeMatiere="GIL35">19</Matiere>
    <Matiere codeMatiere="GIL36">10</Matiere>
    <Matiere codeMatiere="GIL37">15</Matiere>
    <Matiere codeMatiere="GIL38">15</Matiere>
    <Matiere codeMatiere="GIL39">10.65</Matiere>
  </Note>
  <Note>
    <CNE>18000018</CNE>
    <LastName>GIL2_LN8</LastName>
    <FirstName>GIL2_FN8</FirstName>
    <Matiere codeMatiere="GIL31">10.54</Matiere>
    <Matiere codeMatiere="GIL32">13</Matiere>
    <Matiere codeMatiere="GIL33">16</Matiere>
    <Matiere codeMatiere="GIL34">12</Matiere>
    <Matiere codeMatiere="GIL35">15</Matiere>
    <Matiere codeMatiere="GIL36">14.63</Matiere>
    <Matiere codeMatiere="GIL37">14</Matiere>
    <Matiere codeMatiere="GIL38">15.92</Matiere>
    <Matiere codeMatiere="GIL39">13</Matiere>
  </Note>
  <Note>
    <CNE>18000019</CNE>
    <LastName>GIL2_LN9</LastName>
    <FirstName>GIL2_FN9</FirstName>
    <Matiere codeMatiere="GIL31">10</Matiere>
    <Matiere codeMatiere="GIL32">13</Matiere>
    <Matiere codeMatiere="GIL33">20</Matiere>
    <Matiere codeMatiere="GIL34">15.76</Matiere>
    <Matiere codeMatiere="GIL35">14</Matiere>
    <Matiere codeMatiere="GIL36">14.02</Matiere>
    <Matiere codeMatiere="GIL37">12</Matiere>
    <Matiere codeMatiere="GIL38">16.32</Matiere>
    <Matiere codeMatiere="GIL39">16</Matiere>
  </Note>
  <Note>
    <CNE>18000020</CNE>
    <LastName>GIL2_LN10</LastName>
    <FirstName>GIL2_FN10</FirstName>
    <Matiere codeMatiere="GIL31">11.85</Matiere>
    <Matiere codeMatiere="GIL32">10</Matiere>
    <Matiere codeMatiere="GIL33">12</Matiere>
    <Matiere codeMatiere="GIL34">9.7</Matiere>
    <Matiere codeMatiere="GIL35">10</Matiere>
    <Matiere codeMatiere="GIL36">17.68</Matiere>
    <Matiere codeMatiere="GIL37">10</Matiere>
    <Matiere codeMatiere="GIL38">8.45</Matiere>
    <Matiere codeMatiere="GIL39">10.74</Matiere>
  </Note>
</Notes>
