=== amamatou/GestionScolarite-XML/Validation_xml/Notes.dtd
<!ELEMENT Notes (Note)*>
<!ELEMENT Note (CNE,FirstName,LastName,Matiere*)>
<!ELEMENT CNE (#PCDATA)>
<!ELEMENT FirstName (#PCDATA)>
<!ELEMENT LastName (#PCDATA)>
<!ELEMENT Matiere (#PCDATA)>
<!ATTLIST Matiere codeMatiere CDATA #REQUIRED>

=== amamatou/GestionScolarite-XML/Fichiers_xml/Notes_GIL3_Apres.xml
<?xml version="1.0"?>
<!DOCTYPE Notes SYSTEM "C://xampp/htdocs/GestionScolarite-XML/Validation_xml//notes.dtd">
<Notes>
  <Note>
    <CNE>17000011</CNE>
    <LastName>GIL3_LN1</LastName>
    <FirstName>GIL3_FN1</FirstName>
    <Matiere codeMatiere="GIL51">14</Matiere>
    <Matiere codeMatiere="GIL52">12</Matiere>
    <Matiere codeMatiere="GIL53">17</Matiere>
    <Matiere codeMatiere="GIL54">12</Matiere>
    <Matiere codeMatiere="GIL55">12</Matiere>
    <Matiere codeMatiere="GIL56">12</Matiere>
  </Note>
  <Note>
    <CNE>17000012</CNE>
    <LastName>GIL3_LN2</LastName>
    <FirstName>GIL3_FN2</FirstName>
    <Matiere codeMatiere="GIL51">13</Matiere>
    <Matiere codeMatiere="GIL52">14</Matiere>
    <Matiere codeMatiere="GIL53">12</Matiere>
    <Matiere codeMatiere="GIL54">13</Matiere>
    <Matiere codeMatiere="GIL55">15</Matiere>
    <Matiere codeMatiere="GIL56">15</Matiere>
  </Note>
  <Note>
    <CNE>17000013</CNE>
    <LastName>GIL3_LN3</LastName>
    <FirstName>GIL3_FN3</FirstName>
    <Matiere codeMatiere="GIL51">12</Matiere>
    <Matiere codeMatiere="GIL52">12</Matiere>
    <Matiere codeMatiere="GIL53">12</Matiere>
    <Matiere codeMatiere="GIL54">12</Matiere>
    <Matiere codeMatiere="GIL55">12</Matiere>
    <Matiere codeMatiere="GIL56">13</Matiere>
  </Note>
  <Note>
    <CNE>17000014</CNE>
    <LastName>GIL3_LN4</LastName>
    <FirstName>GIL3_FN4</FirstName>
    <Matiere codeMatiere="GIL51">19</Matiere>
    <Matiere codeMatiere="GIL52">16</Matiere>
    <Matiere codeMatiere="GIL53">12</Matiere>
    <Matiere codeMatiere="GIL54">12</Matiere>
    <Matiere codeMatiere="GIL55">17</Matiere>
    <Matiere codeMatiere="GIL56">19</Matiere>
  </Note>
  <Note>
    <CNE>17000015</CNE>
    <LastName>GIL3_LN5</LastName>
    <FirstName>GIL3_FN5</FirstName>
    <Matiere codeMatiere="GIL51">17</Matiere>
    <Matiere codeMatiere="GIL52">12</Matiere>
    <Matiere codeMatiere="GIL53">13</Matiere>
    <Matiere codeMatiere="GIL54">10</Matiere>
    <Matiere codeMatiere="GIL55">18</Matiere>
    <Matiere codeMatiere="GIL56">12</Matiere>
  </Note>
  <Note>
    <CNE>17000016</CNE>
    <LastName>GIL3_LN6</LastName>
    <FirstName>GIL3_FN6</FirstName>
    <Matiere codeMatiere="GIL51">16</Matiere>
    <Matiere codeMatiere="GIL52">13</Matiere>
    <Matiere codeMatiere="GIL53">12</Matiere>
    <Matiere codeMatiere="GIL54">10</Matiere>
    <Matiere codeMatiere="GIL55">14</Matiere>
    <Matiere codeMatiere="GIL56">12</Matiere>
  </Note>
  <Note>
    <CNE>17000017</CNE>
    <LastName>GIL3_LN7</LastName>
    <FirstName>GIL3_FN7</FirstName>
    <Matiere codeMatiere="GIL51">12</Matiere>
    <Matiere codeMatiere="GIL52">17</Matiere>
    <Matiere codeMatiere="GIL53">15</Matiere>
    <Matiere codeMatiere="GIL54">12</Matiere>
    <Matiere codeMatiere="GIL55">12</Matiere>
    <Matiere codeMatiere="GIL56">12</Matiere>
  </Note>
  <Note>
    <CNE>17000018</CNE>
    <LastName>GIL3_LN8</LastName>
    <FirstName>GIL3_FN8</FirstName>
    <Matiere codeMatiere="GIL51">12</Matiere>
    <Matiere codeMatiere="GIL52">19</Matiere>
    <Matiere codeMatiere="GIL53">13</Matiere>
    <Matiere codeMatiere="GIL54">14</Matiere>
    <Matiere codeMatiere="GIL55">15</Matiere>
    <Matiere codeMatiere="GIL56">13</Matiere>
  </Note>
  <Note>
    <CNE>17000019</CNE>
    <LastName>GIL3_LN9</LastName>
    <FirstName>GIL3_FN9</FirstName>
    <Matiere codeMatiere="GIL51">15</Matiere>
    <Matiere codeMatiere="GIL52">14</Matiere>
    <Matiere codeMatiere="GIL53">12</Matiere>
    <Matiere codeMatiere="GIL54">12</Matiere>
    <Matiere codeMatiere="GIL55">14</Matiere>
    <Matiere codeMatiere="GIL56">16</Matiere>
  </Note>
  <Note>
    <CNE>17000020</CNE>
    <LastName>GIL3_LN10</LastName>
    <FirstName>GIL3_FN10</FirstName>
    <Matiere codeMatiere="GIL51">12</Matiere>
    <Matiere codeMatiere="GIL52">12</Matiere>
    <Matiere codeMatiere="GIL53">12</Matiere>
    <Matiere codeMatiere="GIL54">13</Matiere>
    <Matiere codeMatiere="GIL55">18</Matiere>
    <Matiere codeMatiere="GIL56">13</Matiere>
  </Note>
</Notes>

=== amamatou/GestionScolarite-XML/Fichiers_xml/Notes_GSTR3_Apres.xml
<?xml version="1.0"?>
<!DOCTYPE Notes SYSTEM "C://xampp/htdocs/GestionScolarite-XML/Validation_xml//notes.dtd">
<Notes>
  <Note>
    <CNE>17000001</CNE>
    <LastName>Gstr3_LN1</LastName>
    <FirstName>Gstr3_FN1</FirstName>
    <Matiere codeMatiere="GSTR51">12</Matiere>
    <Matiere codeMatiere="GSTR52">12</Matiere>
    <Matiere codeMatiere="GSTR53">12</Matiere>
    <Matiere codeMatiere="GSTR54">9</Matiere>
    <Matiere codeMatiere="GSTR55">13</Matiere>
    <Matiere codeMatiere="GSTR56">12</Matiere>
  </Note>
  <Note>
    <CNE>17000002</CNE>
    <LastName>Gstr3_LN2</LastName>
    <FirstName>Gstr3_FN2</FirstName>
    <Matiere codeMatiere="GSTR51">17</Matiere>
    <Matiere codeMatiere="GSTR52">20</Matiere>
    <Matiere codeMatiere="GSTR53">13</Matiere>
    <Matiere codeMatiere="GSTR54">12</Matiere>
    <Matiere codeMatiere="GSTR55">14</Matiere>
    <Matiere codeMatiere="GSTR56">15</Matiere>
  </Note>
  <Note>
    <CNE>17000003</CNE>
    <LastName>Gstr3_LN3</LastName>
    <FirstName>Gstr3_FN3</FirstName>
    <Matiere codeMatiere="GSTR51">12</Matiere>
    <Matiere codeMatiere="GSTR52">19</Matiere>
    <Matiere codeMatiere="GSTR53">20</Matiere>
    <Matiere codeMatiere="GSTR54">15</Matiere>
    <Matiere codeMatiere="GSTR55">16</Matiere>
    <Matiere codeMatiere="GSTR56">14</Matiere>
  </Note>
  <Note>
    <CNE>17000004</CNE>
    <LastName>Gstr3_LN4</LastName>
    <FirstName>Gstr3_FN4</FirstName>
    <Matiere codeMatiere="GSTR51">17</Matiere>
    <Matiere codeMatiere="GSTR52">20</Matiere>
    <Matiere codeMatiere="GSTR53">20</Matiere>
    <Matiere codeMatiere="GSTR54">17</Matiere>
    <Matiere codeMatiere="GSTR55">20</Matiere>
    <Matiere codeMatiere="GSTR56">15</Matiere>
  </Note>
  <Note>
    <CNE>17000005</CNE>
    <LastName>Gstr3_LN5</LastName>
    <FirstName>Gstr3_FN5</FirstName>
    <Matiere codeMatiere="GSTR51">9</Matiere>
    <Matiere codeMatiere="GSTR52">14</Matiere>
    <Matiere codeMatiere="GSTR53">12</Matiere>
    <Matiere codeMatiere="GSTR54">10</Matiere>
    <Matiere codeMatiere="GSTR55">15</Matiere>
    <Matiere codeMatiere="GSTR56">17</Matiere>
  </Note>
  <Note>
    <CNE>17000006</CNE>
    <LastName>Gstr3_LN6</LastName>
    <FirstName>Gstr3_FN6</FirstName>
    <Matiere codeMatiere="GSTR51">11</Matiere>
    <Matiere codeMatiere="GSTR52">12</Matiere>
    <Matiere codeMatiere="GSTR53">15</Matiere>
    <Matiere codeMatiere="GSTR54">12</Matiere>
    <Matiere codeMatiere="GSTR55">13</Matiere>
    <Matiere codeMatiere="GSTR56">17</Matiere>
  </Note>
  <Note>
    <CNE>17000007</CNE>
    <LastName>Gstr3_LN7</LastName>
    <FirstName>Gstr3_FN7</FirstName>
    <Matiere codeMatiere="GSTR51">12</Matiere>
    <Matiere codeMatiere="GSTR52">17</Matiere>
    <Matiere codeMatiere="GSTR53">15</Matiere>
    <Matiere codeMatiere="GSTR54">13</Matiere>
    <Matiere codeMatiere="GSTR55">12</Matiere>
    <Matiere codeMatiere="GSTR56">12</Matiere>
  </Note>
  <Note>
    <CNE>17000008</CNE>
    <LastName>Gstr3_LN8</LastName>
    <FirstName>Gstr3_FN8</FirstName>
    <Matiere codeMatiere="GSTR51">12</Matiere>
    <Matiere codeMatiere="GSTR52">18</Matiere>
    <Matiere codeMatiere="GSTR53">13</Matiere>
    <Matiere codeMatiere="GSTR54">12</Matiere>
    <Matiere codeMatiere="GSTR55">16</Matiere>
    <Matiere codeMatiere="GSTR56">19</Matiere>
  </Note>
  <Note>
    <CNE>17000009</CNE>
    <LastName>Gstr3_LN9</LastName>
    <FirstName>Gstr3_FN9</FirstName>
    <Matiere codeMatiere="GSTR51">10</Matiere>
    <Matiere codeMatiere="GSTR52">15</Matiere>
    <Matiere codeMatiere="GSTR53">17</Matiere>
    <Matiere codeMatiere="GSTR54">14</Matiere>
    <Matiere codeMatiere="GSTR55">15</Matiere>
    <Matiere codeMatiere="GSTR56">10</Matiere>
  </Note>
  <Note>
    <CNE>17000010</CNE>
    <LastName>Gstr3_LN10</LastName>
    <FirstName>Gstr3_FN10</FirstName>
    <Matiere codeMatiere="GSTR51">12</Matiere>
    <Matiere codeMatiere="GSTR52">10</Matiere>
    <Matiere codeMatiere="GSTR53">10</Matiere>
    <Matiere codeMatiere="GSTR54">12</Matiere>
    <Matiere codeMatiere="GSTR55">12</Matiere>
    <Matiere codeMatiere="GSTR56">18</Matiere>
  </Note>
</Notes>

=== amamatou/GestionScolarite-XML/Fichiers_xml/Notes_GIL2.xml
<?xml version="1.0"?>
<!DOCTYPE Notes SYSTEM "C://xampp/htdocs/GestionScolarite-XML/Validation_xml/Notes.dtd">
<Notes>
  <Note>
    <CNE>18000011</CNE>
    <LastName>GIL2_LN1</LastName>
    <FirstName>GIL2_FN1</FirstName>
    <Matiere codeMatiere="GIL31">12</Matiere>
    <Matiere codeMatiere="GIL32">6.89</Matiere>
    <Matiere codeMatiere="GIL33">19</Matiere>
    <Matiere codeMatiere="GIL34">4.7</Matiere>
    <Matiere codeMatiere="GIL35">12</Matiere>
    <Matiere codeMatiere="GIL36">13</Matiere>
    <Matiere codeMatiere="GIL37">19.32</Matiere>
    <Matiere codeMatiere="GIL38">4.98</Matiere>
    <Matiere codeMatiere="GIL39">12.09</Matiere>
  </Note>
  <Note>
    <CNE>18000012</CNE>
    <LastName>GIL2_LN2</LastName>
    <FirstName>GIL2_FN2</FirstName>
    <Matiere codeMatiere="GIL31">6.8</Matiere>
    <Matiere codeMatiere="GIL32">10.8</Matiere>
    <Matiere codeMatiere="GIL33">17</Matiere>
    <Matiere codeMatiere="GIL34">12.6</Matiere>
    <Matiere codeMatiere="GIL35">15</Matiere>
    <Matiere codeMatiere="GIL36">14</Matiere>
    <Matiere codeMatiere="GIL37">19.65</Matiere>
    <Matiere codeMatiere="GIL38">12</Matiere>
    <Matiere codeMatiere="GIL39">12</Matiere>
  </Note>
  <Note>
    <CNE>18000013</CNE>
    <LastName>GIL2_LN3</LastName>
    <FirstName>GIL2_FN3</FirstName>
    <Matiere codeMatiere="GIL31">15</Matiere>
    <Matiere codeMatiere="GIL32">12</Matiere>
    <Matiere codeMatiere="GIL33">16</Matiere>
    <Matiere codeMatiere="GIL34">13.8</Matiere>
    <Matiere codeMatiere="GIL35">19</Matiere>
    <Matiere codeMatiere="GIL36">15</Matiere>
    <Matiere codeMatiere="GIL37">12</Matiere>
    <Matiere codeMatiere="GIL38">13</Matiere>
    <Matiere codeMatiere="GIL39">12</Matiere>
  </Note>
  <Note>
    <CNE>18000014</CNE>
    <LastName>GIL2_LN4</LastName>
    <FirstName>GIL2_FN4</FirstName>
    <Matiere codeMatiere="GIL31">11</Matiere>
    <Matiere codeMatiere="GIL32">17</Matiere>
    <Matiere codeMatiere="GIL33">15</Matiere>
    <Matiere codeMatiere="GIL34">15</Matiere>
    <Matiere codeMatiere="GIL35">4.5</Matiere>
    <Matiere codeMatiere="GIL36">6</Matiere>
    <Matiere codeMatiere="GIL37">14</Matiere>
    <Matiere codeMatiere="GIL38">10</Matiere>
    <Matiere codeMatiere="GIL39">14</Matiere>
  </Note>
  <Note>
    <CNE>18000015</CNE>
    <LastName>GIL2_LN5</LastName>
    <FirstName>GIL2_FN5</FirstName>
    <Matiere codeMatiere="GIL31">10</Matiere>
    <Matiere codeMatiere="GIL32">10</Matiere>
    <Matiere codeMatiere="GIL33">10</Matiere>
    <Matiere codeMatiere="GIL34">16.8</Matiere>
    <Matiere codeMatiere="GIL35">10.54</Matiere>
    <Matiere codeMatiere="GIL36">8.9</Matiere>
    <Matiere codeMatiere="GIL37">17</Matiere>
    <Matiere codeMatiere="GIL38">14</Matiere>
    <Matiere codeMatiere="GIL39">19</Matiere>
  </Note>
  <Note>
    <CNE>18000016</CNE>
    <LastName>GIL2_LN6</LastName>
    <FirstName>GIL2_FN6</FirstName>
    <Matiere codeMatiere="GIL31">19</Matiere>
    <Matiere codeMatiere="GIL32">19</Matiere>
    <Matiere codeMatiere="GIL33">14</Matiere>
    <Matiere codeMatiere="GIL34">12</Matiere>
    <Matiere codeMatiere="GIL35">13</Matiere>
    <Matiere codeMatiere="GIL36">12</Matiere>
    <Matiere codeMatiere="GIL37">19</Matiere>
    <Matiere codeMatiere="GIL38">15.7</Matiere>
    <Matiere codeMatiere="GIL39">13</Matiere>
  </Note>
  <Note>
    <CNE>18000017</CNE>
    <LastName>GIL2_LN7</LastName>
    <FirstName>GIL2_FN7</FirstName>
    <Matiere codeMatiere="GIL31">14</Matiere>
    <Matiere codeMatiere="GIL32">18</Matiere>
    <Matiere codeMatiere="GIL33">12</Matiere>
    <Matiere codeMatiere="GIL34">10.54</Matiere>
    <Matiere codeMatiere="GIL35">19</Matiere>
    <Matiere codeMatiere="GIL36">10</Matiere>
    <Matiere codeMatiere="GIL37">15</Matiere>
    <Matiere codeMatiere="GIL38">15</Matiere>
    <Matiere codeMatiere="GIL39">10.65</Matiere>
  </Note>
  <Note>
    <CNE>18000018</CNE>
    <LastName>GIL2_LN8</LastName>
    <FirstName>GIL2_FN8</FirstName>
    <Matiere codeMatiere="GIL31">10.54</Matiere>
    <Matiere codeMatiere="GIL32">13</Matiere>
    <Matiere codeMatiere="GIL33">16</Matiere>
    <Matiere codeMatiere="GIL34">12</Matiere>
    <Matiere codeMatiere="GIL35">15</Matiere>
    <Matiere codeMatiere="GIL36">14.63</Matiere>
    <Matiere codeMatiere="GIL37">14</Matiere>
    <Matiere codeMatiere="GIL38">15.92</Matiere>
    <Matiere codeMatiere="GIL39">13</Matiere>
  </Note>
  <Note>
    <CNE>18000019</CNE>
    <LastName>GIL2_LN9</LastName>
    <FirstName>GIL2_FN9</FirstName>
    <Matiere codeMatiere="GIL31">10</Matiere>
    <Matiere codeMatiere="GIL32">13</Matiere>
    <Matiere codeMatiere="GIL33">20</Matiere>
    <Matiere codeMatiere="GIL34">15.76</Matiere>
    <Matiere codeMatiere="GIL35">14</Matiere>
    <Matiere codeMatiere="GIL36">14.02</Matiere>
    <Matiere codeMatiere="GIL37">12</Matiere>
    <Matiere codeMatiere="GIL38">16.32</Matiere>
    <Matiere codeMatiere="GIL39">16</Matiere>
  </Note>
  <Note>
    <CNE>18000020</CNE>
    <LastName>GIL2_LN10</LastName>
    <FirstName>GIL2_FN10</FirstName>
    <Matiere codeMatiere="GIL31">11.85</Matiere>
    <Matiere codeMatiere="GIL32">10</Matiere>
    <Matiere codeMatiere="GIL33">12</Matiere>
    <Matiere codeMatiere="GIL34">9.7</Matiere>
    <Matiere codeMatiere="GIL35">10</Matiere>
    <Matiere codeMatiere="GIL36">17.68</Matiere>
    <Matiere codeMatiere="GIL37">10</Matiere>
    <Matiere codeMatiere="GIL38">8.45</Matiere>
    <Matiere codeMatiere="GIL39">10.74</Matiere>
  </Note>
</Notes>

=== amamatou/GestionScolarite-XML/Fichiers_xml/Notes_GIL1_Apres.xml
<?xml version="1.0"?>
<!DOCTYPE Notes SYSTEM "C://xampp/htdocs/GestionScolarite-XML/Validation_xml//notes.dtd">
<Notes>
  <Note>
    <CNE>19000011</CNE>
    <LastName>GIL1_FN1</LastName>
    <FirstName>GIL1_LN1</FirstName>
    <Matiere codeMatiere="GIL11">16</Matiere>
    <Matiere codeMatiere="GIL12">10.87</Matiere>
    <Matiere codeMatiere="GIL13">14</Matiere>
    <Matiere codeMatiere="GIL14">12</Matiere>
    <Matiere codeMatiere="GIL15">17</Matiere>
    <Matiere codeMatiere="GIL16">11.98</Matiere>
    <Matiere codeMatiere="GIL17">19.32</Matiere>
    <Matiere codeMatiere="GIL18">9.98</Matiere>
    <Matiere codeMatiere="GIL19">12.09</Matiere>
  </Note>
  <Note>
    <CNE>19000012</CNE>
    <LastName>GIL1_FN2</LastName>
    <FirstName>GIL1_LN2</FirstName>
    <Matiere codeMatiere="GIL11">14</Matiere>
    <Matiere codeMatiere="GIL12">12</Matiere>
    <Matiere codeMatiere="GIL13">13</Matiere>
    <Matiere codeMatiere="GIL14">13</Matiere>
    <Matiere codeMatiere="GIL15">12</Matiere>
    <Matiere codeMatiere="GIL16">18</Matiere>
    <Matiere codeMatiere="GIL17">19.65</Matiere>
    <Matiere codeMatiere="GIL18">11.97</Matiere>
    <Matiere codeMatiere="GIL19">12</Matiere>
  </Note>
  <Note>
    <CNE>19000013</CNE>
    <LastName>GIL1_FN3</LastName>
    <FirstName>GIL1_LN3</FirstName>
    <Matiere codeMatiere="GIL11">11</Matiere>
    <Matiere codeMatiere="GIL12">13.78</Matiere>
    <Matiere codeMatiere="GIL13">16.54</Matiere>
    <Matiere codeMatiere="GIL14">12.98</Matiere>
    <Matiere codeMatiere="GIL15">14.87</Matiere>
    <Matiere codeMatiere="GIL16">16</Matiere>
    <Matiere codeMatiere="GIL17">12.39</Matiere>
    <Matiere codeMatiere="GIL18">12</Matiere>
    <Matiere codeMatiere="GIL19">17</Matiere>
  </Note>
  <Note>
    <CNE>19000014</CNE>
    <LastName>GIL1_FN4</LastName>
    <FirstName>GIL1_LN4</FirstName>
    <Matiere codeMatiere="GIL11">11.87</Matiere>
    <Matiere codeMatiere="GIL12">12</Matiere>
    <Matiere codeMatiere="GIL13">13</Matiere>
    <Matiere codeMatiere="GIL14">13.45</Matiere>
    <Matiere codeMatiere="GIL15">14</Matiere>
    <Matiere codeMatiere="GIL16">14.98</Matiere>
    <Matiere codeMatiere="GIL17">13.09</Matiere>
    <Matiere codeMatiere="GIL18">13.98</Matiere>
    <Matiere codeMatiere="GIL19">18</Matiere>
  </Note>
  <Note>
    <CNE>19000015</CNE>
    <LastName>GIL1_FN5</LastName>
    <FirstName>GIL1_LN5</FirstName>
    <Matiere codeMatiere="GIL11">14</Matiere>
    <Matiere codeMatiere="GIL12">15.9</Matiere>
    <Matiere codeMatiere="GIL13">12</Matiere>
    <Matiere codeMatiere="GIL14">15.09</Matiere>
    <Matiere codeMatiere="GIL15">12</Matiere>
    <Matiere codeMatiere="GIL16">13.87</Matiere>
    <Matiere codeMatiere="GIL17">17.88</Matiere>
    <Matiere codeMatiere="GIL18">12</Matiere>
    <Matiere codeMatiere="GIL19">12</Matiere>
  </Note>
  <Note>
    <CNE>19000016</CNE>
    <LastName>GIL1_FN6</LastName>
    <FirstName>GIL1_LN6</FirstName>
    <Matiere codeMatiere="GIL11">15</Matiere>
    <Matiere codeMatiere="GIL12">11.87</Matiere>
    <Matiere codeMatiere="GIL13">12</Matiere>
    <Matiere codeMatiere="GIL14">10.87</Matiere>
    <Matiere codeMatiere="GIL15">13</Matiere>
    <Matiere codeMatiere="GIL16">12</Matiere>
    <Matiere codeMatiere="GIL17">12.09</Matiere>
    <Matiere codeMatiere="GIL18">14.98</Matiere>
    <Matiere codeMatiere="GIL19">14.98</Matiere>
  </Note>
  <Note>
    <CNE>19000017</CNE>
    <LastName>GIL1_FN7</LastName>
    <FirstName>GIL1_LN7</FirstName>
    <Matiere codeMatiere="GIL11">12</Matiere>
    <Matiere codeMatiere="GIL12">13</Matiere>
    <Matiere codeMatiere="GIL13">15</Matiere>
    <Matiere codeMatiere="GIL14">10</Matiere>
    <Matiere codeMatiere="GIL15">17</Matiere>
    <Matiere codeMatiere="GIL16">12</Matiere>
    <Matiere codeMatiere="GIL17">13.98</Matiere>
    <Matiere codeMatiere="GIL18">16</Matiere>
    <Matiere codeMatiere="GIL19">16</Matiere>
  </Note>
  <Note>
    <CNE>19000018</CNE>
    <LastName>GIL1_FN8</LastName>
    <FirstName>GIL1_LN8</FirstName>
    <Matiere codeMatiere="GIL11">12</Matiere>
    <Matiere codeMatiere="GIL12">12.65</Matiere>
    <Matiere codeMatiere="GIL13">11</Matiere>
    <Matiere codeMatiere="GIL14">12</Matiere>
    <Matiere codeMatiere="GIL15">14</Matiere>
    <Matiere codeMatiere="GIL16">14.63</Matiere>
    <Matiere codeMatiere="GIL17">15.87</Matiere>
    <Matiere codeMatiere="GIL18">15.92</Matiere>
    <Matiere codeMatiere="GIL19">11.98</Matiere>
  </Note>
  <Note>
    <CNE>19000019</CNE>
    <LastName>GIL1_FN9</LastName>
    <FirstName>GIL1_LN9</FirstName>
    <Matiere codeMatiere="GIL11">12</Matiere>
    <Matiere codeMatiere="GIL12">13</Matiere>
    <Matiere codeMatiere="GIL13">14</Matiere>
    <Matiere codeMatiere="GIL14">15</Matiere>
    <Matiere codeMatiere="GIL15">12</Matiere>
    <Matiere codeMatiere="GIL16">14.02</Matiere>
    <Matiere codeMatiere="GIL17">16.98</Matiere>
    <Matiere codeMatiere="GIL18">16.32</Matiere>
    <Matiere codeMatiere="GIL19">12</Matiere>
  </Note>
  <Note>
    <CNE>19000020</CNE>
    <LastName>GIL1_FN10</LastName>
    <FirstName>GIL1_LN10</FirstName>
    <Matiere codeMatiere="GIL11">12</Matiere>
    <Matiere codeMatiere="GIL12">12</Matiere>
    <Matiere codeMatiere="GIL13">12.98</Matiere>
    <Matiere codeMatiere="GIL14">12</Matiere>
    <Matiere codeMatiere="GIL15">15.98</Matiere>
    <Matiere codeMatiere="GIL16">17.68</Matiere>
    <Matiere codeMatiere="GIL17">14.09</Matiere>
    <Matiere codeMatiere="GIL18">11.98</Matiere>
    <Matiere codeMatiere="GIL19">12</Matiere>
  </Note>
</Notes>

=== amamatou/GestionScolarite-XML/Fichiers_xml/Notes_GSEA1_Apres.xml
<?xml version="1.0"?>
<!DOCTYPE Notes SYSTEM "C://xampp/htdocs/GestionScolarite-XML/Validation_xml//notes.dtd">
<Notes>
  <Note>
    <CNE>19000021</CNE>
    <LastName>Gsea1_LN1</LastName>
    <FirstName>Gsea1_FN1</FirstName>
    <Matiere codeMatiere="GSEA11">12</Matiere>
    <Matiere codeMatiere="GSEA12">10</Matiere>
    <Matiere codeMatiere="GSEA13">14</Matiere>
    <Matiere codeMatiere="GSEA14">18</Matiere>
    <Matiere codeMatiere="GSEA15">20</Matiere>
    <Matiere codeMatiere="GSEA16">13</Matiere>
    <Matiere codeMatiere="GSEA21">16</Matiere>
    <Matiere codeMatiere="GSEA22">19</Matiere>
    <Matiere codeMatiere="GSEA23">12</Matiere>
    <Matiere codeMatiere="GSEA24">18</Matiere>
    <Matiere codeMatiere="GSEA25">9</Matiere>
    <Matiere codeMatiere="GSEA26">12</Matiere>
  </Note>
  <Note>
    <CNE>19000022</CNE>
    <LastName>Gsea1_LN2</LastName>
    <FirstName>Gsea1_FN2</FirstName>
    <Matiere codeMatiere="GSEA11">15</Matiere>
    <Matiere codeMatiere="GSEA12">12</Matiere>
    <Matiere codeMatiere="GSEA13">12</Matiere>
    <Matiere codeMatiere="GSEA14">18</Matiere>
    <Matiere codeMatiere="GSEA15">13</Matiere>
    <Matiere codeMatiere="GSEA16">12</Matiere>
    <Matiere codeMatiere="GSEA21">12</Matiere>
    <Matiere codeMatiere="GSEA22">18</Matiere>
    <Matiere codeMatiere="GSEA23">12</Matiere>
    <Matiere codeMatiere="GSEA24">17</Matiere>
    <Matiere codeMatiere="GSEA25">17</Matiere>
    <Matiere codeMatiere="GSEA26">12</Matiere>
  </Note>
  <Note>
    <CNE>19000023</CNE>
    <LastName>Gsea1_LN3</LastName>
    <FirstName>Gsea1_FN3</FirstName>
    <Matiere codeMatiere="GSEA11">12</Matiere>
    <Matiere codeMatiere="GSEA12">14</Matiere>
    <Matiere codeMatiere="GSEA13">12</Matiere>
    <Matiere codeMatiere="GSEA14">20</Matiere>
    <Matiere codeMatiere="GSEA15">12</Matiere>
    <Matiere codeMatiere="GSEA16">18</Matiere>
    <Matiere codeMatiere="GSEA21">20</Matiere>
    <Matiere codeMatiere="GSEA22">18</Matiere>
    <Matiere codeMatiere="GSEA23">14</Matiere>
    <Matiere codeMatiere="GSEA24">12</Matiere>
    <Matiere codeMatiere="GSEA25">15</Matiere>
    <Matiere codeMatiere="GSEA26">10</Matiere>
  </Note>
  <Note>
    <CNE>19000024</CNE>
    <LastName>Gsea1_LN4</LastName>
    <FirstName>Gsea1_FN4</FirstName>
    <Matiere codeMatiere="GSEA11">12</Matiere>
    <Matiere codeMatiere="GSEA12">12</Matiere>
    <Matiere codeMatiere="GSEA13">12</Matiere>
    <Matiere codeMatiere="GSEA14">16</Matiere>
    <Matiere codeMatiere="GSEA15">13</Matiere>
    <Matiere codeMatiere="GSEA16">13</Matiere>
    <Matiere codeMatiere="GSEA21">13</Matiere>
    <Matiere codeMatiere="GSEA22">14</Matiere>
    <Matiere codeMatiere="GSEA23">12</Matiere>
    <Matiere codeMatiere="GSEA24">20</Matiere>
    <Matiere codeMatiere="GSEA25">18</Matiere>
    <Matiere codeMatiere="GSEA26">18</Matiere>
  </Note>
  <Note>
    <CNE>19000025</CNE>
    <LastName>Gsea1_LN5</LastName>
    <FirstName>Gsea1_FN5</FirstName>
    <Matiere codeMatiere="GSEA11">10</Matiere>
    <Matiere codeMatiere="GSEA12">9</Matiere>
    <Matiere codeMatiere="GSEA13">20</Matiere>
    <Matiere codeMatiere="GSEA14">18</Matiere>
    <Matiere codeMatiere="GSEA15">13</Matiere>
    <Matiere codeMatiere="GSEA16">12</Matiere>
    <Matiere codeMatiere="GSEA21">20</Matiere>
    <Matiere codeMatiere="GSEA22">12</Matiere>
    <Matiere codeMatiere="GSEA23">18</Matiere>
    <Matiere codeMatiere="GSEA24">12</Matiere>
    <Matiere codeMatiere="GSEA25">13</Matiere>
    <Matiere codeMatiere="GSEA26">16</Matiere>
  </Note>
  <Note>
    <CNE>19000026</CNE>
    <LastName>Gsea1_LN6</LastName>
    <FirstName>Gsea1_FN6</FirstName>
    <Matiere codeMatiere="GSEA11">19</Matiere>
    <Matiere codeMatiere="GSEA12">16</Matiere>
    <Matiere codeMatiere="GSEA13">12</Matiere>
    <Matiere codeMatiere="GSEA14">17</Matiere>
    <Matiere codeMatiere="GSEA15">13</Matiere>
    <Matiere codeMatiere="GSEA16">14</Matiere>
    <Matiere codeMatiere="GSEA21">12</Matiere>
    <Matiere codeMatiere="GSEA22">19</Matiere>
    <Matiere codeMatiere="GSEA23">14</Matiere>
    <Matiere codeMatiere="GSEA24">12</Matiere>
    <Matiere codeMatiere="GSEA25">18</Matiere>
    <Matiere codeMatiere="GSEA26">12</Matiere>
  </Note>
  <Note>
    <CNE>19000027</CNE>
    <LastName>Gsea1_LN7</LastName>
    <FirstName>Gsea1_FN7</FirstName>
    <Matiere codeMatiere="GSEA11">17</Matiere>
    <Matiere codeMatiere="GSEA12">20</Matiere>
    <Matiere codeMatiere="GSEA13">12</Matiere>
    <Matiere codeMatiere="GSEA14">12</Matiere>
    <Matiere codeMatiere="GSEA15">19</Matiere>
    <Matiere codeMatiere="GSEA16">16</Matiere>
    <Matiere codeMatiere="GSEA21">10</Matiere>
    <Matiere codeMatiere="GSEA22">15</Matiere>
    <Matiere codeMatiere="GSEA23">12</Matiere>
    <Matiere codeMatiere="GSEA24">12</Matiere>
    <Matiere codeMatiere="GSEA25">15</Matiere>
    <Matiere codeMatiere="GSEA26">12</Matiere>
  </Note>
  <Note>
    <CNE>19000028</CNE>
    <LastName>Gsea1_LN8</LastName>
    <FirstName>Gsea1_FN8</FirstName>
    <Matiere codeMatiere="GSEA11">12</Matiere>
    <Matiere codeMatiere="GSEA12">13</Matiere>
    <Matiere codeMatiere="GSEA13">18</Matiere>
    <Matiere codeMatiere="GSEA14">15</Matiere>
    <Matiere codeMatiere="GSEA15">13</Matiere>
    <Matiere codeMatiere="GSEA16">15</Matiere>
    <Matiere codeMatiere="GSEA21">19</Matiere>
    <Matiere codeMatiere="GSEA22">13</Matiere>
    <Matiere codeMatiere="GSEA23">11</Matiere>
    <Matiere codeMatiere="GSEA24">12</Matiere>
    <Matiere codeMatiere="GSEA25">15</Matiere>
    <Matiere codeMatiere="GSEA26">10</Matiere>
  </Note>
  <Note>
    <CNE>19000029</CNE>
    <LastName>Gsea1_LN9</LastName>
    <FirstName>Gsea1_FN9</FirstName>
    <Matiere codeMatiere="GSEA11">19</Matiere>
    <Matiere codeMatiere="GSEA12">16</Matiere>
    <Matiere codeMatiere="GSEA13">12</Matiere>
    <Matiere codeMatiere="GSEA14">14</Matiere>
    <Matiere codeMatiere="GSEA15">15</Matiere>
    <Matiere codeMatiere="GSEA16">14</Matiere>
    <Matiere codeMatiere="GSEA21">20</Matiere>
    <Matiere codeMatiere="GSEA22">14</Matiere>
    <Matiere codeMatiere="GSEA23">19</Matiere>
    <Matiere codeMatiere="GSEA24">12</Matiere>
    <Matiere codeMatiere="GSEA25">12</Matiere>
    <Matiere codeMatiere="GSEA26">17</Matiere>
  </Note>
  <Note>
    <CNE>19000030</CNE>
    <LastName>Gsea1_LN10</LastName>
    <FirstName>Gsea1_FN10</FirstName>
    <Matiere codeMatiere="GSEA11">10</Matiere>
    <Matiere codeMatiere="GSEA12">11</Matiere>
    <Matiere codeMatiere="GSEA13">20</Matiere>
    <Matiere codeMatiere="GSEA14">20</Matiere>
    <Matiere codeMatiere="GSEA15">18</Matiere>
    <Matiere codeMatiere="GSEA16">16</Matiere>
    <Matiere codeMatiere="GSEA21">12</Matiere>
    <Matiere codeMatiere="GSEA22">12</Matiere>
    <Matiere codeMatiere="GSEA23">12</Matiere>
    <Matiere codeMatiere="GSEA24">20</Matiere>
    <Matiere codeMatiere="GSEA25">8</Matiere>
    <Matiere codeMatiere="GSEA26">19</Matiere>
  </Note>
</Notes>
