=== amamatou/GestionScolarite-XML/Validation_xml/Notes.dtd
<!ELEMENT Notes (Note)*>
<!ELEMENT Note (CNE,FirstName,LastName,Matiere*)>
<!ELEMENT CNE (#PCDATA)>
<!ELEMENT FirstName (#PCDATA)>
<!ELEMENT LastName (#PCDATA)>
<!ELEMENT Matiere (#PCDATA)>
<!ATTLIST Matiere codeMatiere CDATA #REQUIRED>

=== amamatou/GestionScolarite-XML/Fichiers_xml/Notes_AP1_Apres.xml
<?xml version="1.0"?>
<!DOCTYPE Notes SYSTEM "C://xampp/htdocs/GestionScolarite-XML/Validation_xml//notes.dtd">
<Notes>
  <Note>
    <CNE>21000001</CNE>
    <LastName>AP1_LN1</LastName>
    <FirstName>AP1_FN1</FirstName>
    <Matiere codeMatiere="AP11">12.34</Matiere>
    <Matiere codeMatiere="AP12">10.73</Matiere>
    <Matiere codeMatiere="AP13">15.33</Matiere>
    <Matiere codeMatiere="AP14">18.7</Matiere>
    <Matiere codeMatiere="AP15">12.76</Matiere>
    <Matiere codeMatiere="AP16">14.5</Matiere>
    <Matiere codeMatiere="AP17">13.44</Matiere>
    <Matiere codeMatiere="AP18">12.23</Matiere>
    <Matiere codeMatiere="AP19">13</Matiere>
  </Note>
  <Note>
    <CNE>21000002</CNE>
    <LastName>AP1_LN2</LastName>
    <FirstName>AP1_FN2</FirstName>
    <Matiere codeMatiere="AP11">10</Matiere>
    <Matiere codeMatiere="AP12">9.5</Matiere>
    <Matiere codeMatiere="AP13">9.87</Matiere>
    <Matiere codeMatiere="AP14">10</Matiere>
    <Matiere codeMatiere="AP15">11.63</Matiere>
    <Matiere codeMatiere="AP16">15.35</Matiere>
    <Matiere codeMatiere="AP17">18.88</Matiere>
    <Matiere codeMatiere="AP18">10</Matiere>
    <Matiere codeMatiere="AP19">10</Matiere>
  </Note>
  <Note>
    <CNE>21000003</CNE>
    <LastName>AP1_LN3</LastName>
    <FirstName>AP1_FN3</FirstName>
    <Matiere codeMatiere="AP11">13.06</Matiere>
    <Matiere codeMatiere="AP12">12.38</Matiere>
    <Matiere codeMatiere="AP13">15</Matiere>
    <Matiere codeMatiere="AP14">14.67</Matiere>
    <Matiere codeMatiere="AP15">17.87</Matiere>
    <Matiere codeMatiere="AP16">9.98</Matiere>
    <Matiere codeMatiere="AP17">10</Matiere>
    <Matiere codeMatiere="AP18">10</Matiere>
    <Matiere codeMatiere="AP19">15.7</Matiere>
  </Note>
  <Note>
    <CNE>21000004</CNE>
    <LastName>AP1_LN4</LastName>
    <FirstName>AP1_FN4</FirstName>
    <Matiere codeMatiere="AP11">18.62</Matiere>
    <Matiere codeMatiere="AP12">15.67</Matiere>
    <Matiere codeMatiere="AP13">18.79</Matiere>
    <Matiere codeMatiere="AP14">18.69</Matiere>
    <Matiere codeMatiere="AP15">15.88</Matiere>
    <Matiere codeMatiere="AP16">8.96</Matiere>
    <Matiere codeMatiere="AP17">10.66</Matiere>
    <Matiere codeMatiere="AP18">10</Matiere>
    <Matiere codeMatiere="AP19">17.04</Matiere>
  </Note>
  <Note>
    <CNE>21000005</CNE>
    <LastName>AP1_LN5</LastName>
    <FirstName>AP1_FN5</FirstName>
    <Matiere codeMatiere="AP11">14.54</Matiere>
    <Matiere codeMatiere="AP12">12.97</Matiere>
    <Matiere codeMatiere="AP13">10.97</Matiere>
    <Matiere codeMatiere="AP14">13.81</Matiere>
    <Matiere codeMatiere="AP15">10</Matiere>
    <Matiere codeMatiere="AP16">17.91</Matiere>
    <Matiere codeMatiere="AP17">14.69</Matiere>
    <Matiere codeMatiere="AP18">12.15</Matiere>
    <Matiere codeMatiere="AP19">15.92</Matiere>
  </Note>
  <Note>
    <CNE>21000006</CNE>
    <LastName>AP1_LN6</LastName>
    <FirstName>AP1_FN6</FirstName>
    <Matiere codeMatiere="AP11">10</Matiere>
    <Matiere codeMatiere="AP12">13.8</Matiere>
    <Matiere codeMatiere="AP13">10</Matiere>
    <Matiere codeMatiere="AP14">10</Matiere>
    <Matiere codeMatiere="AP15">11.23</Matiere>
    <Matiere codeMatiere="AP16">11.67</Matiere>
    <Matiere codeMatiere="AP17">10</Matiere>
    <Matiere codeMatiere="AP18">10</Matiere>
    <Matiere codeMatiere="AP19">8</Matiere>
  </Note>
  <Note>
    <CNE>21000007</CNE>
    <LastName>AP1_LN7</LastName>
    <FirstName>AP1_FN7</FirstName>
    <Matiere codeMatiere="AP11">16.17</Matiere>
    <Matiere codeMatiere="AP12">18.94</Matiere>
    <Matiere codeMatiere="AP13">18.05</Matiere>
    <Matiere codeMatiere="AP14">12.67</Matiere>
    <Matiere codeMatiere="AP15">14.25</Matiere>
    <Matiere codeMatiere="AP16">10</Matiere>
    <Matiere codeMatiere="AP17">19.18</Matiere>
    <Matiere codeMatiere="AP18">10.45</Matiere>
    <Matiere codeMatiere="AP19">6.98</Matiere>
  </Note>
  <Note>
    <CNE>21000008</CNE>
    <LastName>AP1_LN8</LastName>
    <FirstName>AP1_FN8</FirstName>
    <Matiere codeMatiere="AP11">14.55</Matiere>
    <Matiere codeMatiere="AP12">14.89</Matiere>
    <Matiere codeMatiere="AP13">10</Matiere>
    <Matiere codeMatiere="AP14">14.45</Matiere>
    <Matiere codeMatiere="AP15">10</Matiere>
    <Matiere codeMatiere="AP16">12.75</Matiere>
    <Matiere codeMatiere="AP17">15.01</Matiere>
    <Matiere codeMatiere="AP18">10.38</Matiere>
    <Matiere codeMatiere="AP19">16.5</Matiere>
  </Note>
  <Note>
    <CNE>21000009</CNE>
    <LastName>AP1_LN9</LastName>
    <FirstName>AP1_FN9</FirstName>
    <Matiere codeMatiere="AP11">10</Matiere>
    <Matiere codeMatiere="AP12">11.71</Matiere>
    <Matiere codeMatiere="AP13">11.57</Matiere>
    <Matiere codeMatiere="AP14">10.59</Matiere>
    <Matiere codeMatiere="AP15">10.65</Matiere>
    <Matiere codeMatiere="AP16">10</Matiere>
    <Matiere codeMatiere="AP17">13.3</Matiere>
    <Matiere codeMatiere="AP18">17.75</Matiere>
    <Matiere codeMatiere="AP19">13.09</Matiere>
  </Note>
  <Note>
    <CNE>21000010</CNE>
    <LastName>AP1_LN10</LastName>
    <FirstName>AP1_FN10</FirstName>
    <Matiere codeMatiere="AP11">10</Matiere>
    <Matiere codeMatiere="AP12">10</Matiere>
    <Matiere codeMatiere="AP13">10</Matiere>
    <Matiere codeMatiere="AP14">13.16</Matiere>
    <Matiere codeMatiere="AP15">19</Matiere>
    <Matiere codeMatiere="AP16">10</Matiere>
    <Matiere codeMatiere="AP17">15.74</Matiere>
    <Matiere codeMatiere="AP18">18.97</Matiere>
    <Matiere codeMatiere="AP19">17.74</Matiere>
  </Note>
</Notes>

=== amamatou/GestionScolarite-XML/Fichiers_xml/Notes_G3EI1_Apres.xml
<?xml version="1.0"?>
<!DOCTYPE Notes SYSTEM "C://xampp/htdocs/GestionScolarite-XML/Validation_xml//notes.dtd">
<Notes>
  <Note>
    <CNE>19000041</CNE>
    <LastName>G3EI1_LN1</LastName>
    <FirstName>G3EI1_FN1</FirstName>
    <Matiere codeMatiere="G3EI111">11</Matiere>
    <Matiere codeMatiere="G3EI112">14</Matiere>
    <Matiere codeMatiere="G3EI113">19.32</Matiere>
    <Matiere codeMatiere="G3EI114">11.68</Matiere>
    <Matiere codeMatiere="G3EI115">10.73</Matiere>
    <Matiere codeMatiere="G3EI116">15.06</Matiere>
    <Matiere codeMatiere="G3EI121">17.56</Matiere>
    <Matiere codeMatiere="G3EI122">10</Matiere>
    <Matiere codeMatiere="G3EI123">13.84</Matiere>
  </Note>
  <Note>
    <CNE>19000042</CNE>
    <LastName>G3EI1_LN2</LastName>
    <FirstName>G3EI1_FN2</FirstName>
    <Matiere codeMatiere="G3EI111">16.5</Matiere>
    <Matiere codeMatiere="G3EI112">17</Matiere>
    <Matiere codeMatiere="G3EI113">19.65</Matiere>
    <Matiere codeMatiere="G3EI114">10</Matiere>
    <Matiere codeMatiere="G3EI115">18.7</Matiere>
    <Matiere codeMatiere="G3EI116">15.13</Matiere>
    <Matiere codeMatiere="G3EI121">10.99</Matiere>
    <Matiere codeMatiere="G3EI122">12.11</Matiere>
    <Matiere codeMatiere="G3EI123">9.96</Matiere>
  </Note>
  <Note>
    <CNE>19000043</CNE>
    <LastName>G3EI1_LN3</LastName>
    <FirstName>G3EI1_FN3</FirstName>
    <Matiere codeMatiere="G3EI111">18.65</Matiere>
    <Matiere codeMatiere="G3EI112">12</Matiere>
    <Matiere codeMatiere="G3EI113">12.39</Matiere>
    <Matiere codeMatiere="G3EI114">10.52</Matiere>
    <Matiere codeMatiere="G3EI115">12.26</Matiere>
    <Matiere codeMatiere="G3EI116">15.77</Matiere>
    <Matiere codeMatiere="G3EI121">19.45</Matiere>
    <Matiere codeMatiere="G3EI122">18.89</Matiere>
    <Matiere codeMatiere="G3EI123">10</Matiere>
  </Note>
  <Note>
    <CNE>19000044</CNE>
    <LastName>G3EI1_LN4</LastName>
    <FirstName>G3EI1_FN4</FirstName>
    <Matiere codeMatiere="G3EI111">10</Matiere>
    <Matiere codeMatiere="G3EI112">18</Matiere>
    <Matiere codeMatiere="G3EI113">13.09</Matiere>
    <Matiere codeMatiere="G3EI114">17.56</Matiere>
    <Matiere codeMatiere="G3EI115">11.26</Matiere>
    <Matiere codeMatiere="G3EI116">16.26</Matiere>
    <Matiere codeMatiere="G3EI121">12.91</Matiere>
    <Matiere codeMatiere="G3EI122">14.16</Matiere>
    <Matiere codeMatiere="G3EI123">13.34</Matiere>
  </Note>
  <Note>
    <CNE>19000045</CNE>
    <LastName>G3EI1_LN5</LastName>
    <FirstName>G3EI1_FN5</FirstName>
    <Matiere codeMatiere="G3EI111">13.89</Matiere>
    <Matiere codeMatiere="G3EI112">10</Matiere>
    <Matiere codeMatiere="G3EI113">17.88</Matiere>
    <Matiere codeMatiere="G3EI114">17.66</Matiere>
    <Matiere codeMatiere="G3EI115">10.67</Matiere>
    <Matiere codeMatiere="G3EI116">16.66</Matiere>
    <Matiere codeMatiere="G3EI121">18.24</Matiere>
    <Matiere codeMatiere="G3EI122">17.93</Matiere>
    <Matiere codeMatiere="G3EI123">15.91</Matiere>
  </Note>
  <Note>
    <CNE>19000046</CNE>
    <LastName>G3EI1_LN6</LastName>
    <FirstName>G3EI1_FN6</FirstName>
    <Matiere codeMatiere="G3EI111">10</Matiere>
    <Matiere codeMatiere="G3EI112">16</Matiere>
    <Matiere codeMatiere="G3EI113">9.87</Matiere>
    <Matiere codeMatiere="G3EI114">14.74</Matiere>
    <Matiere codeMatiere="G3EI115">10</Matiere>
    <Matiere codeMatiere="G3EI116">11.85</Matiere>
    <Matiere codeMatiere="G3EI121">12.21</Matiere>
    <Matiere codeMatiere="G3EI122">16.71</Matiere>
    <Matiere codeMatiere="G3EI123">11.29</Matiere>
  </Note>
  <Note>
    <CNE>19000047</CNE>
    <LastName>G3EI1_LN7</LastName>
    <FirstName>G3EI1_FN7</FirstName>
    <Matiere codeMatiere="G3EI111">10</Matiere>
    <Matiere codeMatiere="G3EI112">10</Matiere>
    <Matiere codeMatiere="G3EI113">13.82</Matiere>
    <Matiere codeMatiere="G3EI114">12.86</Matiere>
    <Matiere codeMatiere="G3EI115">12.72</Matiere>
    <Matiere codeMatiere="G3EI116">14.11</Matiere>
    <Matiere codeMatiere="G3EI121">13.87</Matiere>
    <Matiere codeMatiere="G3EI122">12.78</Matiere>
    <Matiere codeMatiere="G3EI123">13.17</Matiere>
  </Note>
  <Note>
    <CNE>19000048</CNE>
    <LastName>G3EI1_LN8</LastName>
    <FirstName>G3EI1_FN8</FirstName>
    <Matiere codeMatiere="G3EI111">12</Matiere>
    <Matiere codeMatiere="G3EI112">8.98</Matiere>
    <Matiere codeMatiere="G3EI113">12</Matiere>
    <Matiere codeMatiere="G3EI114">16.51</Matiere>
    <Matiere codeMatiere="G3EI115">18.84</Matiere>
    <Matiere codeMatiere="G3EI116">13.45</Matiere>
    <Matiere codeMatiere="G3EI121">16.75</Matiere>
    <Matiere codeMatiere="G3EI122">12.07</Matiere>
    <Matiere codeMatiere="G3EI123">14.63</Matiere>
  </Note>
  <Note>
    <CNE>19000049</CNE>
    <LastName>G3EI1_LN9</LastName>
    <FirstName>G3EI1_FN9</FirstName>
    <Matiere codeMatiere="G3EI111">12</Matiere>
    <Matiere codeMatiere="G3EI112">13</Matiere>
    <Matiere codeMatiere="G3EI113">15.78</Matiere>
    <Matiere codeMatiere="G3EI114">17.15</Matiere>
    <Matiere codeMatiere="G3EI115">10.95</Matiere>
    <Matiere codeMatiere="G3EI116">17.83</Matiere>
    <Matiere codeMatiere="G3EI121">14.99</Matiere>
    <Matiere codeMatiere="G3EI122">12.65</Matiere>
    <Matiere codeMatiere="G3EI123">14.02</Matiere>
  </Note>
  <Note>
    <CNE>19000050</CNE>
    <LastName>G3EI1_LN10</LastName>
    <FirstName>G3EI1_FN10</FirstName>
    <Matiere codeMatiere="G3EI111">12</Matiere>
    <Matiere codeMatiere="G3EI112">12</Matiere>
    <Matiere codeMatiere="G3EI113">18.55</Matiere>
    <Matiere codeMatiere="G3EI114">11.85</Matiere>
    <Matiere codeMatiere="G3EI115">11.39</Matiere>
    <Matiere codeMatiere="G3EI116">10</Matiere>
    <Matiere codeMatiere="G3EI121">10.82</Matiere>
    <Matiere codeMatiere="G3EI122">10</Matiere>
    <Matiere codeMatiere="G3EI123">17.68</Matiere>
  </Note>
</Notes>

=== amamatou/GestionScolarite-XML/Fichiers_xml/Notes_GINF3_Apres.xml
<?xml version="1.0"?>
<!DOCTYPE Notes SYSTEM "C://xampp/htdocs/GestionScolarite-XML/Validation_xml//notes.dtd">
<Notes>
  <Note>
    <CNE>17000031</CNE>
    <LastName>Ginf3_LN1</LastName>
    <FirstName>Ginf3_FN1</FirstName>
    <Matiere codeMatiere="GINF51">10</Matiere>
    <Matiere codeMatiere="GINF52">12</Matiere>
    <Matiere codeMatiere="GINF53">12</Matiere>
    <Matiere codeMatiere="GINF54">14</Matiere>
    <Matiere codeMatiere="GINF55">12</Matiere>
    <Matiere codeMatiere="GINF56">13</Matiere>
  </Note>
  <Note>
    <CNE>17000032</CNE>
    <LastName>Ginf3_LN2</LastName>
    <FirstName>Ginf3_FN2</FirstName>
    <Matiere codeMatiere="GINF51">20</Matiere>
    <Matiere codeMatiere="GINF52">17</Matiere>
    <Matiere codeMatiere="GINF53">20</Matiere>
    <Matiere codeMatiere="GINF54">20</Matiere>
    <Matiere codeMatiere="GINF55">17</Matiere>
    <Matiere codeMatiere="GINF56">12</Matiere>
  </Note>
  <Note>
    <CNE>17000033</CNE>
    <LastName>Ginf3_LN3</LastName>
    <FirstName>Ginf3_FN3</FirstName>
    <Matiere codeMatiere="GINF51">12</Matiere>
    <Matiere codeMatiere="GINF52">13</Matiere>
    <Matiere codeMatiere="GINF53">16</Matiere>
    <Matiere codeMatiere="GINF54">14</Matiere>
    <Matiere codeMatiere="GINF55">11</Matiere>
    <Matiere codeMatiere="GINF56">15</Matiere>
  </Note>
  <Note>
    <CNE>17000034</CNE>
    <LastName>Ginf3_LN4</LastName>
    <FirstName>Ginf3_FN4</FirstName>
    <Matiere codeMatiere="GINF51">12</Matiere>
    <Matiere codeMatiere="GINF52">10</Matiere>
    <Matiere codeMatiere="GINF53">14</Matiere>
    <Matiere codeMatiere="GINF54">13</Matiere>
    <Matiere codeMatiere="GINF55">12</Matiere>
    <Matiere codeMatiere="GINF56">16</Matiere>
  </Note>
  <Note>
    <CNE>17000035</CNE>
    <LastName>Ginf3_LN5</LastName>
    <FirstName>Ginf3_FN5</FirstName>
    <Matiere codeMatiere="GINF51">12</Matiere>
    <Matiere codeMatiere="GINF52">9</Matiere>
    <Matiere codeMatiere="GINF53">12</Matiere>
    <Matiere codeMatiere="GINF54">12</Matiere>
    <Matiere codeMatiere="GINF55">12</Matiere>
    <Matiere codeMatiere="GINF56">17</Matiere>
  </Note>
  <Note>
    <CNE>17000036</CNE>
    <LastName>Ginf3_LN6</LastName>
    <FirstName>Ginf3_FN6</FirstName>
    <Matiere codeMatiere="GINF51">16</Matiere>
    <Matiere codeMatiere="GINF52">20</Matiere>
    <Matiere codeMatiere="GINF53">20</Matiere>
    <Matiere codeMatiere="GINF54">16</Matiere>
    <Matiere codeMatiere="GINF55">16</Matiere>
    <Matiere codeMatiere="GINF56">13</Matiere>
  </Note>
  <Note>
    <CNE>17000037</CNE>
    <LastName>Ginf3_LN7</LastName>
    <FirstName>Ginf3_FN7</FirstName>
    <Matiere codeMatiere="GINF51">12</Matiere>
    <Matiere codeMatiere="GINF52">13</Matiere>
    <Matiere codeMatiere="GINF53">12</Matiere>
    <Matiere codeMatiere="GINF54">20</Matiere>
    <Matiere codeMatiere="GINF55">12</Matiere>
    <Matiere codeMatiere="GINF56">10</Matiere>
  </Note>
  <Note>
    <CNE>17000038</CNE>
    <LastName>Ginf3_LN8</LastName>
    <FirstName>Ginf3_FN8</FirstName>
    <Matiere codeMatiere="GINF51">14</Matiere>
    <Matiere codeMatiere="GINF52">12</Matiere>
    <Matiere codeMatiere="GINF53">15</Matiere>
    <Matiere codeMatiere="GINF54">19</Matiere>
    <Matiere codeMatiere="GINF55">12</Matiere>
    <Matiere codeMatiere="GINF56">16</Matiere>
  </Note>
  <Note>
    <CNE>17000039</CNE>
    <LastName>Ginf3_LN9</LastName>
    <FirstName>Ginf3_FN9</FirstName>
    <Matiere codeMatiere="GINF51">12</Matiere>
    <Matiere codeMatiere="GINF52">20</Matiere>
    <Matiere codeMatiere="GINF53">16</Matiere>
    <Matiere codeMatiere="GINF54">18</Matiere>
    <Matiere codeMatiere="GINF55">19</Matiere>
    <Matiere codeMatiere="GINF56">16</Matiere>
  </Note>
  <Note>
    <CNE>17000040</CNE>
    <LastName>Ginf3_LN10</LastName>
    <FirstName>Ginf3_FN10</FirstName>
    <Matiere codeMatiere="GINF51">15</Matiere>
    <Matiere codeMatiere="GINF52">13</Matiere>
    <Matiere codeMatiere="GINF53">18</Matiere>
    <Matiere codeMatiere="GINF54">18</Matiere>
    <Matiere codeMatiere="GINF55">17</Matiere>
    <Matiere codeMatiere="GINF56">15</Matiere>
  </Note>
</Notes>
