=== amamatou/GestionScolarite-XML/Validation_xml/Notes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
elementFormDefault="qualified">

  <xs:element name="Notes">
   <xs:complexType>
     <xs:sequence>
      <xs:element name="Note">
       <xs:complexType>
        <xs:sequence>
          <xs:element name="CNE" type="xs:string"/>
          <xs:element name="FirstName" type="xs:string"/>
          <xs:element name="LastName" type="xs:string"/>
          <xs:element name="Matiere" maxOccurs="12" minOccurs="6">
            <xs:complexType>
              <xs:attribute name="codeMatiere" type="xs:string" use="required" />
              <xs:restriction base="xs:float">
                <xs:minInclusive value="0"/>
                <xs:maxInclusive value="20"/>
              </xs:restriction>
            </xs:complexType>  
          </xs:element>
        </xs:sequence>
        </xs:complexType>
    </xs:element>
   </xs:sequence>
  </xs:complexType> 
  </xs:element>
  </xs:schema>

=== amamatou/GestionScolarite-XML/Fichiers_xml/Notes_GSTR2_ApresRat.xml
<?xml version="1.0"?>
<Notes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C://xampp/htdocs/GestionScolarite-XML/Validation_xml/Notes.xsd">
  <Note>
    <CNE>18000001</CNE>
    <LastName>Gstr2_LN1</LastName>
    <FirstName>Gstr2_FN1</FirstName>
    <Matiere codeMatiere="GSTR31">10</Matiere>
    <Matiere codeMatiere="GSTR32">12</Matiere>
    <Matiere codeMatiere="GSTR33">15</Matiere>
    <Matiere codeMatiere="GSTR34">12</Matiere>
    <Matiere codeMatiere="GSTR35">12</Matiere>
    <Matiere codeMatiere="GSTR36">19</Matiere>
    <Matiere codeMatiere="GSTR41">17</Matiere>
    <Matiere codeMatiere="GSTR42">12</Matiere>
    <Matiere codeMatiere="GSTR43">12</Matiere>
    <Matiere codeMatiere="GSTR44">12</Matiere>
    <Matiere codeMatiere="GSTR45">12</Matiere>
    <Matiere codeMatiere="GSTR46">12</Matiere>
  </Note>
  <Note>
    <CNE>18000002</CNE>
    <LastName>Gstr2_LN2</LastName>
    <FirstName>Gstr2_FN2</FirstName>
    <Matiere codeMatiere="GSTR31">12</Matiere>
    <Matiere codeMatiere="GSTR32">10</Matiere>
    <Matiere codeMatiere="GSTR33">14</Matiere>
    <Matiere codeMatiere="GSTR34">13</Matiere>
    <Matiere codeMatiere="GSTR35">19</Matiere>
    <Matiere codeMatiere="GSTR36">15</Matiere>
    <Matiere codeMatiere="GSTR41">8</Matiere>
    <Matiere codeMatiere="GSTR42">16</Matiere>
    <Matiere codeMatiere="GSTR43">12</Matiere>
    <Matiere codeMatiere="GSTR44">13</Matiere>
    <Matiere codeMatiere="GSTR45">15</Matiere>
    <Matiere codeMatiere="GSTR46">12</Matiere>
  </Note>
  <Note>
    <CNE>18000003</CNE>
    <LastName>Gstr2_LN3</LastName>
    <FirstName>Gstr2_FN3</FirstName>
    <Matiere codeMatiere="GSTR31">12</Matiere>
    <Matiere codeMatiere="GSTR32">19</Matiere>
    <Matiere codeMatiere="GSTR33">19</Matiere>
    <Matiere codeMatiere="GSTR34">9</Matiere>
    <Matiere codeMatiere="GSTR35">18</Matiere>
    <Matiere codeMatiere="GSTR36">10</Matiere>
    <Matiere codeMatiere="GSTR41">18</Matiere>
    <Matiere codeMatiere="GSTR42">13</Matiere>
    <Matiere codeMatiere="GSTR43">13</Matiere>
    <Matiere codeMatiere="GSTR44">19</Matiere>
    <Matiere codeMatiere="GSTR45">16</Matiere>
    <Matiere codeMatiere="GSTR46">13</Matiere>
  </Note>
  <Note>
    <CNE>18000004</CNE>
    <LastName>Gstr2_LN4</LastName>
    <FirstName>Gstr2_FN4</FirstName>
    <Matiere codeMatiere="GSTR31">11</Matiere>
    <Matiere codeMatiere="GSTR32">15</Matiere>
    <Matiere codeMatiere="GSTR33">17</Matiere>
    <Matiere codeMatiere="GSTR34">16</Matiere>
    <Matiere codeMatiere="GSTR35">17</Matiere>
    <Matiere codeMatiere="GSTR36">19</Matiere>
    <Matiere codeMatiere="GSTR41">10</Matiere>
    <Matiere codeMatiere="GSTR42">16</Matiere>
    <Matiere codeMatiere="GSTR43">17</Matiere>
    <Matiere codeMatiere="GSTR44">16</Matiere>
    <Matiere codeMatiere="GSTR45">10</Matiere>
    <Matiere codeMatiere="GSTR46">12</Matiere>
  </Note>
  <Note>
    <CNE>18000005</CNE>
    <LastName>Gstr2_LN5</LastName>
    <FirstName>Gstr2_FN5</FirstName>
    <Matiere codeMatiere="GSTR31">19</Matiere>
    <Matiere codeMatiere="GSTR32">12</Matiere>
    <Matiere codeMatiere="GSTR33">12</Matiere>
    <Matiere codeMatiere="GSTR34">20</Matiere>
    <Matiere codeMatiere="GSTR35">20</Matiere>
    <Matiere codeMatiere="GSTR36">13</Matiere>
    <Matiere codeMatiere="GSTR41">11</Matiere>
    <Matiere codeMatiere="GSTR42">12</Matiere>
    <Matiere codeMatiere="GSTR43">10</Matiere>
    <Matiere codeMatiere="GSTR44">19</Matiere>
    <Matiere codeMatiere="GSTR45">18</Matiere>
    <Matiere codeMatiere="GSTR46">10</Matiere>
  </Note>
  <Note>
    <CNE>18000006</CNE>
    <LastName>Gstr2_LN6</LastName>
    <FirstName>Gstr2_FN6</FirstName>
    <Matiere codeMatiere="GSTR31">12</Matiere>
    <Matiere codeMatiere="GSTR32">16</Matiere>
    <Matiere codeMatiere="GSTR33">19</Matiere>
    <Matiere codeMatiere="GSTR34">12</Matiere>
    <Matiere codeMatiere="GSTR35">15</Matiere>
    <Matiere codeMatiere="GSTR36">12</Matiere>
    <Matiere codeMatiere="GSTR41">12</Matiere>
    <Matiere codeMatiere="GSTR42">10</Matiere>
    <Matiere codeMatiere="GSTR43">16</Matiere>
    <Matiere codeMatiere="GSTR44">13</Matiere>
    <Matiere codeMatiere="GSTR45">19</Matiere>
    <Matiere codeMatiere="GSTR46">18</Matiere>
  </Note>
  <Note>
    <CNE>18000007</CNE>
    <LastName>Gstr2_LN7</LastName>
    <FirstName>Gstr2_FN7</FirstName>
    <Matiere codeMatiere="GSTR31">12</Matiere>
    <Matiere codeMatiere="GSTR32">12</Matiere>
    <Matiere codeMatiere="GSTR33">10</Matiere>
    <Matiere codeMatiere="GSTR34">9</Matiere>
    <Matiere codeMatiere="GSTR35">17</Matiere>
    <Matiere codeMatiere="GSTR36">12</Matiere>
    <Matiere codeMatiere="GSTR41">18</Matiere>
    <Matiere codeMatiere="GSTR42">12</Matiere>
    <Matiere codeMatiere="GSTR43">12</Matiere>
    <Matiere codeMatiere="GSTR44">15</Matiere>
    <Matiere codeMatiere="GSTR45">12</Matiere>
    <Matiere codeMatiere="GSTR46">11</Matiere>
  </Note>
  <Note>
    <CNE>18000008</CNE>
    <LastName>Gstr2_LN8</LastName>
    <FirstName>Gstr2_FN8</FirstName>
    <Matiere codeMatiere="GSTR31">8</Matiere>
    <Matiere codeMatiere="GSTR32">15</Matiere>
    <Matiere codeMatiere="GSTR33">12</Matiere>
    <Matiere codeMatiere="GSTR34">12</Matiere>
    <Matiere codeMatiere="GSTR35">18</Matiere>
    <Matiere codeMatiere="GSTR36">15</Matiere>
    <Matiere codeMatiere="GSTR41">9</Matiere>
    <Matiere codeMatiere="GSTR42">17</Matiere>
    <Matiere codeMatiere="GSTR43">16</Matiere>
    <Matiere codeMatiere="GSTR44">18</Matiere>
    <Matiere codeMatiere="GSTR45">12</Matiere>
    <Matiere codeMatiere="GSTR46">17</Matiere>
  </Note>
  <Note>
    <CNE>18000009</CNE>
    <LastName>Gstr2_LN9</LastName>
    <FirstName>Gstr2_FN9</FirstName>
    <Matiere codeMatiere="GSTR31">15</Matiere>
    <Matiere codeMatiere="GSTR32">12</Matiere>
    <Matiere codeMatiere="GSTR33">16</Matiere>
    <Matiere codeMatiere="GSTR34">18</Matiere>
    <Matiere codeMatiere="GSTR35">19</Matiere>
    <Matiere codeMatiere="GSTR36">12</Matiere>
    <Matiere codeMatiere="GSTR41">10</Matiere>
    <Matiere codeMatiere="GSTR42">9</Matiere>
    <Matiere codeMatiere="GSTR43">12</Matiere>
    <Matiere codeMatiere="GSTR44">12</Matiere>
    <Matiere codeMatiere="GSTR45">17</Matiere>
    <Matiere codeMatiere="GSTR46">12</Matiere>
  </Note>
  <Note>
    <CNE>18000010</CNE>
    <LastName>Gstr2_LN10</LastName>
    <FirstName>Gstr2_FN10</FirstName>
    <Matiere codeMatiere="GSTR31">12</Matiere>
    <Matiere codeMatiere="GSTR32">14</Matiere>
    <Matiere codeMatiere="GSTR33">13</Matiere>
    <Matiere codeMatiere="GSTR34">12</Matiere>
    <Matiere codeMatiere="GSTR35">18</Matiere>
    <Matiere codeMatiere="GSTR36">19</Matiere>
    <Matiere codeMatiere="GSTR41">12</Matiere>
    <Matiere codeMatiere="GSTR42">10</Matiere>
    <Matiere codeMatiere="GSTR43">12</Matiere>
    <Matiere codeMatiere="GSTR44">16</Matiere>
    <Matiere codeMatiere="GSTR45">12</Matiere>
    <Matiere codeMatiere="GSTR46">17</Matiere>
  </Note>
</Notes>

=== amamatou/GestionScolarite-XML/Fichiers_xml/Notes_AP2_Avant.xml
<?xml version="1.0"?>
<Notes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C://xampp/htdocs/GestionScolarite-XML/Validation_xml/Notes.xsd">
  <Note>
    <CNE>20000001</CNE>
    <LastName>AP2_LN1</LastName>
    <FirstName>AP2_FN1</FirstName>
    <Matiere codeMatiere="AP31">10.2</Matiere>
    <Matiere codeMatiere="AP32">10.73</Matiere>
    <Matiere codeMatiere="AP33">15.06</Matiere>
    <Matiere codeMatiere="AP34">16.89</Matiere>
    <Matiere codeMatiere="AP35">9.09</Matiere>
    <Matiere codeMatiere="AP36">13.84</Matiere>
    <Matiere codeMatiere="AP41">19.32</Matiere>
    <Matiere codeMatiere="AP42">15.76</Matiere>
    <Matiere codeMatiere="AP43">11.44</Matiere>
  </Note>
  <Note>
    <CNE>20000002</CNE>
    <LastName>AP2_LN2</LastName>
    <FirstName>AP2_FN2</FirstName>
    <Matiere codeMatiere="AP31">9.46</Matiere>
    <Matiere codeMatiere="AP32">14.89</Matiere>
    <Matiere codeMatiere="AP33">12,89</Matiere>
    <Matiere codeMatiere="AP34">10.99</Matiere>
    <Matiere codeMatiere="AP35">12.11</Matiere>
    <Matiere codeMatiere="AP36">8.35</Matiere>
    <Matiere codeMatiere="AP41">16.35</Matiere>
    <Matiere codeMatiere="AP42">11.46</Matiere>
    <Matiere codeMatiere="AP43">18.64</Matiere>
  </Note>
  <Note>
    <CNE>20000003</CNE>
    <LastName>AP2_LN3</LastName>
    <FirstName>AP2_FN3</FirstName>
    <Matiere codeMatiere="AP31">10.52</Matiere>
    <Matiere codeMatiere="AP32">9.67</Matiere>
    <Matiere codeMatiere="AP33">15.77</Matiere>
    <Matiere codeMatiere="AP34">19.45</Matiere>
    <Matiere codeMatiere="AP35">14.98</Matiere>
    <Matiere codeMatiere="AP36">9.73</Matiere>
    <Matiere codeMatiere="AP41">12.39</Matiere>
    <Matiere codeMatiere="AP42">17.97</Matiere>
    <Matiere codeMatiere="AP43">10.98</Matiere>
  </Note>
  <Note>
    <CNE>20000004</CNE>
    <LastName>AP2_LN4</LastName>
    <FirstName>AP2_FN4</FirstName>
    <Matiere codeMatiere="AP31">15.57</Matiere>
    <Matiere codeMatiere="AP32">13.96</Matiere>
    <Matiere codeMatiere="AP33">16.26</Matiere>
    <Matiere codeMatiere="AP34">12.91</Matiere>
    <Matiere codeMatiere="AP35">14.16</Matiere>
    <Matiere codeMatiere="AP36">11.45</Matiere>
    <Matiere codeMatiere="AP41">13.09</Matiere>
    <Matiere codeMatiere="AP42">10</Matiere>
    <Matiere codeMatiere="AP43">17.3</Matiere>
  </Note>
  <Note>
    <CNE>20000005</CNE>
    <LastName>AP2_LN5</LastName>
    <FirstName>AP2_FN5</FirstName>
    <Matiere codeMatiere="AP31">17.66</Matiere>
    <Matiere codeMatiere="AP32">10.67</Matiere>
    <Matiere codeMatiere="AP33">13.67</Matiere>
    <Matiere codeMatiere="AP34">15.67</Matiere>
    <Matiere codeMatiere="AP35">17.93</Matiere>
    <Matiere codeMatiere="AP36">15.91</Matiere>
    <Matiere codeMatiere="AP41">10.78</Matiere>
    <Matiere codeMatiere="AP42">16.87</Matiere>
    <Matiere codeMatiere="AP43">12.89</Matiere>
  </Note>
  <Note>
    <CNE>20000006</CNE>
    <LastName>AP2_LN6</LastName>
    <FirstName>AP2_FN6</FirstName>
    <Matiere codeMatiere="AP31">12.65</Matiere>
    <Matiere codeMatiere="AP32">8.54</Matiere>
    <Matiere codeMatiere="AP33">11.85</Matiere>
    <Matiere codeMatiere="AP34">11</Matiere>
    <Matiere codeMatiere="AP35">16.71</Matiere>
    <Matiere codeMatiere="AP36">11.29</Matiere>
    <Matiere codeMatiere="AP41">8.66</Matiere>
    <Matiere codeMatiere="AP42">12.78</Matiere>
    <Matiere codeMatiere="AP43">16.22</Matiere>
  </Note>
  <Note>
    <CNE>20000007</CNE>
    <LastName>AP2_LN7</LastName>
    <FirstName>AP2_FN7</FirstName>
    <Matiere codeMatiere="AP31">11.45</Matiere>
    <Matiere codeMatiere="AP32">12.72</Matiere>
    <Matiere codeMatiere="AP33">14.11</Matiere>
    <Matiere codeMatiere="AP34">13.87</Matiere>
    <Matiere codeMatiere="AP35">10.56</Matiere>
    <Matiere codeMatiere="AP36">13.17</Matiere>
    <Matiere codeMatiere="AP41">13.82</Matiere>
    <Matiere codeMatiere="AP42">10.83</Matiere>
    <Matiere codeMatiere="AP43">13.67</Matiere>
  </Note>
  <Note>
    <CNE>20000008</CNE>
    <LastName>AP2_LN8</LastName>
    <FirstName>AP2_FN8</FirstName>
    <Matiere codeMatiere="AP31">14.69</Matiere>
    <Matiere codeMatiere="AP32">17.56</Matiere>
    <Matiere codeMatiere="AP33">12.78</Matiere>
    <Matiere codeMatiere="AP34">15.65</Matiere>
    <Matiere codeMatiere="AP35">12.07</Matiere>
    <Matiere codeMatiere="AP36">14.63</Matiere>
    <Matiere codeMatiere="AP41">10</Matiere>
    <Matiere codeMatiere="AP42">15.92</Matiere>
    <Matiere codeMatiere="AP43">15.32</Matiere>
  </Note>
  <Note>
    <CNE>20000009</CNE>
    <LastName>AP2_LN9</LastName>
    <FirstName>AP2_FN9</FirstName>
    <Matiere codeMatiere="AP31">17.15</Matiere>
    <Matiere codeMatiere="AP32">10.95</Matiere>
    <Matiere codeMatiere="AP33">17.83</Matiere>
    <Matiere codeMatiere="AP34">14.99</Matiere>
    <Matiere codeMatiere="AP35">13.47</Matiere>
    <Matiere codeMatiere="AP36">13.78</Matiere>
    <Matiere codeMatiere="AP41">15.78</Matiere>
    <Matiere codeMatiere="AP42">16.32</Matiere>
    <Matiere codeMatiere="AP43">14.56</Matiere>
  </Note>
  <Note>
    <CNE>20000010</CNE>
    <LastName>AP2_LN10</LastName>
    <FirstName>AP2_FN10</FirstName>
    <Matiere codeMatiere="AP31">11.85</Matiere>
    <Matiere codeMatiere="AP32">11.39</Matiere>
    <Matiere codeMatiere="AP33">9.67</Matiere>
    <Matiere codeMatiere="AP34">10.82</Matiere>
    <Matiere codeMatiere="AP35">8.78</Matiere>
    <Matiere codeMatiere="AP36">17.68</Matiere>
    <Matiere codeMatiere="AP41">18.55</Matiere>
    <Matiere codeMatiere="AP42">7.56</Matiere>
    <Matiere codeMatiere="AP43">13.89</Matiere>
  </Note>
</Notes>

=== amamatou/GestionScolarite-XML/Fichiers_xml/Notes_GINF1_ApresRat.xml
<?xml version="1.0"?>
<Notes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C://xampp/htdocs/GestionScolarite-XML/Validation_xml/Notes.xsd">
  <Note>
    <CNE>19000031</CNE>
    <LastName>Ginf1_FN1</LastName>
    <FirstName>Ginf1_LN1</FirstName>
    <Matiere codeMatiere="GINF11">19</Matiere>
    <Matiere codeMatiere="GINF12">15</Matiere>
    <Matiere codeMatiere="GINF13">16</Matiere>
    <Matiere codeMatiere="GINF14">12</Matiere>
    <Matiere codeMatiere="GINF15">12</Matiere>
    <Matiere codeMatiere="GINF16">20</Matiere>
    <Matiere codeMatiere="GINF21">12</Matiere>
    <Matiere codeMatiere="GINF22">13</Matiere>
    <Matiere codeMatiere="GINF23">12</Matiere>
    <Matiere codeMatiere="GINF24">16</Matiere>
    <Matiere codeMatiere="GINF25">20</Matiere>
    <Matiere codeMatiere="GINF26">12</Matiere>
  </Note>
  <Note>
    <CNE>19000032</CNE>
    <LastName>Ginf1_FN2</LastName>
    <FirstName>Ginf1_LN2</FirstName>
    <Matiere codeMatiere="GINF11">13</Matiere>
    <Matiere codeMatiere="GINF12">13</Matiere>
    <Matiere codeMatiere="GINF13">19</Matiere>
    <Matiere codeMatiere="GINF14">13</Matiere>
    <Matiere codeMatiere="GINF15">15</Matiere>
    <Matiere codeMatiere="GINF16">20</Matiere>
    <Matiere codeMatiere="GINF21">15</Matiere>
    <Matiere codeMatiere="GINF22">7</Matiere>
    <Matiere codeMatiere="GINF23">13</Matiere>
    <Matiere codeMatiere="GINF24">11</Matiere>
    <Matiere codeMatiere="GINF25">15</Matiere>
    <Matiere codeMatiere="GINF26">12</Matiere>
  </Note>
  <Note>
    <CNE>19000033</CNE>
    <LastName>Ginf1_FN3</LastName>
    <FirstName>Ginf1_LN3</FirstName>
    <Matiere codeMatiere="GINF11">14</Matiere>
    <Matiere codeMatiere="GINF12">18</Matiere>
    <Matiere codeMatiere="GINF13">16</Matiere>
    <Matiere codeMatiere="GINF14">12</Matiere>
    <Matiere codeMatiere="GINF15">17</Matiere>
    <Matiere codeMatiere="GINF16">16</Matiere>
    <Matiere codeMatiere="GINF21">12</Matiere>
    <Matiere codeMatiere="GINF22">10</Matiere>
    <Matiere codeMatiere="GINF23">13</Matiere>
    <Matiere codeMatiere="GINF24">12</Matiere>
    <Matiere codeMatiere="GINF25">12</Matiere>
    <Matiere codeMatiere="GINF26">19</Matiere>
  </Note>
  <Note>
    <CNE>19000034</CNE>
    <LastName>Ginf1_FN4</LastName>
    <FirstName>Ginf1_LN4</FirstName>
    <Matiere codeMatiere="GINF11">16</Matiere>
    <Matiere codeMatiere="GINF12">12</Matiere>
    <Matiere codeMatiere="GINF13">14</Matiere>
    <Matiere codeMatiere="GINF14">14</Matiere>
    <Matiere codeMatiere="GINF15">12</Matiere>
    <Matiere codeMatiere="GINF16">20</Matiere>
    <Matiere codeMatiere="GINF21">17</Matiere>
    <Matiere codeMatiere="GINF22">15</Matiere>
    <Matiere codeMatiere="GINF23">17</Matiere>
    <Matiere codeMatiere="GINF24">12</Matiere>
    <Matiere codeMatiere="GINF25">14</Matiere>
    <Matiere codeMatiere="GINF26">14</Matiere>
  </Note>
  <Note>
    <CNE>19000035</CNE>
    <LastName>Ginf1_FN5</LastName>
    <FirstName>Ginf1_LN5</FirstName>
    <Matiere codeMatiere="GINF11">12</Matiere>
    <Matiere codeMatiere="GINF12">8</Matiere>
    <Matiere codeMatiere="GINF13">13</Matiere>
    <Matiere codeMatiere="GINF14">13</Matiere>
    <Matiere codeMatiere="GINF15">12</Matiere>
    <Matiere codeMatiere="GINF16">11</Matiere>
    <Matiere codeMatiere="GINF21">8</Matiere>
    <Matiere codeMatiere="GINF22">13</Matiere>
    <Matiere codeMatiere="GINF23">17</Matiere>
    <Matiere codeMatiere="GINF24">12</Matiere>
    <Matiere codeMatiere="GINF25">17</Matiere>
    <Matiere codeMatiere="GINF26">20</Matiere>
  </Note>
  <Note>
    <CNE>19000036</CNE>
    <LastName>Ginf1_FN6</LastName>
    <FirstName>Ginf1_LN6</FirstName>
    <Matiere codeMatiere="GINF11">18</Matiere>
    <Matiere codeMatiere="GINF12">17</Matiere>
    <Matiere codeMatiere="GINF13">17</Matiere>
    <Matiere codeMatiere="GINF14">20</Matiere>
    <Matiere codeMatiere="GINF15">12</Matiere>
    <Matiere codeMatiere="GINF16">12</Matiere>
    <Matiere codeMatiere="GINF21">12</Matiere>
    <Matiere codeMatiere="GINF22">12</Matiere>
    <Matiere codeMatiere="GINF23">14</Matiere>
    <Matiere codeMatiere="GINF24">18</Matiere>
    <Matiere codeMatiere="GINF25">13</Matiere>
    <Matiere codeMatiere="GINF26">12</Matiere>
  </Note>
  <Note>
    <CNE>19000037</CNE>
    <LastName>Ginf1_FN7</LastName>
    <FirstName>Ginf1_LN7</FirstName>
    <Matiere codeMatiere="GINF11">10</Matiere>
    <Matiere codeMatiere="GINF12">12</Matiere>
    <Matiere codeMatiere="GINF13">12</Matiere>
    <Matiere codeMatiere="GINF14">18</Matiere>
    <Matiere codeMatiere="GINF15">13</Matiere>
    <Matiere codeMatiere="GINF16">19</Matiere>
    <Matiere codeMatiere="GINF21">16</Matiere>
    <Matiere codeMatiere="GINF22">16</Matiere>
    <Matiere codeMatiere="GINF23">16</Matiere>
    <Matiere codeMatiere="GINF24">18</Matiere>
    <Matiere codeMatiere="GINF25">16</Matiere>
    <Matiere codeMatiere="GINF26">12</Matiere>
  </Note>
  <Note>
    <CNE>19000038</CNE>
    <LastName>Ginf1_FN8</LastName>
    <FirstName>Ginf1_LN8</FirstName>
    <Matiere codeMatiere="GINF11">12</Matiere>
    <Matiere codeMatiere="GINF12">12</Matiere>
    <Matiere codeMatiere="GINF13">20</Matiere>
    <Matiere codeMatiere="GINF14">11</Matiere>
    <Matiere codeMatiere="GINF15">18</Matiere>
    <Matiere codeMatiere="GINF16">14</Matiere>
    <Matiere codeMatiere="GINF21">12</Matiere>
    <Matiere codeMatiere="GINF22">12</Matiere>
    <Matiere codeMatiere="GINF23">12</Matiere>
    <Matiere codeMatiere="GINF24">20</Matiere>
    <Matiere codeMatiere="GINF25">13</Matiere>
    <Matiere codeMatiere="GINF26">12</Matiere>
  </Note>
  <Note>
    <CNE>19000039</CNE>
    <LastName>Ginf1_FN9</LastName>
    <FirstName>Ginf1_LN9</FirstName>
    <Matiere codeMatiere="GINF11">13</Matiere>
    <Matiere codeMatiere="GINF12">13</Matiere>
    <Matiere codeMatiere="GINF13">20</Matiere>
    <Matiere codeMatiere="GINF14">13</Matiere>
    <Matiere codeMatiere="GINF15">12</Matiere>
    <Matiere codeMatiere="GINF16">18</Matiere>
    <Matiere codeMatiere="GINF21">9</Matiere>
    <Matiere codeMatiere="GINF22">12</Matiere>
    <Matiere codeMatiere="GINF23">20</Matiere>
    <Matiere codeMatiere="GINF24">20</Matiere>
    <Matiere codeMatiere="GINF25">17</Matiere>
    <Matiere codeMatiere="GINF26">14</Matiere>
  </Note>
  <Note>
    <CNE>19000040</CNE>
    <LastName>Ginf1_FN10</LastName>
    <FirstName>Ginf1_LN10</FirstName>
    <Matiere codeMatiere="GINF11">12</Matiere>
    <Matiere codeMatiere="GINF12">20</Matiere>
    <Matiere codeMatiere="GINF13">13</Matiere>
    <Matiere codeMatiere="GINF14">16</Matiere>
    <Matiere codeMatiere="GINF15">12</Matiere>
    <Matiere codeMatiere="GINF16">12</Matiere>
    <Matiere codeMatiere="GINF21">15</Matiere>
    <Matiere codeMatiere="GINF22">15</Matiere>
    <Matiere codeMatiere="GINF23">20</Matiere>
    <Matiere codeMatiere="GINF24">10</Matiere>
    <Matiere codeMatiere="GINF25">13</Matiere>
    <Matiere codeMatiere="GINF26">19</Matiere>
  </Note>
</Notes>

=== amamatou/GestionScolarite-XML/Fichiers_xml/Notes_G3EI2_Avant.xml
<?xml version="1.0"?>
<Notes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C://xampp/htdocs/GestionScolarite-XML/Validation_xml/Notes.xsd">
  <Note>
    <CNE>18000041</CNE>
    <LastName>G3EI2_FN1</LastName>
    <FirstName>G3EI2_LN1</FirstName>
    <Matiere codeMatiere="G3EI31">12.76</Matiere>
    <Matiere codeMatiere="G3EI32">10.73</Matiere>
    <Matiere codeMatiere="G3EI33">15.06</Matiere>
    <Matiere codeMatiere="G3EI34">12</Matiere>
    <Matiere codeMatiere="G3EI35">9.09</Matiere>
    <Matiere codeMatiere="G3EI36">12</Matiere>
    <Matiere codeMatiere="G3EI37">19.32</Matiere>
    <Matiere codeMatiere="G3EI38">12</Matiere>
    <Matiere codeMatiere="G3EI39">11.44</Matiere>
  </Note>
  <Note>
    <CNE>18000042</CNE>
    <LastName>G3EI2_FN2</LastName>
    <FirstName>G3EI2_LN2</FirstName>
    <Matiere codeMatiere="G3EI31">13.76</Matiere>
    <Matiere codeMatiere="G3EI32">18.7</Matiere>
    <Matiere codeMatiere="G3EI33">15.13</Matiere>
    <Matiere codeMatiere="G3EI34">18</Matiere>
    <Matiere codeMatiere="G3EI35">13</Matiere>
    <Matiere codeMatiere="G3EI36">13.6</Matiere>
    <Matiere codeMatiere="G3EI37">19.65</Matiere>
    <Matiere codeMatiere="G3EI38">15.98</Matiere>
    <Matiere codeMatiere="G3EI39">18.64</Matiere>
  </Note>
  <Note>
    <CNE>18000043</CNE>
    <LastName>G3EI2_FN3</LastName>
    <FirstName>G3EI2_LN3</FirstName>
    <Matiere codeMatiere="G3EI31">12</Matiere>
    <Matiere codeMatiere="G3EI32">12.7</Matiere>
    <Matiere codeMatiere="G3EI33">15.77</Matiere>
    <Matiere codeMatiere="G3EI34">4</Matiere>
    <Matiere codeMatiere="G3EI35">12.7</Matiere>
    <Matiere codeMatiere="G3EI36">17.76</Matiere>
    <Matiere codeMatiere="G3EI37">12.39</Matiere>
    <Matiere codeMatiere="G3EI38">13.09</Matiere>
    <Matiere codeMatiere="G3EI39">14.83</Matiere>
  </Note>
  <Note>
    <CNE>18000044</CNE>
    <LastName>G3EI2_FN4</LastName>
    <FirstName>G3EI2_LN4</FirstName>
    <Matiere codeMatiere="G3EI31">11.8</Matiere>
    <Matiere codeMatiere="G3EI32">9.6</Matiere>
    <Matiere codeMatiere="G3EI33">16.26</Matiere>
    <Matiere codeMatiere="G3EI34">5.87</Matiere>
    <Matiere codeMatiere="G3EI35">12.76</Matiere>
    <Matiere codeMatiere="G3EI36">12.98</Matiere>
    <Matiere codeMatiere="G3EI37">13.09</Matiere>
    <Matiere codeMatiere="G3EI38">14</Matiere>
    <Matiere codeMatiere="G3EI39">17.3</Matiere>
  </Note>
  <Note>
    <CNE>18000045</CNE>
    <LastName>G3EI2_FN5</LastName>
    <FirstName>G3EI2_LN5</FirstName>
    <Matiere codeMatiere="G3EI31">16.9</Matiere>
    <Matiere codeMatiere="G3EI32">18</Matiere>
    <Matiere codeMatiere="G3EI33">16.66</Matiere>
    <Matiere codeMatiere="G3EI34">13</Matiere>
    <Matiere codeMatiere="G3EI35">14</Matiere>
    <Matiere codeMatiere="G3EI36">10</Matiere>
    <Matiere codeMatiere="G3EI37">17.88</Matiere>
    <Matiere codeMatiere="G3EI38">12.04</Matiere>
    <Matiere codeMatiere="G3EI39">15.84</Matiere>
  </Note>
  <Note>
    <CNE>18000046</CNE>
    <LastName>G3EI2_FN6</LastName>
    <FirstName>G3EI2_LN6</FirstName>
    <Matiere codeMatiere="G3EI31">14.74</Matiere>
    <Matiere codeMatiere="G3EI32">13</Matiere>
    <Matiere codeMatiere="G3EI33">11.85</Matiere>
    <Matiere codeMatiere="G3EI34">18.65</Matiere>
    <Matiere codeMatiere="G3EI35">15.66</Matiere>
    <Matiere codeMatiere="G3EI36">11.29</Matiere>
    <Matiere codeMatiere="G3EI37">8.66</Matiere>
    <Matiere codeMatiere="G3EI38">9.5</Matiere>
    <Matiere codeMatiere="G3EI39">16.9</Matiere>
  </Note>
  <Note>
    <CNE>18000047</CNE>
    <LastName>G3EI2_FN7</LastName>
    <FirstName>G3EI2_LN7</FirstName>
    <Matiere codeMatiere="G3EI31">12.86</Matiere>
    <Matiere codeMatiere="G3EI32">10.86</Matiere>
    <Matiere codeMatiere="G3EI33">14.11</Matiere>
    <Matiere codeMatiere="G3EI34">10</Matiere>
    <Matiere codeMatiere="G3EI35">12.78</Matiere>
    <Matiere codeMatiere="G3EI36">13.17</Matiere>
    <Matiere codeMatiere="G3EI37">13.82</Matiere>
    <Matiere codeMatiere="G3EI38">10.83</Matiere>
    <Matiere codeMatiere="G3EI39">14</Matiere>
  </Note>
  <Note>
    <CNE>18000048</CNE>
    <LastName>G3EI2_FN8</LastName>
    <FirstName>G3EI2_LN8</FirstName>
    <Matiere codeMatiere="G3EI31">16.51</Matiere>
    <Matiere codeMatiere="G3EI32">18.84</Matiere>
    <Matiere codeMatiere="G3EI33">13.45</Matiere>
    <Matiere codeMatiere="G3EI34">12</Matiere>
    <Matiere codeMatiere="G3EI35">12.07</Matiere>
    <Matiere codeMatiere="G3EI36">14.63</Matiere>
    <Matiere codeMatiere="G3EI37">12</Matiere>
    <Matiere codeMatiere="G3EI38">15.92</Matiere>
    <Matiere codeMatiere="G3EI39">15</Matiere>
  </Note>
  <Note>
    <CNE>18000049</CNE>
    <LastName>G3EI2_FN9</LastName>
    <FirstName>G3EI2_LN9</FirstName>
    <Matiere codeMatiere="G3EI31">17.15</Matiere>
    <Matiere codeMatiere="G3EI32">10.95</Matiere>
    <Matiere codeMatiere="G3EI33">17.83</Matiere>
    <Matiere codeMatiere="G3EI34">15</Matiere>
    <Matiere codeMatiere="G3EI35">12.65</Matiere>
    <Matiere codeMatiere="G3EI36">14.02</Matiere>
    <Matiere codeMatiere="G3EI37">15.78</Matiere>
    <Matiere codeMatiere="G3EI38">16.32</Matiere>
    <Matiere codeMatiere="G3EI39">4.5</Matiere>
  </Note>
  <Note>
    <CNE>18000050</CNE>
    <LastName>G3EI2_FN10</LastName>
    <FirstName>G3EI2_LN10</FirstName>
    <Matiere codeMatiere="G3EI31">11.85</Matiere>
    <Matiere codeMatiere="G3EI32">11.39</Matiere>
    <Matiere codeMatiere="G3EI33">9.67</Matiere>
    <Matiere codeMatiere="G3EI34">7.5</Matiere>
    <Matiere codeMatiere="G3EI35">9.26</Matiere>
    <Matiere codeMatiere="G3EI36">17.68</Matiere>
    <Matiere codeMatiere="G3EI37">18.55</Matiere>
    <Matiere codeMatiere="G3EI38">8.45</Matiere>
    <Matiere codeMatiere="G3EI39">10.74</Matiere>
  </Note>
</Notes>
