=== amamatou/GestionScolarite-XML/Validation_xml/Students.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
elementFormDefault="qualified">

<xs:element name="Students">
   <xs:complexType>
     <xs:sequence>
      <xs:element name="Student" maxOccurs="240" minOccurs="24">
       <xs:complexType>
        <xs:sequence>
          <xs:element name="CNE" type="xs:string"/>
          <xs:element name="LastName">
            <xs:simpleType>
              <xs:restriction base="xs:string">
                <xs:pattern value="[A-Z]([aA-zZ\s*])*"/>
              </xs:restriction>
            </xs:simpleType>
          </xs:element>
          <xs:element name="FirstName">
          <xs:simpleType>
              <xs:restriction base="xs:string">
                <xs:pattern value="[A-Z]([aA-zZ\s*])*"/>
              </xs:restriction>
            </xs:simpleType>
          </xs:element>
          <xs:element name="DateofBirth" type="xs:date"/>
          <xs:element name="ClasseName" type="xs:string"/>
          <xs:element name="Phone" type="xs:string"/>
          <xs:element name="Email" type="xs:string"/>
        </xs:sequence>
        </xs:complexType>
    </xs:element>
   </xs:sequence>
  </xs:complexType> 
  </xs:element>

  </xs:schema>

=== amamatou/GestionScolarite-XML/Fichiers_xml/Groupes/AP1_Gr3.xml
<?xml version="1.0"?>
<Students xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C://xampp/htdocs/GestionScolarite-XML/Validation_xml/Students.xsd"><Student>
    <CNE>21000049</CNE>
    <LastName>Vincent Cobb</LastName>
    <FirstName>Russell Calderon</FirstName>
    <DateofBirth>2013-12-10</DateofBirth>
    <ClasseName>AP1</ClasseName>
    <Phone>07 28 60 91 32</Phone>
    <Email>VincentCobb.RussellCalderon@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>21000050</CNE>
    <LastName>Lacy Watkins</LastName>
    <FirstName>Jarrod Boyer</FirstName>
    <DateofBirth>2007-05-13</DateofBirth>
    <ClasseName>AP1</ClasseName>
    <Phone>861363657</Phone>
    <Email>LacyWatkins.JarrodBoyer@etu.uae.ac.ma</Email>
  </Student></Students>

=== amamatou/GestionScolarite-XML/Fichiers_xml/Groupes/GIL1_Gr1.xml
<?xml version="1.0"?>
<Students xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C://xampp/htdocs/GestionScolarite-XML/Validation_xml/Students.xsd"><Student>
    <CNE>19000051</CNE>
    <LastName>Castor Lambert</LastName>
    <FirstName>Bianca Rosa</FirstName>
    <DateofBirth>2001-12-19</DateofBirth>
    <ClasseName>GIL1</ClasseName>
    <Phone>04 61 71 56 86</Phone>
    <Email>CastorLambert.BiancaRosa@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>19000052</CNE>
    <LastName>Rhonda Middleton</LastName>
    <FirstName>Mannix Martin</FirstName>
    <DateofBirth>2000-07-20</DateofBirth>
    <ClasseName>GIL1</ClasseName>
    <Phone>01 82 98 92 66</Phone>
    <Email>RhondaMiddleton.MannixMartin@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>19000053</CNE>
    <LastName>Hall Fitzpatrick</LastName>
    <FirstName>Cain Mccormick</FirstName>
    <DateofBirth>1999-01-12</DateofBirth>
    <ClasseName>GIL1</ClasseName>
    <Phone>05 81 86 42 78</Phone>
    <Email>HallFitzpatrick.CainMccormick@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>19000054</CNE>
    <LastName>Madaline Willis</LastName>
    <FirstName>Rudyard Nicholson</FirstName>
    <DateofBirth>1998-08-18</DateofBirth>
    <ClasseName>GIL1</ClasseName>
    <Phone>03 26 99 58 62</Phone>
    <Email>MadalineWillis.RudyardNicholson@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>19000055</CNE>
    <LastName>Driscoll Bowers</LastName>
    <FirstName>Sasha Ray</FirstName>
    <DateofBirth>1999-11-21</DateofBirth>
    <ClasseName>GIL1</ClasseName>
    <Phone>06 55 33 32 49</Phone>
    <Email>DriscollBowers.SashaRay@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>19000056</CNE>
    <LastName>Linda Larson</LastName>
    <FirstName>Clark Galloway</FirstName>
    <DateofBirth>1997-10-22</DateofBirth>
    <ClasseName>GIL1</ClasseName>
    <Phone>03 34 09 32 82</Phone>
    <Email>LindaLarson.ClarkGalloway@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>19000057</CNE>
    <LastName>Randall Cobb</LastName>
    <FirstName>Travis Brooks</FirstName>
    <DateofBirth>1998-09-30</DateofBirth>
    <ClasseName>GIL1</ClasseName>
    <Phone>03 76 66 24 37</Phone>
    <Email>RandallCobb.TravisBrooks@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>19000058</CNE>
    <LastName>Buffy Cash</LastName>
    <FirstName>Oren William</FirstName>
    <DateofBirth>1999-05-03</DateofBirth>
    <ClasseName>GIL1</ClasseName>
    <Phone>02 78 68 35 35</Phone>
    <Email>BuffyCash.OrenWilliam@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>19000059</CNE>
    <LastName>Raphael Ward</LastName>
    <FirstName>Micah Hammond</FirstName>
    <DateofBirth>1997-03-23</DateofBirth>
    <ClasseName>GIL1</ClasseName>
    <Phone>05 38 86 88 53</Phone>
    <Email>RaphaelWard.MicahHammond@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>19000060</CNE>
    <LastName>Sylvester Quinn</LastName>
    <FirstName>Lani Lawrence</FirstName>
    <DateofBirth>1998-10-16</DateofBirth>
    <ClasseName>GIL1</ClasseName>
    <Phone>05 44 22 75 86</Phone>
    <Email>SylvesterQuinn.LaniLawrence@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>19000061</CNE>
    <LastName>Oprah Glass</LastName>
    <FirstName>Beau Mckenzie</FirstName>
    <DateofBirth>2002-01-06</DateofBirth>
    <ClasseName>GIL1</ClasseName>
    <Phone>05 52 77 10 53</Phone>
    <Email>OprahGlass.BeauMckenzie@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>19000062</CNE>
    <LastName>Hilary Hoover</LastName>
    <FirstName>Alfreda Contreras</FirstName>
    <DateofBirth>1999-12-05</DateofBirth>
    <ClasseName>GIL1</ClasseName>
    <Phone>08 21 99 89 95</Phone>
    <Email>HilaryHoover.AlfredaContreras@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>19000063</CNE>
    <LastName>Ira Vargas</LastName>
    <FirstName>Theodore Bird</FirstName>
    <DateofBirth>2001-04-30</DateofBirth>
    <ClasseName>GIL1</ClasseName>
    <Phone>06 25 87 28 26</Phone>
    <Email>IraVargas.TheodoreBird@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>19000064</CNE>
    <LastName>Gretchen Hull</LastName>
    <FirstName>Charles Hoffman</FirstName>
    <DateofBirth>2001-06-10</DateofBirth>
    <ClasseName>GIL1</ClasseName>
    <Phone>08 58 46 48 26</Phone>
    <Email>GretchenHull.CharlesHoffman@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>19000065</CNE>
    <LastName>Zachery Herrera</LastName>
    <FirstName>Darrel Whitney</FirstName>
    <DateofBirth>1997-11-23</DateofBirth>
    <ClasseName>GIL1</ClasseName>
    <Phone>05 93 58 74 38</Phone>
    <Email>ZacheryHerrera.DarrelWhitney@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>19000066</CNE>
    <LastName>Dale Short</LastName>
    <FirstName>Joelle Whitley</FirstName>
    <DateofBirth>1998-06-11</DateofBirth>
    <ClasseName>GIL1</ClasseName>
    <Phone>05 65 75 13 40</Phone>
    <Email>DaleShort.JoelleWhitley@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>19000067</CNE>
    <LastName>Beau Stone</LastName>
    <FirstName>Adena Frank</FirstName>
    <DateofBirth>1998-01-25</DateofBirth>
    <ClasseName>GIL1</ClasseName>
    <Phone>01 84 85 44 08</Phone>
    <Email>BeauStone.AdenaFrank@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>19000068</CNE>
    <LastName>Acton Peterson</LastName>
    <FirstName>Velma Ayers</FirstName>
    <DateofBirth>1999-08-28</DateofBirth>
    <ClasseName>GIL1</ClasseName>
    <Phone>01 56 73 76 97</Phone>
    <Email>ActonPeterson.VelmaAyers@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>19000069</CNE>
    <LastName>Lars Davis</LastName>
    <FirstName>Uma Valdez</FirstName>
    <DateofBirth>2002-09-27</DateofBirth>
    <ClasseName>GIL1</ClasseName>
    <Phone>03 71 87 00 60</Phone>
    <Email>LarsDavis.UmaValdez@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>19000070</CNE>
    <LastName>Raphael Burnett</LastName>
    <FirstName>Hunter Carter</FirstName>
    <DateofBirth>2002-09-19</DateofBirth>
    <ClasseName>GIL1</ClasseName>
    <Phone>06 30 11 04 81</Phone>
    <Email>RaphaelBurnett.HunterCarter@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>19000071</CNE>
    <LastName>Thaddeus Holman</LastName>
    <FirstName>Robert Merritt</FirstName>
    <DateofBirth>2002-10-30</DateofBirth>
    <ClasseName>GIL1</ClasseName>
    <Phone>07 16 53 98 39</Phone>
    <Email>ThaddeusHolman.RobertMerritt@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>19000072</CNE>
    <LastName>Sierra Edwards</LastName>
    <FirstName>Emma Valdez</FirstName>
    <DateofBirth>1999-09-29</DateofBirth>
    <ClasseName>GIL1</ClasseName>
    <Phone>04 74 77 36 84</Phone>
    <Email>SierraEdwards.EmmaValdez@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>19000073</CNE>
    <LastName>Aquila Vance</LastName>
    <FirstName>Yen Whitfield</FirstName>
    <DateofBirth>1999-03-07</DateofBirth>
    <ClasseName>GIL1</ClasseName>
    <Phone>07 55 33 70 27</Phone>
    <Email>AquilaVance.YenWhitfield@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>19000074</CNE>
    <LastName>Rhea Montoya</LastName>
    <FirstName>Chester Giles</FirstName>
    <DateofBirth>2002-09-20</DateofBirth>
    <ClasseName>GIL1</ClasseName>
    <Phone>07 78 31 68 73</Phone>
    <Email>RheaMontoya.ChesterGiles@etu.uae.ac.ma</Email>
  </Student></Students>

=== amamatou/GestionScolarite-XML/Fichiers_xml/Groupes/GSTR2_Gr1.xml
<?xml version="1.0"?>
<Students xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C://xampp/htdocs/GestionScolarite-XML/Validation_xml/Students.xsd"><Student>
    <CNE>18000001</CNE>
    <LastName>Orli</LastName>
    <FirstName>Susan Daniels</FirstName>
    <DateofBirth>2000-06-23</DateofBirth>
    <ClasseName>Gstr2</ClasseName>
    <Phone>04 55 53 62 61</Phone>
    <Email>Orli.SusanDaniels@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>18000002</CNE>
    <LastName>Hedda</LastName>
    <FirstName>Raymond Goodwin</FirstName>
    <DateofBirth>2011-12-11</DateofBirth>
    <ClasseName>Gstr2</ClasseName>
    <Phone>09 84 21 07 56</Phone>
    <Email>Hedda.RaymondGoodwin@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>18000003</CNE>
    <LastName>Silas</LastName>
    <FirstName>Leroy Ray</FirstName>
    <DateofBirth>2006-02-09</DateofBirth>
    <ClasseName>Gstr2</ClasseName>
    <Phone>08 70 13 94 18</Phone>
    <Email>Silas.LeroyRay@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>18000004</CNE>
    <LastName>Kenneth</LastName>
    <FirstName>Joan Jones</FirstName>
    <DateofBirth>2003-07-06</DateofBirth>
    <ClasseName>Gstr2</ClasseName>
    <Phone>04 83 69 20 29</Phone>
    <Email>Kenneth.JoanJones@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>18000005</CNE>
    <LastName>Cain</LastName>
    <FirstName>Sebastian Ballard</FirstName>
    <DateofBirth>2005-02-28</DateofBirth>
    <ClasseName>Gstr2</ClasseName>
    <Phone>06 86 52 80 14</Phone>
    <Email>Cain.SebastianBallard@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>18000006</CNE>
    <LastName>Clementine</LastName>
    <FirstName>Winter Larson</FirstName>
    <DateofBirth>2003-03-14</DateofBirth>
    <ClasseName>Gstr2</ClasseName>
    <Phone>02 35 11 16 80</Phone>
    <Email>Clementine.WinterLarson@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>18000007</CNE>
    <LastName>Georgia</LastName>
    <FirstName>Owen Horton</FirstName>
    <DateofBirth>2005-12-25</DateofBirth>
    <ClasseName>Gstr2</ClasseName>
    <Phone>09 52 43 35 83</Phone>
    <Email>Georgia.OwenHorton@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>18000008</CNE>
    <LastName>Eve</LastName>
    <FirstName>Kimberley Arnold</FirstName>
    <DateofBirth>2013-10-09</DateofBirth>
    <ClasseName>Gstr2</ClasseName>
    <Phone>07 71 66 45 72</Phone>
    <Email>Eve.KimberleyArnold@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>18000009</CNE>
    <LastName>Josiah</LastName>
    <FirstName>Lacy Gardner</FirstName>
    <DateofBirth>2004-10-06</DateofBirth>
    <ClasseName>Gstr2</ClasseName>
    <Phone>08 34 10 71 38</Phone>
    <Email>Josiah.LacyGardner@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>18000010</CNE>
    <LastName>Ainsley</LastName>
    <FirstName>Molly Livingston</FirstName>
    <DateofBirth>2014-01-15</DateofBirth>
    <ClasseName>Gstr2</ClasseName>
    <Phone>08 77 78 28 12</Phone>
    <Email>Ainsley.MollyLivingston@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>18000011</CNE>
    <LastName>Gwendolyn</LastName>
    <FirstName>Carol Knowles</FirstName>
    <DateofBirth>2000-09-10</DateofBirth>
    <ClasseName>Gstr2</ClasseName>
    <Phone>04 32 77 12 35</Phone>
    <Email>Gwendolyn.CarolKnowles@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>18000012</CNE>
    <LastName>Quon</LastName>
    <FirstName>Michael Brown</FirstName>
    <DateofBirth>2012-07-20</DateofBirth>
    <ClasseName>Gstr2</ClasseName>
    <Phone>07 84 43 22 23</Phone>
    <Email>Quon.MichaelBrown@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>18000013</CNE>
    <LastName>Halla</LastName>
    <FirstName>Lillian Greer</FirstName>
    <DateofBirth>2003-05-23</DateofBirth>
    <ClasseName>Gstr2</ClasseName>
    <Phone>06 45 81 28 67</Phone>
    <Email>Halla.LillianGreer@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>18000014</CNE>
    <LastName>Ryan</LastName>
    <FirstName>Ishmael Donovan</FirstName>
    <DateofBirth>2002-11-16</DateofBirth>
    <ClasseName>Gstr2</ClasseName>
    <Phone>09 61 41 16 12</Phone>
    <Email>Ryan.IshmaelDonovan@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>18000015</CNE>
    <LastName>Daria</LastName>
    <FirstName>Kenyon Booker</FirstName>
    <DateofBirth>2010-01-01</DateofBirth>
    <ClasseName>Gstr2</ClasseName>
    <Phone>03 64 34 11 35</Phone>
    <Email>Daria.KenyonBooker@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>18000016</CNE>
    <LastName>Frances</LastName>
    <FirstName>Cody Martinez</FirstName>
    <DateofBirth>2011-01-15</DateofBirth>
    <ClasseName>Gstr2</ClasseName>
    <Phone>07 20 76 02 22</Phone>
    <Email>Frances.CodyMartinez@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>18000017</CNE>
    <LastName>Iris</LastName>
    <FirstName>Roth Downs</FirstName>
    <DateofBirth>2002-12-17</DateofBirth>
    <ClasseName>Gstr2</ClasseName>
    <Phone>09 59 25 68 83</Phone>
    <Email>Iris.RothDowns@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>18000018</CNE>
    <LastName>Naomi</LastName>
    <FirstName>Justin Warren</FirstName>
    <DateofBirth>2011-08-16</DateofBirth>
    <ClasseName>Gstr2</ClasseName>
    <Phone>02 11 77 34 56</Phone>
    <Email>Naomi.JustinWarren@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>18000019</CNE>
    <LastName>Stacey</LastName>
    <FirstName>Malachi Vazquez</FirstName>
    <DateofBirth>2009-04-27</DateofBirth>
    <ClasseName>Gstr2</ClasseName>
    <Phone>04 42 85 25 31</Phone>
    <Email>Stacey.MalachiVazquez@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>18000020</CNE>
    <LastName>Summer</LastName>
    <FirstName>Nayda Davenport</FirstName>
    <DateofBirth>2008-12-02</DateofBirth>
    <ClasseName>Gstr2</ClasseName>
    <Phone>07 35 37 50 32</Phone>
    <Email>Summer.NaydaDavenport@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>18000021</CNE>
    <LastName>MacKenzie</LastName>
    <FirstName>Hammett Barber</FirstName>
    <DateofBirth>2014-12-06</DateofBirth>
    <ClasseName>Gstr2</ClasseName>
    <Phone>08 65 51 12 25</Phone>
    <Email>MacKenzie.HammettBarber@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>18000022</CNE>
    <LastName>Zahir</LastName>
    <FirstName>Cole Lang</FirstName>
    <DateofBirth>2001-04-21</DateofBirth>
    <ClasseName>Gstr2</ClasseName>
    <Phone>01 27 71 98 57</Phone>
    <Email>Zahir.ColeLang@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>18000023</CNE>
    <LastName>Ramona</LastName>
    <FirstName>Branden Mcconnell</FirstName>
    <DateofBirth>2012-12-29</DateofBirth>
    <ClasseName>Gstr2</ClasseName>
    <Phone>07 67 31 56 81</Phone>
    <Email>Ramona.BrandenMcconnell@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>18000024</CNE>
    <LastName>Herrod</LastName>
    <FirstName>Aurora Cortez</FirstName>
    <DateofBirth>2013-05-01</DateofBirth>
    <ClasseName>Gstr2</ClasseName>
    <Phone>02 46 82 15 40</Phone>
    <Email>Herrod.AuroraCortez@etu.uae.ac.ma</Email>
  </Student></Students>

=== amamatou/GestionScolarite-XML/Fichiers_xml/Groupes/GINF1_Gr3.xml
<?xml version="1.0"?>
<Students xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C://xampp/htdocs/GestionScolarite-XML/Validation_xml/Students.xsd"><Student>
    <CNE>19000199</CNE>
    <LastName>Regina Barrera</LastName>
    <FirstName>Julian Valencia</FirstName>
    <DateofBirth>1998-02-19</DateofBirth>
    <ClasseName>Ginf1</ClasseName>
    <Phone>06 68 46 46 44</Phone>
    <Email>ReginaBarrera.JulianValencia@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>19000200</CNE>
    <LastName>Asher Bishop</LastName>
    <FirstName>Geraldine Harris</FirstName>
    <DateofBirth>1997-12-07</DateofBirth>
    <ClasseName>Ginf1</ClasseName>
    <Phone>02 54 65 03 98</Phone>
    <Email>AsherBishop.GeraldineHarris@etu.uae.ac.ma</Email>
  </Student></Students>

=== amamatou/GestionScolarite-XML/Fichiers_xml/Groupes/G3EI1_Gr2.xml
<?xml version="1.0"?>
<Students xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C://xampp/htdocs/GestionScolarite-XML/Validation_xml/Students.xsd"><Student>
    <CNE>19000225</CNE>
    <LastName>Maile Hayden</LastName>
    <FirstName>Rashad Ramsey</FirstName>
    <DateofBirth>2001-06-05</DateofBirth>
    <ClasseName>G3EI1</ClasseName>
    <Phone>04 73 43 44 15</Phone>
    <Email>MaileHayden.RashadRamsey@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>19000226</CNE>
    <LastName>Ciaran Flowers</LastName>
    <FirstName>Ella Wilcox</FirstName>
    <DateofBirth>1998-10-16</DateofBirth>
    <ClasseName>G3EI1</ClasseName>
    <Phone>04 78 68 08 86</Phone>
    <Email>CiaranFlowers.EllaWilcox@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>19000227</CNE>
    <LastName>Oleg Bruce</LastName>
    <FirstName>Colin Collier</FirstName>
    <DateofBirth>1998-08-23</DateofBirth>
    <ClasseName>G3EI1</ClasseName>
    <Phone>06 39 89 67 61</Phone>
    <Email>OlegBruce.ColinCollier@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>19000228</CNE>
    <LastName>Conan Bradshaw</LastName>
    <FirstName>Alisa Dawson</FirstName>
    <DateofBirth>1999-01-01</DateofBirth>
    <ClasseName>G3EI1</ClasseName>
    <Phone>03 54 33 51 52</Phone>
    <Email>ConanBradshaw.AlisaDawson@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>19000229</CNE>
    <LastName>Destiny Landry</LastName>
    <FirstName>Lane Burt</FirstName>
    <DateofBirth>2000-02-24</DateofBirth>
    <ClasseName>G3EI1</ClasseName>
    <Phone>02 21 50 79 45</Phone>
    <Email>DestinyLandry.LaneBurt@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>19000230</CNE>
    <LastName>Leandra Faulkner</LastName>
    <FirstName>Raymond Weber</FirstName>
    <DateofBirth>2001-06-20</DateofBirth>
    <ClasseName>G3EI1</ClasseName>
    <Phone>02 54 54 30 61</Phone>
    <Email>LeandraFaulkner.RaymondWeber@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>19000231</CNE>
    <LastName>Maryam Richards</LastName>
    <FirstName>Ursula Morrison</FirstName>
    <DateofBirth>1999-05-20</DateofBirth>
    <ClasseName>G3EI1</ClasseName>
    <Phone>08 37 77 34 31</Phone>
    <Email>MaryamRichards.UrsulaMorrison@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>19000232</CNE>
    <LastName>Odessa Jenkins</LastName>
    <FirstName>Hakeem Cooper</FirstName>
    <DateofBirth>2002-12-09</DateofBirth>
    <ClasseName>G3EI1</ClasseName>
    <Phone>01 07 56 83 24</Phone>
    <Email>OdessaJenkins.HakeemCooper@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>19000233</CNE>
    <LastName>Isaiah Franklin</LastName>
    <FirstName>Valentine Bernard</FirstName>
    <DateofBirth>1998-09-29</DateofBirth>
    <ClasseName>G3EI1</ClasseName>
    <Phone>03 11 46 32 15</Phone>
    <Email>IsaiahFranklin.ValentineBernard@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>19000234</CNE>
    <LastName>Marvin Wilkinson</LastName>
    <FirstName>Cassady Erickson</FirstName>
    <DateofBirth>1998-06-09</DateofBirth>
    <ClasseName>G3EI1</ClasseName>
    <Phone>02 27 42 28 63</Phone>
    <Email>MarvinWilkinson.CassadyErickson@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>19000235</CNE>
    <LastName>Jelani Ford</LastName>
    <FirstName>Yuri Wilkerson</FirstName>
    <DateofBirth>1997-05-15</DateofBirth>
    <ClasseName>G3EI1</ClasseName>
    <Phone>06 06 62 74 07</Phone>
    <Email>JelaniFord.YuriWilkerson@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>19000236</CNE>
    <LastName>Veronica Rich</LastName>
    <FirstName>Cara Kaufman</FirstName>
    <DateofBirth>1999-10-04</DateofBirth>
    <ClasseName>G3EI1</ClasseName>
    <Phone>06 39 81 37 33</Phone>
    <Email>VeronicaRich.CaraKaufman@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>19000237</CNE>
    <LastName>Vance Boyle</LastName>
    <FirstName>Noelani Bernard</FirstName>
    <DateofBirth>2002-02-23</DateofBirth>
    <ClasseName>G3EI1</ClasseName>
    <Phone>06 83 63 57 28</Phone>
    <Email>VanceBoyle.NoelaniBernard@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>19000238</CNE>
    <LastName>Shad Wilson</LastName>
    <FirstName>Holmes Baird</FirstName>
    <DateofBirth>1997-11-04</DateofBirth>
    <ClasseName>G3EI1</ClasseName>
    <Phone>09 62 23 55 06</Phone>
    <Email>ShadWilson.HolmesBaird@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>19000239</CNE>
    <LastName>Macy Holcomb</LastName>
    <FirstName>Nasim Weaver</FirstName>
    <DateofBirth>1999-12-28</DateofBirth>
    <ClasseName>G3EI1</ClasseName>
    <Phone>08 45 61 63 45</Phone>
    <Email>MacyHolcomb.NasimWeaver@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>19000240</CNE>
    <LastName>Cody Atkins</LastName>
    <FirstName>Xenos Stout</FirstName>
    <DateofBirth>1999-09-10</DateofBirth>
    <ClasseName>G3EI1</ClasseName>
    <Phone>04 23 38 82 33</Phone>
    <Email>CodyAtkins.XenosStout@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>19000241</CNE>
    <LastName>Devin Mack</LastName>
    <FirstName>MacKenzie Chase</FirstName>
    <DateofBirth>1999-10-14</DateofBirth>
    <ClasseName>G3EI1</ClasseName>
    <Phone>01 46 58 73 59</Phone>
    <Email>DevinMack.MacKenzieChase@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>19000242</CNE>
    <LastName>Julian Ashley</LastName>
    <FirstName>Priscilla Booth</FirstName>
    <DateofBirth>1997-03-02</DateofBirth>
    <ClasseName>G3EI1</ClasseName>
    <Phone>03 12 52 23 21</Phone>
    <Email>JulianAshley.PriscillaBooth@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>19000243</CNE>
    <LastName>Sigourney Cervantes</LastName>
    <FirstName>Wade Santiago</FirstName>
    <DateofBirth>2002-03-03</DateofBirth>
    <ClasseName>G3EI1</ClasseName>
    <Phone>09 28 72 46 13</Phone>
    <Email>SigourneyCervantes.WadeSantiago@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>19000244</CNE>
    <LastName>Hamish Vaughn</LastName>
    <FirstName>Serina Bowers</FirstName>
    <DateofBirth>1999-09-18</DateofBirth>
    <ClasseName>G3EI1</ClasseName>
    <Phone>01 57 79 71 21</Phone>
    <Email>HamishVaughn.SerinaBowers@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>19000245</CNE>
    <LastName>Malcolm Glover</LastName>
    <FirstName>Sonya Soto</FirstName>
    <DateofBirth>1998-08-22</DateofBirth>
    <ClasseName>G3EI1</ClasseName>
    <Phone>03 36 31 50 17</Phone>
    <Email>MalcolmGlover.SonyaSoto@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>19000246</CNE>
    <LastName>Reed Wiley</LastName>
    <FirstName>Perry Lamb</FirstName>
    <DateofBirth>1998-01-19</DateofBirth>
    <ClasseName>G3EI1</ClasseName>
    <Phone>04 88 65 78 35</Phone>
    <Email>ReedWiley.PerryLamb@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>19000247</CNE>
    <LastName>Owen Wright</LastName>
    <FirstName>Imogene House</FirstName>
    <DateofBirth>2001-12-01</DateofBirth>
    <ClasseName>G3EI1</ClasseName>
    <Phone>02 54 14 42 17</Phone>
    <Email>OwenWright.ImogeneHouse@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>19000248</CNE>
    <LastName>Ali Simpson</LastName>
    <FirstName>Zephania Hudson</FirstName>
    <DateofBirth>1998-10-14</DateofBirth>
    <ClasseName>G3EI1</ClasseName>
    <Phone>05 08 87 11 58</Phone>
    <Email>AliSimpson.ZephaniaHudson@etu.uae.ac.ma</Email>
  </Student></Students>
