=== amamatou/GestionScolarite-XML/Validation_xml/Students.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
elementFormDefault="qualified">

<xs:element name="Students">
   <xs:complexType>
     <xs:sequence>
      <xs:element name="Student" maxOccurs="240" minOccurs="24">
       <xs:complexType>
        <xs:sequence>
          <xs:element name="CNE" type="xs:string"/>
          <xs:element name="LastName">
            <xs:simpleType>
              <xs:restriction base="xs:string">
                <xs:pattern value="[A-Z]([aA-zZ\s*])*"/>
              </xs:restriction>
            </xs:simpleType>
          </xs:element>
          <xs:element name="FirstName">
          <xs:simpleType>
              <xs:restriction base="xs:string">
                <xs:pattern value="[A-Z]([aA-zZ\s*])*"/>
              </xs:restriction>
            </xs:simpleType>
          </xs:element>
          <xs:element name="DateofBirth" type="xs:date"/>
          <xs:element name="ClasseName" type="xs:string"/>
          <xs:element name="Phone" type="xs:string"/>
          <xs:element name="Email" type="xs:string"/>
        </xs:sequence>
        </xs:complexType>
    </xs:element>
   </xs:sequence>
  </xs:complexType> 
  </xs:element>

  </xs:schema>

=== amamatou/GestionScolarite-XML/Fichiers_xml/Groupes/AP2_Gr1.xml
<?xml version="1.0"?>
<Students xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C://xampp/htdocs/GestionScolarite-XML/Validation_xml/Students.xsd"><Student>
    <CNE>20000001</CNE>
    <LastName>Bo Alvarado</LastName>
    <FirstName>Imelda Becker</FirstName>
    <DateofBirth>1997-03-22</DateofBirth>
    <ClasseName>AP2</ClasseName>
    <Phone>03 15 32 74 90</Phone>
    <Email>BoAlvarado.ImeldaBecker@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>20000002</CNE>
    <LastName>Lacota Gay</LastName>
    <FirstName>Cairo Hoover</FirstName>
    <DateofBirth>2000-11-08</DateofBirth>
    <ClasseName>AP2</ClasseName>
    <Phone>01 26 95 94 46</Phone>
    <Email>LacotaGay.CairoHoover@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>20000003</CNE>
    <LastName>Rudyard Guy</LastName>
    <FirstName>Lesley Mcgowan</FirstName>
    <DateofBirth>1999-06-24</DateofBirth>
    <ClasseName>AP2</ClasseName>
    <Phone>05 65 64 29 29</Phone>
    <Email>RudyardGuy.LesleyMcgowan@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>20000004</CNE>
    <LastName>Lester Finley</LastName>
    <FirstName>Herman Shields</FirstName>
    <DateofBirth>1997-04-30</DateofBirth>
    <ClasseName>AP2</ClasseName>
    <Phone>05 75 43 83 31</Phone>
    <Email>LesterFinley.HermanShields@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>20000005</CNE>
    <LastName>Eagan Delacruz</LastName>
    <FirstName>Driscoll Harrell</FirstName>
    <DateofBirth>2000-02-06</DateofBirth>
    <ClasseName>AP2</ClasseName>
    <Phone>02 52 86 98 82</Phone>
    <Email>EaganDelacruz.DriscollHarrell@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>20000006</CNE>
    <LastName>Jesse Crawford</LastName>
    <FirstName>Sierra Strickland</FirstName>
    <DateofBirth>1998-09-24</DateofBirth>
    <ClasseName>AP2</ClasseName>
    <Phone>07 58 16 14 11</Phone>
    <Email>JesseCrawford.SierraStrickland@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>20000007</CNE>
    <LastName>Vernon Sloan</LastName>
    <FirstName>Olga Holden</FirstName>
    <DateofBirth>1998-12-24</DateofBirth>
    <ClasseName>AP2</ClasseName>
    <Phone>05 87 82 74 26</Phone>
    <Email>VernonSloan.OlgaHolden@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>20000008</CNE>
    <LastName>Virginia Schultz</LastName>
    <FirstName>Brynne Sexton</FirstName>
    <DateofBirth>1998-08-22</DateofBirth>
    <ClasseName>AP2</ClasseName>
    <Phone>08 38 15 22 40</Phone>
    <Email>VirginiaSchultz.BrynneSexton@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>20000009</CNE>
    <LastName>Pearl Ortega</LastName>
    <FirstName>Laith Hancock</FirstName>
    <DateofBirth>1998-05-21</DateofBirth>
    <ClasseName>AP2</ClasseName>
    <Phone>01 27 12 14 26</Phone>
    <Email>PearlOrtega.LaithHancock@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>20000010</CNE>
    <LastName>Teegan Nash</LastName>
    <FirstName>Serena Blackwell</FirstName>
    <DateofBirth>2001-11-21</DateofBirth>
    <ClasseName>AP2</ClasseName>
    <Phone>06 03 05 13 76</Phone>
    <Email>TeeganNash.SerenaBlackwell@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>20000011</CNE>
    <LastName>John Lee</LastName>
    <FirstName>Sylvester Chase</FirstName>
    <DateofBirth>2000-03-14</DateofBirth>
    <ClasseName>AP2</ClasseName>
    <Phone>02 25 21 45 20</Phone>
    <Email>JohnLee.SylvesterChase@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>20000012</CNE>
    <LastName>Shellie Russo</LastName>
    <FirstName>Karleigh Martinez</FirstName>
    <DateofBirth>1997-08-17</DateofBirth>
    <ClasseName>AP2</ClasseName>
    <Phone>07 39 78 36 25</Phone>
    <Email>ShellieRusso.KarleighMartinez@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>20000013</CNE>
    <LastName>Roth Mcleod</LastName>
    <FirstName>Karleigh Maxwell</FirstName>
    <DateofBirth>2002-06-26</DateofBirth>
    <ClasseName>AP2</ClasseName>
    <Phone>06 24 13 56 54</Phone>
    <Email>RothMcleod.KarleighMaxwell@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>20000014</CNE>
    <LastName>Amir Perez</LastName>
    <FirstName>Emery Ayers</FirstName>
    <DateofBirth>1997-12-20</DateofBirth>
    <ClasseName>AP2</ClasseName>
    <Phone>06 78 05 04 12</Phone>
    <Email>AmirPerez.EmeryAyers@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>20000015</CNE>
    <LastName>Dacey Todd</LastName>
    <FirstName>Madaline Jacobson</FirstName>
    <DateofBirth>1999-10-08</DateofBirth>
    <ClasseName>AP2</ClasseName>
    <Phone>01 13 44 31 59</Phone>
    <Email>DaceyTodd.MadalineJacobson@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>20000016</CNE>
    <LastName>Charles Haley</LastName>
    <FirstName>Eve Daniel</FirstName>
    <DateofBirth>1999-03-05</DateofBirth>
    <ClasseName>AP2</ClasseName>
    <Phone>01 73 15 92 42</Phone>
    <Email>CharlesHaley.EveDaniel@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>20000017</CNE>
    <LastName>Adena Cooper</LastName>
    <FirstName>Leilani Orr</FirstName>
    <DateofBirth>1997-10-28</DateofBirth>
    <ClasseName>AP2</ClasseName>
    <Phone>07 24 00 58 65</Phone>
    <Email>AdenaCooper.LeilaniOrr@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>20000018</CNE>
    <LastName>Maite Sandoval</LastName>
    <FirstName>Alfonso Guerra</FirstName>
    <DateofBirth>1998-07-24</DateofBirth>
    <ClasseName>AP2</ClasseName>
    <Phone>04 61 22 53 07</Phone>
    <Email>MaiteSandoval.AlfonsoGuerra@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>20000019</CNE>
    <LastName>Rashad Rasmussen</LastName>
    <FirstName>Raven Fowler</FirstName>
    <DateofBirth>2000-07-31</DateofBirth>
    <ClasseName>AP2</ClasseName>
    <Phone>04 85 14 26 10</Phone>
    <Email>RashadRasmussen.RavenFowler@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>20000020</CNE>
    <LastName>Oprah Lee</LastName>
    <FirstName>Ezekiel Berry</FirstName>
    <DateofBirth>1997-05-22</DateofBirth>
    <ClasseName>AP2</ClasseName>
    <Phone>06 95 03 36 81</Phone>
    <Email>OprahLee.EzekielBerry@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>20000021</CNE>
    <LastName>Channing Suarez</LastName>
    <FirstName>Caldwell Melendez</FirstName>
    <DateofBirth>2001-05-20</DateofBirth>
    <ClasseName>AP2</ClasseName>
    <Phone>05 45 42 95 96</Phone>
    <Email>ChanningSuarez.CaldwellMelendez@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>20000022</CNE>
    <LastName>Erasmus Battle</LastName>
    <FirstName>Eliana Chavez</FirstName>
    <DateofBirth>1999-01-22</DateofBirth>
    <ClasseName>AP2</ClasseName>
    <Phone>07 58 68 84 05</Phone>
    <Email>ErasmusBattle.ElianaChavez@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>20000023</CNE>
    <LastName>Sacha Meadows</LastName>
    <FirstName>Aaron Horn</FirstName>
    <DateofBirth>2000-11-24</DateofBirth>
    <ClasseName>AP2</ClasseName>
    <Phone>07 66 96 72 78</Phone>
    <Email>SachaMeadows.AaronHorn@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>20000024</CNE>
    <LastName>Wing Stephenson</LastName>
    <FirstName>Sierra Osborn</FirstName>
    <DateofBirth>2001-06-10</DateofBirth>
    <ClasseName>AP2</ClasseName>
    <Phone>02 76 46 33 35</Phone>
    <Email>WingStephenson.SierraOsborn@etu.uae.ac.ma</Email>
  </Student></Students>

=== amamatou/GestionScolarite-XML/Fichiers_xml/Groupes/GINF2_Gr3.xml
<?xml version="1.0"?>
<Students xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C://xampp/htdocs/GestionScolarite-XML/Validation_xml/Students.xsd"><Student>
    <CNE>18000199</CNE>
    <LastName>Sana</LastName>
    <FirstName>Lookman Ossam</FirstName>
    <DateofBirth>1999-04-24</DateofBirth>
    <ClasseName>Ginf2</ClasseName>
    <Phone>04 42 16 90 64</Phone>
    <Email>LookmanOssam.Taali@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>18000200</CNE>
    <LastName>Taali</LastName>
    <FirstName>Houda</FirstName>
    <DateofBirth>2000-11-26</DateofBirth>
    <ClasseName>Ginf2</ClasseName>
    <Phone>05 49 24 53 91</Phone>
    <Email>Houda.@etu.uae.ac.ma</Email>
  </Student></Students>

=== amamatou/GestionScolarite-XML/Fichiers_xml/Groupes/G3EI3_Gr3.xml
<?xml version="1.0"?>
<Students xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C://xampp/htdocs/GestionScolarite-XML/Validation_xml/Students.xsd"><Student>
    <CNE>17000249</CNE>
    <LastName>Arsenio Stein</LastName>
    <FirstName>Zeph Sanford</FirstName>
    <DateofBirth>1998-06-21</DateofBirth>
    <ClasseName>G3EI3</ClasseName>
    <Phone>06 07 05 11 83</Phone>
    <Email>ArsenioStein.ZephSanford@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>17000250</CNE>
    <LastName>Sydnee Vaughan</LastName>
    <FirstName>Zephania Sampson</FirstName>
    <DateofBirth>2000-08-27</DateofBirth>
    <ClasseName>G3EI3</ClasseName>
    <Phone>08 88 32 71 78</Phone>
    <Email>SydneeVaughan.ZephaniaSampson@etu.uae.ac.ma</Email>
  </Student></Students>

=== amamatou/GestionScolarite-XML/Fichiers_xml/Groupes/G3EI3_Gr2.xml
<?xml version="1.0"?>
<Students xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C://xampp/htdocs/GestionScolarite-XML/Validation_xml/Students.xsd"><Student>
    <CNE>17000225</CNE>
    <LastName>Sebastian Henson</LastName>
    <FirstName>Levi Bright</FirstName>
    <DateofBirth>1999-12-22</DateofBirth>
    <ClasseName>G3EI3</ClasseName>
    <Phone>02 28 67 28 57</Phone>
    <Email>SebastianHenson.LeviBright@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>17000226</CNE>
    <LastName>Charles Frost</LastName>
    <FirstName>Demetrius Hines</FirstName>
    <DateofBirth>1999-12-20</DateofBirth>
    <ClasseName>G3EI3</ClasseName>
    <Phone>04 16 91 41 32</Phone>
    <Email>CharlesFrost.DemetriusHines@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>17000227</CNE>
    <LastName>Cade Fisher</LastName>
    <FirstName>Calvin Armstrong</FirstName>
    <DateofBirth>2001-06-19</DateofBirth>
    <ClasseName>G3EI3</ClasseName>
    <Phone>04 20 85 06 36</Phone>
    <Email>CadeFisher.CalvinArmstrong@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>17000228</CNE>
    <LastName>Hector Lancaster</LastName>
    <FirstName>Ahmed Stafford</FirstName>
    <DateofBirth>1999-10-03</DateofBirth>
    <ClasseName>G3EI3</ClasseName>
    <Phone>04 88 63 66 85</Phone>
    <Email>HectorLancaster.AhmedStafford@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>17000229</CNE>
    <LastName>Xenos Klein</LastName>
    <FirstName>Clark Becker</FirstName>
    <DateofBirth>1997-02-07</DateofBirth>
    <ClasseName>G3EI3</ClasseName>
    <Phone>07 47 32 25 42</Phone>
    <Email>XenosKlein.ClarkBecker@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>17000230</CNE>
    <LastName>Chiquita Castillo</LastName>
    <FirstName>Dennis Hopkins</FirstName>
    <DateofBirth>1998-11-04</DateofBirth>
    <ClasseName>G3EI3</ClasseName>
    <Phone>05 32 62 71 34</Phone>
    <Email>ChiquitaCastillo.DennisHopkins@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>17000231</CNE>
    <LastName>Sigourney Stafford</LastName>
    <FirstName>Wallace Burton</FirstName>
    <DateofBirth>2002-10-25</DateofBirth>
    <ClasseName>G3EI3</ClasseName>
    <Phone>03 13 27 11 90</Phone>
    <Email>SigourneyStafford.WallaceBurton@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>17000232</CNE>
    <LastName>Wylie Bryan</LastName>
    <FirstName>Dacey Rios</FirstName>
    <DateofBirth>2000-04-14</DateofBirth>
    <ClasseName>G3EI3</ClasseName>
    <Phone>08 19 40 67 76</Phone>
    <Email>WylieBryan.DaceyRios@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>17000233</CNE>
    <LastName>Camilla Mitchell</LastName>
    <FirstName>Elvis Moore</FirstName>
    <DateofBirth>1998-08-28</DateofBirth>
    <ClasseName>G3EI3</ClasseName>
    <Phone>08 86 82 04 56</Phone>
    <Email>CamillaMitchell.ElvisMoore@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>17000234</CNE>
    <LastName>Raya Cantrell</LastName>
    <FirstName>Yoko Rosales</FirstName>
    <DateofBirth>1998-08-27</DateofBirth>
    <ClasseName>G3EI3</ClasseName>
    <Phone>02 33 59 30 47</Phone>
    <Email>RayaCantrell.YokoRosales@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>17000235</CNE>
    <LastName>Rhona Holder</LastName>
    <FirstName>Davis Benton</FirstName>
    <DateofBirth>1999-05-13</DateofBirth>
    <ClasseName>G3EI3</ClasseName>
    <Phone>02 62 53 44 56</Phone>
    <Email>RhonaHolder.DavisBenton@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>17000236</CNE>
    <LastName>Barbara Mercado</LastName>
    <FirstName>Laura Bonner</FirstName>
    <DateofBirth>1999-01-01</DateofBirth>
    <ClasseName>G3EI3</ClasseName>
    <Phone>03 24 48 21 52</Phone>
    <Email>BarbaraMercado.LauraBonner@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>17000237</CNE>
    <LastName>Jakeem Mcmillan</LastName>
    <FirstName>Bert Arnold</FirstName>
    <DateofBirth>1999-12-06</DateofBirth>
    <ClasseName>G3EI3</ClasseName>
    <Phone>06 45 88 02 62</Phone>
    <Email>JakeemMcmillan.BertArnold@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>17000238</CNE>
    <LastName>Kiona Santana</LastName>
    <FirstName>Branden Carrillo</FirstName>
    <DateofBirth>2000-10-20</DateofBirth>
    <ClasseName>G3EI3</ClasseName>
    <Phone>08 20 56 88 28</Phone>
    <Email>KionaSantana.BrandenCarrillo@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>17000239</CNE>
    <LastName>Paul Austin</LastName>
    <FirstName>Colin Wilkinson</FirstName>
    <DateofBirth>1999-11-14</DateofBirth>
    <ClasseName>G3EI3</ClasseName>
    <Phone>09 15 42 36 74</Phone>
    <Email>PaulAustin.ColinWilkinson@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>17000240</CNE>
    <LastName>Leandra Jarvis</LastName>
    <FirstName>Barclay Thompson</FirstName>
    <DateofBirth>1997-02-10</DateofBirth>
    <ClasseName>G3EI3</ClasseName>
    <Phone>07 45 64 43 28</Phone>
    <Email>LeandraJarvis.BarclayThompson@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>17000241</CNE>
    <LastName>Cally Wheeler</LastName>
    <FirstName>Steven Bush</FirstName>
    <DateofBirth>2000-01-20</DateofBirth>
    <ClasseName>G3EI3</ClasseName>
    <Phone>05 35 74 90 86</Phone>
    <Email>CallyWheeler.StevenBush@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>17000242</CNE>
    <LastName>Fleur Powers</LastName>
    <FirstName>Regan Norman</FirstName>
    <DateofBirth>2001-03-14</DateofBirth>
    <ClasseName>G3EI3</ClasseName>
    <Phone>01 49 17 84 68</Phone>
    <Email>FleurPowers.ReganNorman@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>17000243</CNE>
    <LastName>Zoe Sanford</LastName>
    <FirstName>Indira Branch</FirstName>
    <DateofBirth>1997-08-01</DateofBirth>
    <ClasseName>G3EI3</ClasseName>
    <Phone>05 72 13 47 54</Phone>
    <Email>ZoeSanford.IndiraBranch@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>17000244</CNE>
    <LastName>Marshall Petersen</LastName>
    <FirstName>Sylvester Vaughn</FirstName>
    <DateofBirth>1998-05-21</DateofBirth>
    <ClasseName>G3EI3</ClasseName>
    <Phone>01 61 38 69 95</Phone>
    <Email>MarshallPetersen.SylvesterVaughn@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>17000245</CNE>
    <LastName>Adara Hoffman</LastName>
    <FirstName>Jeanette Bauer</FirstName>
    <DateofBirth>2001-04-06</DateofBirth>
    <ClasseName>G3EI3</ClasseName>
    <Phone>06 05 21 87 54</Phone>
    <Email>AdaraHoffman.JeanetteBauer@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>17000246</CNE>
    <LastName>Mohammad Allen</LastName>
    <FirstName>Camilla Medina</FirstName>
    <DateofBirth>2000-12-15</DateofBirth>
    <ClasseName>G3EI3</ClasseName>
    <Phone>03 76 67 71 54</Phone>
    <Email>MohammadAllen.CamillaMedina@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>17000247</CNE>
    <LastName>Jason Day</LastName>
    <FirstName>Nadine Moreno</FirstName>
    <DateofBirth>2000-12-10</DateofBirth>
    <ClasseName>G3EI3</ClasseName>
    <Phone>09 79 06 56 51</Phone>
    <Email>JasonDay.NadineMoreno@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>17000248</CNE>
    <LastName>Jamal Trujillo</LastName>
    <FirstName>Leo Jenkins</FirstName>
    <DateofBirth>2001-02-23</DateofBirth>
    <ClasseName>G3EI3</ClasseName>
    <Phone>09 72 58 01 26</Phone>
    <Email>JamalTrujillo.LeoJenkins@etu.uae.ac.ma</Email>
  </Student></Students>

=== amamatou/GestionScolarite-XML/Fichiers_xml/Groupes/GIL3_Gr2.xml
<?xml version="1.0"?>
<Students xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C://xampp/htdocs/GestionScolarite-XML/Validation_xml/Students.xsd"><Student>
    <CNE>17000075</CNE>
    <LastName>Isabella Henderson</LastName>
    <FirstName>Keith Hammond</FirstName>
    <DateofBirth>2000-01-30</DateofBirth>
    <ClasseName>GIL3</ClasseName>
    <Phone>07 64 49 32 86</Phone>
    <Email>IsabellaHenderson.KeithHammond@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>17000076</CNE>
    <LastName>Summer Vasquez</LastName>
    <FirstName>Calista Wolfe</FirstName>
    <DateofBirth>2002-10-29</DateofBirth>
    <ClasseName>GIL3</ClasseName>
    <Phone>04 64 12 57 71</Phone>
    <Email>SummerVasquez.CalistaWolfe@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>17000077</CNE>
    <LastName>Naomi Little</LastName>
    <FirstName>Stuart Rogers</FirstName>
    <DateofBirth>2000-09-05</DateofBirth>
    <ClasseName>GIL3</ClasseName>
    <Phone>06 22 83 28 72</Phone>
    <Email>NaomiLittle.StuartRogers@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>17000078</CNE>
    <LastName>Melanie Crawford</LastName>
    <FirstName>Solomon Harrison</FirstName>
    <DateofBirth>1999-02-25</DateofBirth>
    <ClasseName>GIL3</ClasseName>
    <Phone>09 76 30 78 47</Phone>
    <Email>MelanieCrawford.SolomonHarrison@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>17000079</CNE>
    <LastName>Cullen Hudson</LastName>
    <FirstName>TaShya Klein</FirstName>
    <DateofBirth>1999-11-04</DateofBirth>
    <ClasseName>GIL3</ClasseName>
    <Phone>08 58 06 90 55</Phone>
    <Email>CullenHudson.TaShyaKlein@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>17000080</CNE>
    <LastName>Reese Palmer</LastName>
    <FirstName>Sade Duffy</FirstName>
    <DateofBirth>2002-06-09</DateofBirth>
    <ClasseName>GIL3</ClasseName>
    <Phone>02 46 31 40 07</Phone>
    <Email>ReesePalmer.SadeDuffy@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>17000081</CNE>
    <LastName>Leila Boyer</LastName>
    <FirstName>Honorato Tillman</FirstName>
    <DateofBirth>1998-04-20</DateofBirth>
    <ClasseName>GIL3</ClasseName>
    <Phone>04 86 51 33 58</Phone>
    <Email>LeilaBoyer.HonoratoTillman@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>17000082</CNE>
    <LastName>Portia Byers</LastName>
    <FirstName>Tyler Middleton</FirstName>
    <DateofBirth>1997-09-10</DateofBirth>
    <ClasseName>GIL3</ClasseName>
    <Phone>07 41 61 49 83</Phone>
    <Email>PortiaByers.TylerMiddleton@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>17000083</CNE>
    <LastName>Ursula Moss</LastName>
    <FirstName>Lance Flynn</FirstName>
    <DateofBirth>1999-07-13</DateofBirth>
    <ClasseName>GIL3</ClasseName>
    <Phone>03 23 27 07 87</Phone>
    <Email>UrsulaMoss.LanceFlynn@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>17000084</CNE>
    <LastName>Silas Mckay</LastName>
    <FirstName>Ian Brown</FirstName>
    <DateofBirth>2002-12-01</DateofBirth>
    <ClasseName>GIL3</ClasseName>
    <Phone>08 63 63 50 03</Phone>
    <Email>SilasMckay.IanBrown@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>17000085</CNE>
    <LastName>Abdul Wilkerson</LastName>
    <FirstName>Hedy Frazier</FirstName>
    <DateofBirth>1998-06-11</DateofBirth>
    <ClasseName>GIL3</ClasseName>
    <Phone>08 32 38 63 72</Phone>
    <Email>AbdulWilkerson.HedyFrazier@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>17000086</CNE>
    <LastName>Celeste Franks</LastName>
    <FirstName>Camilla Trevino</FirstName>
    <DateofBirth>2001-04-30</DateofBirth>
    <ClasseName>GIL3</ClasseName>
    <Phone>04 78 31 12 16</Phone>
    <Email>CelesteFranks.CamillaTrevino@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>17000087</CNE>
    <LastName>Carter Wheeler</LastName>
    <FirstName>Shafira Mccray</FirstName>
    <DateofBirth>1999-08-29</DateofBirth>
    <ClasseName>GIL3</ClasseName>
    <Phone>05 96 70 72 61</Phone>
    <Email>CarterWheeler.ShafiraMccray@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>17000088</CNE>
    <LastName>Philip Livingston</LastName>
    <FirstName>Maggy Terry</FirstName>
    <DateofBirth>1998-02-18</DateofBirth>
    <ClasseName>GIL3</ClasseName>
    <Phone>08 65 86 54 56</Phone>
    <Email>PhilipLivingston.MaggyTerry@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>17000089</CNE>
    <LastName>Venus Sykes</LastName>
    <FirstName>Kiara Barlow</FirstName>
    <DateofBirth>2002-05-17</DateofBirth>
    <ClasseName>GIL3</ClasseName>
    <Phone>05 23 30 40 63</Phone>
    <Email>VenusSykes.KiaraBarlow@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>17000090</CNE>
    <LastName>Griffin Davenport</LastName>
    <FirstName>Gwendolyn Randolph</FirstName>
    <DateofBirth>1998-10-15</DateofBirth>
    <ClasseName>GIL3</ClasseName>
    <Phone>02 11 39 14 01</Phone>
    <Email>GriffinDavenport.GwendolynRandolph@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>17000091</CNE>
    <LastName>Paloma Macdonald</LastName>
    <FirstName>Alfreda Lyons</FirstName>
    <DateofBirth>1998-12-21</DateofBirth>
    <ClasseName>GIL3</ClasseName>
    <Phone>03 67 70 01 26</Phone>
    <Email>PalomaMacdonald.AlfredaLyons@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>17000092</CNE>
    <LastName>Harrison Reynolds</LastName>
    <FirstName>Moana Walter</FirstName>
    <DateofBirth>2002-05-06</DateofBirth>
    <ClasseName>GIL3</ClasseName>
    <Phone>05 35 54 20 70</Phone>
    <Email>HarrisonReynolds.MoanaWalter@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>17000093</CNE>
    <LastName>Carson Mercado</LastName>
    <FirstName>Colleen Steele</FirstName>
    <DateofBirth>1997-02-21</DateofBirth>
    <ClasseName>GIL3</ClasseName>
    <Phone>08 92 26 43 20</Phone>
    <Email>CarsonMercado.ColleenSteele@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>17000094</CNE>
    <LastName>Rhonda Strong</LastName>
    <FirstName>Hasad Deleon</FirstName>
    <DateofBirth>2000-09-20</DateofBirth>
    <ClasseName>GIL3</ClasseName>
    <Phone>07 45 49 51 05</Phone>
    <Email>RhondaStrong.HasadDeleon@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>17000095</CNE>
    <LastName>Linda Huffman</LastName>
    <FirstName>Kennan Gardner</FirstName>
    <DateofBirth>2001-03-22</DateofBirth>
    <ClasseName>GIL3</ClasseName>
    <Phone>02 19 62 72 83</Phone>
    <Email>LindaHuffman.KennanGardner@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>17000096</CNE>
    <LastName>Tiger Ross</LastName>
    <FirstName>Wanda Alexander</FirstName>
    <DateofBirth>2000-09-28</DateofBirth>
    <ClasseName>GIL3</ClasseName>
    <Phone>08 80 14 61 06</Phone>
    <Email>TigerRoss.WandaAlexander@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>17000097</CNE>
    <LastName>Colt Brown</LastName>
    <FirstName>Shana Chang</FirstName>
    <DateofBirth>2002-04-25</DateofBirth>
    <ClasseName>GIL3</ClasseName>
    <Phone>07 85 11 07 97</Phone>
    <Email>ColtBrown.ShanaChang@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>17000098</CNE>
    <LastName>Ahmed House</LastName>
    <FirstName>Aristotle Gilliam</FirstName>
    <DateofBirth>1998-02-02</DateofBirth>
    <ClasseName>GIL3</ClasseName>
    <Phone>02 78 45 02 75</Phone>
    <Email>AhmedHouse.AristotleGilliam@etu.uae.ac.ma</Email>
  </Student></Students>
