=== amamatou/GestionScolarite-XML/Validation_xml/Students.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
elementFormDefault="qualified">

<xs:element name="Students">
   <xs:complexType>
     <xs:sequence>
      <xs:element name="Student" maxOccurs="240" minOccurs="24">
       <xs:complexType>
        <xs:sequence>
          <xs:element name="CNE" type="xs:string"/>
          <xs:element name="LastName">
            <xs:simpleType>
              <xs:restriction base="xs:string">
                <xs:pattern value="[A-Z]([aA-zZ\s*])*"/>
              </xs:restriction>
            </xs:simpleType>
          </xs:element>
          <xs:element name="FirstName">
          <xs:simpleType>
              <xs:restriction base="xs:string">
                <xs:pattern value="[A-Z]([aA-zZ\s*])*"/>
              </xs:restriction>
            </xs:simpleType>
          </xs:element>
          <xs:element name="DateofBirth" type="xs:date"/>
          <xs:element name="ClasseName" type="xs:string"/>
          <xs:element name="Phone" type="xs:string"/>
          <xs:element name="Email" type="xs:string"/>
        </xs:sequence>
        </xs:complexType>
    </xs:element>
   </xs:sequence>
  </xs:complexType> 
  </xs:element>

  </xs:schema>

=== amamatou/GestionScolarite-XML/Fichiers_xml/Groupes/AP2_Gr2.xml
<?xml version="1.0"?>
<Students xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C://xampp/htdocs/GestionScolarite-XML/Validation_xml/Students.xsd"><Student>
    <CNE>20000025</CNE>
    <LastName>Tucker Combs</LastName>
    <FirstName>Moana Lyons</FirstName>
    <DateofBirth>1998-07-24</DateofBirth>
    <ClasseName>AP2</ClasseName>
    <Phone>07 82 52 89 74</Phone>
    <Email>TuckerCombs.MoanaLyons@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>20000026</CNE>
    <LastName>Tyrone Baker</LastName>
    <FirstName>Jenna Cunningham</FirstName>
    <DateofBirth>1998-09-08</DateofBirth>
    <ClasseName>AP2</ClasseName>
    <Phone>04 76 77 34 01</Phone>
    <Email>TyroneBaker.JennaCunningham@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>20000027</CNE>
    <LastName>Lucy Barnes</LastName>
    <FirstName>Ryder Molina</FirstName>
    <DateofBirth>1997-05-15</DateofBirth>
    <ClasseName>AP2</ClasseName>
    <Phone>02 43 95 14 17</Phone>
    <Email>LucyBarnes.RyderMolina@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>20000028</CNE>
    <LastName>August Mayer</LastName>
    <FirstName>Leonard Moss</FirstName>
    <DateofBirth>2002-05-27</DateofBirth>
    <ClasseName>AP2</ClasseName>
    <Phone>03 71 81 23 37</Phone>
    <Email>AugustMayer.LeonardMoss@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>20000029</CNE>
    <LastName>Vaughan Ellis</LastName>
    <FirstName>Salvador Holden</FirstName>
    <DateofBirth>1997-04-17</DateofBirth>
    <ClasseName>AP2</ClasseName>
    <Phone>03 76 77 77 64</Phone>
    <Email>VaughanEllis.SalvadorHolden@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>20000030</CNE>
    <LastName>Desirae Park</LastName>
    <FirstName>Lance Farrell</FirstName>
    <DateofBirth>1997-09-09</DateofBirth>
    <ClasseName>AP2</ClasseName>
    <Phone>08 32 17 61 87</Phone>
    <Email>DesiraePark.LanceFarrell@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>20000031</CNE>
    <LastName>Kitra Blanchard</LastName>
    <FirstName>Bevis Whitfield</FirstName>
    <DateofBirth>2002-12-15</DateofBirth>
    <ClasseName>AP2</ClasseName>
    <Phone>03 29 75 12 06</Phone>
    <Email>KitraBlanchard.BevisWhitfield@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>20000032</CNE>
    <LastName>Ursula Hudson</LastName>
    <FirstName>Adria Wilcox</FirstName>
    <DateofBirth>1998-03-01</DateofBirth>
    <ClasseName>AP2</ClasseName>
    <Phone>03 64 87 86 88</Phone>
    <Email>UrsulaHudson.AdriaWilcox@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>20000033</CNE>
    <LastName>Hasad Foreman</LastName>
    <FirstName>Randall Nixon</FirstName>
    <DateofBirth>2000-03-25</DateofBirth>
    <ClasseName>AP2</ClasseName>
    <Phone>05 88 13 78 11</Phone>
    <Email>HasadForeman.RandallNixon@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>20000034</CNE>
    <LastName>Owen Cannon</LastName>
    <FirstName>Graiden Myers</FirstName>
    <DateofBirth>1999-05-25</DateofBirth>
    <ClasseName>AP2</ClasseName>
    <Phone>09 34 80 13 79</Phone>
    <Email>OwenCannon.GraidenMyers@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>20000035</CNE>
    <LastName>Cyrus Spencer</LastName>
    <FirstName>Lucas Calderon</FirstName>
    <DateofBirth>2000-03-28</DateofBirth>
    <ClasseName>AP2</ClasseName>
    <Phone>05 57 98 59 34</Phone>
    <Email>CyrusSpencer.LucasCalderon@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>20000036</CNE>
    <LastName>Kimberley Valencia</LastName>
    <FirstName>Jade Murray</FirstName>
    <DateofBirth>2002-07-04</DateofBirth>
    <ClasseName>AP2</ClasseName>
    <Phone>06 81 03 96 43</Phone>
    <Email>KimberleyValencia.JadeMurray@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>20000037</CNE>
    <LastName>Risa Webster</LastName>
    <FirstName>Hasad Church</FirstName>
    <DateofBirth>2000-07-17</DateofBirth>
    <ClasseName>AP2</ClasseName>
    <Phone>01 06 38 96 54</Phone>
    <Email>RisaWebster.HasadChurch@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>20000038</CNE>
    <LastName>Jemima Knight</LastName>
    <FirstName>Gabriel Walsh</FirstName>
    <DateofBirth>1997-05-19</DateofBirth>
    <ClasseName>AP2</ClasseName>
    <Phone>08 34 41 55 84</Phone>
    <Email>JemimaKnight.GabrielWalsh@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>20000039</CNE>
    <LastName>Carlos Gill</LastName>
    <FirstName>Octavia Marquez</FirstName>
    <DateofBirth>2001-10-03</DateofBirth>
    <ClasseName>AP2</ClasseName>
    <Phone>01 20 13 12 51</Phone>
    <Email>CarlosGill.OctaviaMarquez@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>20000040</CNE>
    <LastName>Denise Sanchez</LastName>
    <FirstName>Minerva Obrien</FirstName>
    <DateofBirth>1998-07-14</DateofBirth>
    <ClasseName>AP2</ClasseName>
    <Phone>08 82 93 64 31</Phone>
    <Email>DeniseSanchez.MinervaObrien@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>20000041</CNE>
    <LastName>Tamara Wong</LastName>
    <FirstName>Zane Booth</FirstName>
    <DateofBirth>1998-10-14</DateofBirth>
    <ClasseName>AP2</ClasseName>
    <Phone>05 14 18 59 44</Phone>
    <Email>TamaraWong.ZaneBooth@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>20000042</CNE>
    <LastName>Medge Keller</LastName>
    <FirstName>Carl Hayes</FirstName>
    <DateofBirth>1998-10-07</DateofBirth>
    <ClasseName>AP2</ClasseName>
    <Phone>01 80 25 68 69</Phone>
    <Email>MedgeKeller.CarlHayes@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>20000043</CNE>
    <LastName>Amery Foley</LastName>
    <FirstName>Acton Sweet</FirstName>
    <DateofBirth>2000-03-12</DateofBirth>
    <ClasseName>AP2</ClasseName>
    <Phone>01 64 39 63 43</Phone>
    <Email>AmeryFoley.ActonSweet@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>20000044</CNE>
    <LastName>Tiger Solis</LastName>
    <FirstName>Cameron Clay</FirstName>
    <DateofBirth>1997-06-19</DateofBirth>
    <ClasseName>AP2</ClasseName>
    <Phone>03 86 38 75 91</Phone>
    <Email>TigerSolis.CameronClay@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>20000045</CNE>
    <LastName>Colette Hinton</LastName>
    <FirstName>Chandler Spears</FirstName>
    <DateofBirth>2001-02-22</DateofBirth>
    <ClasseName>AP2</ClasseName>
    <Phone>04 29 59 13 16</Phone>
    <Email>ColetteHinton.ChandlerSpears@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>20000046</CNE>
    <LastName>Emery Cummings</LastName>
    <FirstName>Constance Salinas</FirstName>
    <DateofBirth>1999-03-04</DateofBirth>
    <ClasseName>AP2</ClasseName>
    <Phone>05 47 07 42 68</Phone>
    <Email>EmeryCummings.ConstanceSalinas@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>20000047</CNE>
    <LastName>Dale Mccray</LastName>
    <FirstName>Caryn Riley</FirstName>
    <DateofBirth>2000-07-15</DateofBirth>
    <ClasseName>AP2</ClasseName>
    <Phone>05 56 88 68 31</Phone>
    <Email>DaleMccray.CarynRiley@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>20000048</CNE>
    <LastName>Ferris Wilkerson</LastName>
    <FirstName>Aline Aguirre</FirstName>
    <DateofBirth>1998-04-17</DateofBirth>
    <ClasseName>AP2</ClasseName>
    <Phone>07 41 88 10 39</Phone>
    <Email>FerrisWilkerson.AlineAguirre@etu.uae.ac.ma</Email>
  </Student></Students>

=== amamatou/GestionScolarite-XML/Fichiers_xml/Groupes/GSTR3_Gr2.xml
<?xml version="1.0"?>
<Students xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C://xampp/htdocs/GestionScolarite-XML/Validation_xml/Students.xsd"><Student>
    <CNE>17000025</CNE>
    <LastName>Chase</LastName>
    <FirstName>Rana Price</FirstName>
    <DateofBirth>2000-01-20</DateofBirth>
    <ClasseName>Gstr3</ClasseName>
    <Phone>05 91 11 34 93</Phone>
    <Email>Chase.RanaPrice@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>17000026</CNE>
    <LastName>Georgia</LastName>
    <FirstName>Madison Moody</FirstName>
    <DateofBirth>2004-05-17</DateofBirth>
    <ClasseName>Gstr3</ClasseName>
    <Phone>02 51 86 58 26</Phone>
    <Email>Georgia.MadisonMoody@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>17000027</CNE>
    <LastName>Dorian</LastName>
    <FirstName>Adele Charles</FirstName>
    <DateofBirth>2005-06-27</DateofBirth>
    <ClasseName>Gstr3</ClasseName>
    <Phone>06 63 49 75 16</Phone>
    <Email>Dorian.AdeleCharles@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>17000028</CNE>
    <LastName>Marsden</LastName>
    <FirstName>Fuller Holt</FirstName>
    <DateofBirth>2002-09-06</DateofBirth>
    <ClasseName>Gstr3</ClasseName>
    <Phone>08 53 17 66 20</Phone>
    <Email>Marsden.FullerHolt@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>17000029</CNE>
    <LastName>Laith</LastName>
    <FirstName>Lev Bruce</FirstName>
    <DateofBirth>2008-03-14</DateofBirth>
    <ClasseName>Gstr3</ClasseName>
    <Phone>03 30 71 23 76</Phone>
    <Email>Laith.LevBruce@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>17000030</CNE>
    <LastName>Grace</LastName>
    <FirstName>Myra Trujillo</FirstName>
    <DateofBirth>2009-07-04</DateofBirth>
    <ClasseName>Gstr3</ClasseName>
    <Phone>07 56 43 07 24</Phone>
    <Email>Grace.MyraTrujillo@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>17000031</CNE>
    <LastName>Urielle</LastName>
    <FirstName>Isabella Roth</FirstName>
    <DateofBirth>2005-12-13</DateofBirth>
    <ClasseName>Gstr3</ClasseName>
    <Phone>07 28 67 46 12</Phone>
    <Email>Urielle.IsabellaRoth@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>17000032</CNE>
    <LastName>Jason</LastName>
    <FirstName>Magee Mcguire</FirstName>
    <DateofBirth>2003-03-04</DateofBirth>
    <ClasseName>Gstr3</ClasseName>
    <Phone>02 43 14 14 48</Phone>
    <Email>Jason.MageeMcguire@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>17000033</CNE>
    <LastName>Jameson</LastName>
    <FirstName>Jennifer Page</FirstName>
    <DateofBirth>2001-06-27</DateofBirth>
    <ClasseName>Gstr3</ClasseName>
    <Phone>08 22 16 35 81</Phone>
    <Email>Jameson.JenniferPage@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>17000034</CNE>
    <LastName>Justin</LastName>
    <FirstName>Giselle Rivera</FirstName>
    <DateofBirth>2007-11-04</DateofBirth>
    <ClasseName>Gstr3</ClasseName>
    <Phone>03 85 54 11 07</Phone>
    <Email>Justin.GiselleRivera@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>17000035</CNE>
    <LastName>Bradley</LastName>
    <FirstName>Dolan Shaw</FirstName>
    <DateofBirth>2004-02-12</DateofBirth>
    <ClasseName>Gstr3</ClasseName>
    <Phone>09 25 05 05 17</Phone>
    <Email>Bradley.DolanShaw@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>17000036</CNE>
    <LastName>Alyssa</LastName>
    <FirstName>Victor Collier</FirstName>
    <DateofBirth>2011-07-12</DateofBirth>
    <ClasseName>Gstr3</ClasseName>
    <Phone>01 87 31 56 83</Phone>
    <Email>Alyssa.VictorCollier@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>17000037</CNE>
    <LastName>Adara</LastName>
    <FirstName>Haley Lawson</FirstName>
    <DateofBirth>2000-11-24</DateofBirth>
    <ClasseName>Gstr3</ClasseName>
    <Phone>09 42 51 53 48</Phone>
    <Email>Adara.HaleyLawson@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>17000038</CNE>
    <LastName>Sandra</LastName>
    <FirstName>Patience Bates</FirstName>
    <DateofBirth>2003-02-02</DateofBirth>
    <ClasseName>Gstr3</ClasseName>
    <Phone>08 13 14 91 04</Phone>
    <Email>Sandra.PatienceBates@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>17000039</CNE>
    <LastName>Byron</LastName>
    <FirstName>Alden Kinney</FirstName>
    <DateofBirth>2004-11-09</DateofBirth>
    <ClasseName>Gstr3</ClasseName>
    <Phone>01 00 72 17 24</Phone>
    <Email>Byron.AldenKinney@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>17000040</CNE>
    <LastName>Colleen</LastName>
    <FirstName>Harrison Richards</FirstName>
    <DateofBirth>2003-10-12</DateofBirth>
    <ClasseName>Gstr3</ClasseName>
    <Phone>03 43 17 55 86</Phone>
    <Email>Colleen.HarrisonRichards@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>17000041</CNE>
    <LastName>Beverly</LastName>
    <FirstName>Melinda ONeill</FirstName>
    <DateofBirth>2004-09-14</DateofBirth>
    <ClasseName>Gstr3</ClasseName>
    <Phone>08 34 34 57 21</Phone>
    <Email>Beverly.MelindaONeill@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>17000042</CNE>
    <LastName>Oren</LastName>
    <FirstName>Zeph Lyons</FirstName>
    <DateofBirth>2006-09-19</DateofBirth>
    <ClasseName>Gstr3</ClasseName>
    <Phone>05 20 71 26 74</Phone>
    <Email>Oren.ZephLyons@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>17000043</CNE>
    <LastName>Leo</LastName>
    <FirstName>Quinn Nixon</FirstName>
    <DateofBirth>2002-12-21</DateofBirth>
    <ClasseName>Gstr3</ClasseName>
    <Phone>07 63 33 93 03</Phone>
    <Email>Leo.QuinnNixon@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>17000044</CNE>
    <LastName>Samson</LastName>
    <FirstName>Wendy Skinner</FirstName>
    <DateofBirth>2006-03-09</DateofBirth>
    <ClasseName>Gstr3</ClasseName>
    <Phone>07 85 29 48 16</Phone>
    <Email>Samson.WendySkinner@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>17000045</CNE>
    <LastName>Dawn</LastName>
    <FirstName>Reagan Morrison</FirstName>
    <DateofBirth>2004-04-17</DateofBirth>
    <ClasseName>Gstr3</ClasseName>
    <Phone>06 57 32 68 14</Phone>
    <Email>Dawn.ReaganMorrison@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>17000046</CNE>
    <LastName>Rhoda</LastName>
    <FirstName>Amery Guzman</FirstName>
    <DateofBirth>2005-10-15</DateofBirth>
    <ClasseName>Gstr3</ClasseName>
    <Phone>01 83 42 33 12</Phone>
    <Email>Rhoda.AmeryGuzman@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>17000047</CNE>
    <LastName>Gary</LastName>
    <FirstName>Armand Guerrero</FirstName>
    <DateofBirth>2002-03-19</DateofBirth>
    <ClasseName>Gstr3</ClasseName>
    <Phone>04 75 43 31 77</Phone>
    <Email>Gary.ArmandGuerrero@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>17000048</CNE>
    <LastName>Calista</LastName>
    <FirstName>Ivan Gill</FirstName>
    <DateofBirth>2004-01-11</DateofBirth>
    <ClasseName>Gstr3</ClasseName>
    <Phone>06 34 64 68 80</Phone>
    <Email>Calista.IvanGill@etu.uae.ac.ma</Email>
  </Student></Students>

=== amamatou/GestionScolarite-XML/Fichiers_xml/Groupes/AP2_Gr3.xml
<?xml version="1.0"?>
<Students xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C://xampp/htdocs/GestionScolarite-XML/Validation_xml/Students.xsd"><Student>
    <CNE>20000049</CNE>
    <LastName>Jenna Mcmahon</LastName>
    <FirstName>Velma Baird</FirstName>
    <DateofBirth>1999-12-18</DateofBirth>
    <ClasseName>AP2</ClasseName>
    <Phone>07 28 54 57 94</Phone>
    <Email>JennaMcmahon.VelmaBaird@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>20000050</CNE>
    <LastName>Kylee Maddox</LastName>
    <FirstName>Octavius Holloway</FirstName>
    <DateofBirth>2002-11-03</DateofBirth>
    <ClasseName>AP2</ClasseName>
    <Phone>07 25 84 88 37</Phone>
    <Email>KyleeMaddox.OctaviusHolloway@etu.uae.ac.ma</Email>
  </Student></Students>

=== amamatou/GestionScolarite-XML/Fichiers_xml/Groupes/GSEA2_Gr2.xml
<?xml version="1.0"?>
<Students xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C://xampp/htdocs/GestionScolarite-XML/Validation_xml/Students.xsd"><Student>
    <CNE>18000125</CNE>
    <LastName>Maya</LastName>
    <FirstName>Fitzgerald Colon</FirstName>
    <DateofBirth>2004-09-05</DateofBirth>
    <ClasseName>Gsea2</ClasseName>
    <Phone>07 32 71 65 42</Phone>
    <Email>Maya.FitzgeraldColon@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>18000126</CNE>
    <LastName>Hayden</LastName>
    <FirstName>Anthony Booth</FirstName>
    <DateofBirth>2010-04-02</DateofBirth>
    <ClasseName>Gsea2</ClasseName>
    <Phone>03 63 92 54 23</Phone>
    <Email>Hayden.AnthonyBooth@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>18000127</CNE>
    <LastName>Lucas</LastName>
    <FirstName>Cain Nicholson</FirstName>
    <DateofBirth>2000-05-22</DateofBirth>
    <ClasseName>Gsea2</ClasseName>
    <Phone>02 26 84 35 45</Phone>
    <Email>Lucas.CainNicholson@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>18000128</CNE>
    <LastName>Maryam</LastName>
    <FirstName>Maya Buchanan</FirstName>
    <DateofBirth>2003-09-28</DateofBirth>
    <ClasseName>Gsea2</ClasseName>
    <Phone>06 80 11 68 71</Phone>
    <Email>Maryam.MayaBuchanan@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>18000129</CNE>
    <LastName>Tamara</LastName>
    <FirstName>Leigh Schwartz</FirstName>
    <DateofBirth>2001-04-27</DateofBirth>
    <ClasseName>Gsea2</ClasseName>
    <Phone>09 09 15 87 01</Phone>
    <Email>Tamara.LeighSchwartz@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>18000130</CNE>
    <LastName>Aurelia</LastName>
    <FirstName>Nicole Mosley</FirstName>
    <DateofBirth>2000-12-22</DateofBirth>
    <ClasseName>Gsea2</ClasseName>
    <Phone>07 20 61 26 75</Phone>
    <Email>Aurelia.NicoleMosley@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>18000131</CNE>
    <LastName>Quinlan</LastName>
    <FirstName>Duncan Carver</FirstName>
    <DateofBirth>2005-07-14</DateofBirth>
    <ClasseName>Gsea2</ClasseName>
    <Phone>01 15 16 21 81</Phone>
    <Email>Quinlan.DuncanCarver@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>18000132</CNE>
    <LastName>Molly</LastName>
    <FirstName>Zenia Sutton</FirstName>
    <DateofBirth>2005-12-12</DateofBirth>
    <ClasseName>Gsea2</ClasseName>
    <Phone>07 28 35 72 75</Phone>
    <Email>Molly.ZeniaSutton@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>18000133</CNE>
    <LastName>Illana</LastName>
    <FirstName>Cain Garrison</FirstName>
    <DateofBirth>2011-06-28</DateofBirth>
    <ClasseName>Gsea2</ClasseName>
    <Phone>08 63 95 56 88</Phone>
    <Email>Illana.CainGarrison@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>18000134</CNE>
    <LastName>Tanner</LastName>
    <FirstName>Vincent Cleveland</FirstName>
    <DateofBirth>2010-03-25</DateofBirth>
    <ClasseName>Gsea2</ClasseName>
    <Phone>06 91 77 24 77</Phone>
    <Email>Tanner.VincentCleveland@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>18000135</CNE>
    <LastName>Burke</LastName>
    <FirstName>Hermione Dillard</FirstName>
    <DateofBirth>2013-01-25</DateofBirth>
    <ClasseName>Gsea2</ClasseName>
    <Phone>08 63 70 66 45</Phone>
    <Email>Burke.HermioneDillard@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>18000136</CNE>
    <LastName>Keiko</LastName>
    <FirstName>Montana Gilbert</FirstName>
    <DateofBirth>2005-03-20</DateofBirth>
    <ClasseName>Gsea2</ClasseName>
    <Phone>08 56 13 13 96</Phone>
    <Email>Keiko.MontanaGilbert@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>18000137</CNE>
    <LastName>Joshua</LastName>
    <FirstName>Patrick Thompson</FirstName>
    <DateofBirth>2009-03-25</DateofBirth>
    <ClasseName>Gsea2</ClasseName>
    <Phone>08 07 72 68 48</Phone>
    <Email>Joshua.PatrickThompson@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>18000138</CNE>
    <LastName>Gabriel</LastName>
    <FirstName>Dominic Short</FirstName>
    <DateofBirth>2008-05-26</DateofBirth>
    <ClasseName>Gsea2</ClasseName>
    <Phone>07 73 56 27 01</Phone>
    <Email>Gabriel.DominicShort@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>18000139</CNE>
    <LastName>Aspen</LastName>
    <FirstName>Steel Byrd</FirstName>
    <DateofBirth>2014-02-24</DateofBirth>
    <ClasseName>Gsea2</ClasseName>
    <Phone>08 88 11 61 17</Phone>
    <Email>Aspen.SteelByrd@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>18000140</CNE>
    <LastName>Heidi</LastName>
    <FirstName>Gary Malone</FirstName>
    <DateofBirth>2003-07-12</DateofBirth>
    <ClasseName>Gsea2</ClasseName>
    <Phone>03 29 82 81 46</Phone>
    <Email>Heidi.GaryMalone@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>18000141</CNE>
    <LastName>Vaughan</LastName>
    <FirstName>Joelle Green</FirstName>
    <DateofBirth>2002-01-23</DateofBirth>
    <ClasseName>Gsea2</ClasseName>
    <Phone>09 81 11 12 83</Phone>
    <Email>Vaughan.JoelleGreen@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>18000142</CNE>
    <LastName>Dalton</LastName>
    <FirstName>Zenia Porter</FirstName>
    <DateofBirth>2006-07-27</DateofBirth>
    <ClasseName>Gsea2</ClasseName>
    <Phone>08 52 98 55 86</Phone>
    <Email>Dalton.ZeniaPorter@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>18000143</CNE>
    <LastName>Sage</LastName>
    <FirstName>Lionel Manning</FirstName>
    <DateofBirth>2005-08-26</DateofBirth>
    <ClasseName>Gsea2</ClasseName>
    <Phone>02 12 78 29 81</Phone>
    <Email>Sage.LionelManning@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>18000144</CNE>
    <LastName>Igor</LastName>
    <FirstName>Karina Christensen</FirstName>
    <DateofBirth>2011-10-01</DateofBirth>
    <ClasseName>Gsea2</ClasseName>
    <Phone>02 43 63 87 56</Phone>
    <Email>Igor.KarinaChristensen@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>18000145</CNE>
    <LastName>Noelani</LastName>
    <FirstName>Leroy Sargent</FirstName>
    <DateofBirth>2012-05-12</DateofBirth>
    <ClasseName>Gsea2</ClasseName>
    <Phone>08 21 16 77 18</Phone>
    <Email>Noelani.LeroySargent@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>18000146</CNE>
    <LastName>Yvette</LastName>
    <FirstName>Graham Hughes</FirstName>
    <DateofBirth>2012-06-25</DateofBirth>
    <ClasseName>Gsea2</ClasseName>
    <Phone>08 24 61 36 32</Phone>
    <Email>Yvette.GrahamHughes@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>18000147</CNE>
    <LastName>Hamilton</LastName>
    <FirstName>Reuben Nixon</FirstName>
    <DateofBirth>2007-04-20</DateofBirth>
    <ClasseName>Gsea2</ClasseName>
    <Phone>02 25 65 77 63</Phone>
    <Email>Hamilton.ReubenNixon@etu.uae.ac.ma</Email>
  </Student><Student>
    <CNE>18000148</CNE>
    <LastName>Ethan</LastName>
    <FirstName>Oprah Vasquez</FirstName>
    <DateofBirth>2005-04-19</DateofBirth>
    <ClasseName>Gsea2</ClasseName>
    <Phone>07 67 65 24 65</Phone>
    <Email>Ethan.OprahVasquez@etu.uae.ac.ma</Email>
  </Student></Students>
